Repository panther-labs/panther, pull requests merged in 2020-04, with the labels that each got.

#625 Simplify Doc Menus
  docs/gitbook/README.md
  docs/gitbook/SUMMARY.md
  docs/gitbook/historical-search/README.md
  docs/gitbook/log-analysis/log-processing/README.md
  docs/gitbook/policies/scanning/README.md
Labels: documentation

#612 Log subscriptions
  api/lambda/core/log_analysis/log_processor/models/api.go
  deployments/bootstrap.yml
  deployments/panther_config.yml
  internal/compliance/aws_event_processor/processor/accounts.go
  internal/compliance/aws_event_processor/processor/handler.go
  internal/compliance/aws_event_processor/processor/handler_test.go
  internal/log_analysis/datacatalog_updater/main/lambda.go
  internal/log_analysis/datacatalog_updater/main/lambda_test.go
  internal/log_analysis/log_processor/destinations/s3.go
  internal/log_analysis/log_processor/destinations/s3_test.go
  internal/log_analysis/rules_engine/src/__init__.py
  internal/log_analysis/rules_engine/src/main.py
  internal/log_analysis/rules_engine/src/output.py
  internal/log_analysis/rules_engine/tests/test_main.py
  internal/log_analysis/rules_engine/tests/test_output.py
  tools/config/config.go
  tools/mage/deploy.go
Labels: enhancement

#632 Updated latency threshold
  tools/cfngen/cloudwatchcf/alarms_appsync.go
  tools/cfngen/cloudwatchcf/testdata/generated_test_alarms.json
Labels: operations

#635 Add ConfirmDevice to ignore list
  internal/compliance/aws_event_processor/processor/process.go
Labels: bug

#644 Change onboarding check
  tools/mage/deploy_onboard.go
Labels: deployment

#657 Fix data races found by testing with -race
  internal/log_analysis/log_processor/destinations/s3_test.go
  pkg/awsglue/glue.go
Labels: bug

#662 Fix error handling for 404 in compliance alert processor
  internal/compliance/alert_processor/processor/processor.go
Labels: bug

#649 End user security responsibilities
  docs/gitbook/SUMMARY.md
  docs/gitbook/development.md
  docs/gitbook/historical-search/README.md
  docs/gitbook/log-analysis/rules/README.md
  docs/gitbook/policies/automatic-remediation/aws/README.md
  docs/gitbook/policies/policies/aws/README.md
  docs/gitbook/quick-start.md
  docs/gitbook/security-privacy.md
Labels: documentation, security

#668 Whitelist cognito:ForgotPassword in event processor
  internal/compliance/aws_event_processor/processor/process.go
Labels: enhancement

#669 Minor fixes for CT parser
  internal/log_analysis/log_processor/parsers/awslogs/cloudtrail.go
  internal/log_analysis/log_processor/parsers/awslogs/cloudtrail_test.go
Labels: bug

#673 Whitelist cognitio:UpdateUserAttributes for event processor
  internal/compliance/aws_event_processor/processor/process.go
Labels: enhancement

#676 Simplify mage setup, fmt, test:ci
  .circleci/config.yml
  .golangci.yml
  docs/gitbook/development.md
  docs/gitbook/quick-start.md
  go.mod
  go.sum
  internal/log_analysis/log_processor/destinations/s3_test.go
  package.json
  pkg/shutil/hash.go
  tools/mage/build_namespace.go
  tools/mage/clean.go
  tools/mage/deploy.go
  tools/mage/doc.go
  tools/mage/fmt.go
  tools/mage/setup.go
  tools/mage/setup_namespace.go
  tools/mage/swagger.go
  tools/mage/test_namespace.go
  tools/mage/util.go
  tools/mage/util_hash.go
  tools/mage/util_hash_test.go
Labels: mage

#678 Add alert-delivery lambda to dashboards
  tools/dashboards/alerts.go
  tools/dashboards/overview.go
Labels: bug

#686 [docs] panther osquery tutorial
  docs/gitbook/.gitbook/assets/tutorials/cloudwatch-metrics.png
  docs/gitbook/.gitbook/assets/tutorials/log-source-config.png
  docs/gitbook/.gitbook/assets/tutorials/osquery-panther.png
  docs/gitbook/SUMMARY.md
  docs/gitbook/tutorials/osquery-log-analysis.md
Labels: documentation

#689 Include CFN stack name as billing tag
  tools/mage/deploy_template.go
Labels: deployment

#688 Improve s3queue
  cmd/opstools/s3queue/integration_test.go
  cmd/opstools/s3queue/s3queue.go
  cmd/opstools/s3queue/s3queue/main.go
  cmd/opstools/s3queue/s3queue_test.go
  docs/gitbook/operations/ops-home.md
  pkg/awsbatch/sqsbatch/send_message_batch.go
  pkg/awsbatch/sqsbatch/send_message_batch_test.go
Labels: operations

#694 Add support for step functions in alarm generation
  tools/cfngen/cloudwatchcf/alarms.go
  tools/cfngen/cloudwatchcf/alarms_sfn.go
  tools/cfngen/cloudwatchcf/testdata/cf.yml
  tools/cfngen/cloudwatchcf/testdata/generated_test_alarms.json
Labels: operations

#696 Stabilize Go modules, format generated API files
  go.mod
  go.sum
  tools/mage/build_namespace.go
  tools/mage/deploy.go
  tools/mage/fmt.go
  tools/mage/fmt_license.go
  tools/mage/setup.go
Labels: mage

#695 Refactor pkg/awsathena
  pkg/awsathena/integration_test.go
  pkg/awsathena/query.go
  tools/athenaviews/athenaviews.go
Labels: historical search

#698 [deployments] rename alb and sg
  deployments/bootstrap.yml
Labels: web team

#731 Add bucket region detection to s3queue
  cmd/opstools/s3queue/integration_test.go
  cmd/opstools/s3queue/s3queue.go
  cmd/opstools/s3queue/s3queue/main.go
Labels: bug

#718 Use worker model to limit max number of parallel go builds
  tools/mage/build_namespace.go
  tools/mage/util.go
Labels: mage

#734 Improve logging for s3queue
  cmd/opstools/s3queue/s3queue/main.go
Labels: enhancement

#732 Fix output path for mage build:tools
  tools/mage/build_namespace.go
Labels: bug

#690 Support Global Analysis Type
  api/gateway/analysis/api.yml
  api/gateway/analysis/client/operations/create_global_parameters.go
  api/gateway/analysis/client/operations/create_global_responses.go
  api/gateway/analysis/client/operations/delete_globals_parameters.go
  api/gateway/analysis/client/operations/delete_globals_responses.go
  api/gateway/analysis/client/operations/get_global_parameters.go
  api/gateway/analysis/client/operations/get_global_responses.go
  api/gateway/analysis/client/operations/modify_global_parameters.go
  api/gateway/analysis/client/operations/modify_global_responses.go
  api/gateway/analysis/client/operations/operations_client.go
  api/gateway/analysis/models/analysis_type.go
  api/gateway/analysis/models/global.go
  api/gateway/analysis/models/update_global.go
  deployments/core.yml
  docs/gitbook/operations/runbooks.md
  docs/gitbook/policies/policies/README.md
  go.mod
  go.sum
  internal/compliance/policy_engine/src/policy.py
  internal/compliance/policy_engine/tests/integration.py
  internal/compliance/resource_processor/processor/analysis_api.go
  internal/compliance/resource_processor/processor/handler.go
  internal/core/analysis_api/handlers/clients.go
  internal/core/analysis_api/handlers/create_global.go
  internal/core/analysis_api/handlers/delete_global.go
  internal/core/analysis_api/handlers/dynamo.go
  internal/core/analysis_api/handlers/get.go
  internal/core/analysis_api/handlers/get_enabled_analyses.go
  internal/core/analysis_api/handlers/modify_global.go
  internal/core/analysis_api/handlers/sqs.go
  internal/core/analysis_api/handlers/util.go
  internal/core/analysis_api/handlers/util_test.go
  internal/core/analysis_api/main/integration_test.go
  internal/core/analysis_api/main/lambda.go
  internal/core/layer_manager/main/integration_test.go
  internal/core/layer_manager/main/lambda.go
  internal/core/layer_manager/manager/clients.go
  internal/core/layer_manager/manager/handle.go
  internal/log_analysis/rules_engine/src/engine.py
  internal/log_analysis/rules_engine/src/rule.py
  internal/log_analysis/rules_engine/tests/test_engine.py
  tools/mage/deploy.go
  tools/mage/teardown.go
Labels: backend team

#719 Add and register gitlab log parsers
  docs/gitbook/log-analysis/log-processing/supported-logs/GitLab.md
  internal/log_analysis/log_processor/parsers/gitlablogs/api.go
  internal/log_analysis/log_processor/parsers/gitlablogs/api_test.go
  internal/log_analysis/log_processor/parsers/gitlablogs/audit.go
  internal/log_analysis/log_processor/parsers/gitlablogs/audit_test.go
  internal/log_analysis/log_processor/parsers/gitlablogs/exceptions.go
  internal/log_analysis/log_processor/parsers/gitlablogs/exceptions_test.go
  internal/log_analysis/log_processor/parsers/gitlablogs/git.go
  internal/log_analysis/log_processor/parsers/gitlablogs/git_test.go
  internal/log_analysis/log_processor/parsers/gitlablogs/gitlablogs.go
  internal/log_analysis/log_processor/parsers/gitlablogs/integrations.go
  internal/log_analysis/log_processor/parsers/gitlablogs/integrations_test.go
  internal/log_analysis/log_processor/parsers/gitlablogs/rails.go
  internal/log_analysis/log_processor/parsers/gitlablogs/rails_test.go
  internal/log_analysis/log_processor/registry/registry.go
  web/src/constants.ts
Labels: logs

#706 Suricata DNS parser
  docs/gitbook/log-analysis/log-processing/supported-logs/Suricata.md
  internal/log_analysis/log_processor/parsers/suricatalogs/dns.go
  internal/log_analysis/log_processor/parsers/suricatalogs/dns_test.go
  internal/log_analysis/log_processor/registry/registry.go
  web/src/constants.ts
Labels: logs

#738 Increase delay before deleting bucket in teardown to avoid errors
  tools/mage/teardown.go
Labels: bug

#733 [awslogs] AWS CloudTrailInsight parser
  docs/gitbook/log-analysis/log-processing/supported-logs/AWS.md
  docs/gitbook/log-analysis/log-processing/supported-logs/GitLab.md
  internal/log_analysis/log_processor/parsers/awslogs/cloudtrail_insights.go
  internal/log_analysis/log_processor/parsers/awslogs/cloudtrail_insights_test.go
  internal/log_analysis/log_processor/parsers/gitlablogs/git_test.go
  internal/log_analysis/log_processor/parsers/gitlablogs/integrations_test.go
  internal/log_analysis/log_processor/parsers/testutil/testutil.go
  internal/log_analysis/log_processor/registry/registry.go
  web/src/constants.ts
Labels: logs

#739 Tag all Panther aws objects with the version of the deployed sw
  tools/mage/deploy.go
  tools/mage/deploy_template.go
Labels: operations

#748 Expand s3 notification message from rules engine to have all the attributes
  internal/log_analysis/rules_engine/src/output.py
Labels: bug

#647 Athena Lambda API
  api/graphql/schema.graphql
  api/lambda/database/models/api.go
  deployments/appsync.yml
  deployments/bootstrap.yml
  deployments/log_analysis.yml
  deployments/panther_config.yml
  docs/gitbook/operations/runbooks.md
  go.mod
  go.sum
  internal/core/database_api/athena/driver/api/api.go
  internal/core/database_api/athena/driver/api/error.go
  internal/core/database_api/athena/driver/api/execute_async_query.go
  internal/core/database_api/athena/driver/api/execute_async_query_notify.go
  internal/core/database_api/athena/driver/api/execute_query.go
  internal/core/database_api/athena/driver/api/get_databases.go
  internal/core/database_api/athena/driver/api/get_query_results.go
  internal/core/database_api/athena/driver/api/get_query_results_link.go
  internal/core/database_api/athena/driver/api/get_query_status.go
  internal/core/database_api/athena/driver/api/get_tables.go
  internal/core/database_api/athena/driver/api/get_tables_detail.go
  internal/core/database_api/athena/driver/api/integration_test.go
  internal/core/database_api/athena/driver/api/invoke_notify_lambda.go
  internal/core/database_api/athena/driver/api/notify_appsync.go
  internal/core/database_api/athena/driver/api/stop_query.go
  internal/core/database_api/athena/driver/main/main.go
  internal/core/database_api/athena/testutils/testutils.go
  pkg/awsglue/glue.go
  tools/mage/deploy.go
  web/__generated__/schema.tsx
Labels: enhancement

#743 Globals Bulk Upload Support
  api/gateway/analysis/api.yml
  api/gateway/analysis/configmodels.go
  api/gateway/analysis/models/bulk_upload_result.go
  internal/core/analysis_api/handlers/bulk_upload.go
  internal/core/analysis_api/handlers/get.go
  internal/core/analysis_api/handlers/util.go
  internal/core/analysis_api/main/integration_test.go
Labels: backend team

#762 v1.1.0 release - fix doc link
  docs/gitbook/development.md
  docs/gitbook/quick-start.md
  web/src/helpers/utils.tsx
Labels: documentation

#772 Fixed parameter
  web/src/components/wizards/ComplianceSourceWizard/StackDeploymentPanel/StackDeployment.tsx
  web/src/components/wizards/LogSourceWizard/StackDeploymentPanel/StackDeployment.tsx
Labels: bug, frontend

#773 Fixed template format
  deployments/auxiliary/cloudformation/panther-cloudsec-iam.yml
  internal/core/source_api/api/testdata/panther-cloudsec-iam-updated.yml
Labels: bug

#770 Add Enterprise Snowflake Documentation
  docs/gitbook/.gitbook/assets/snowflake-run.png
  docs/gitbook/.gitbook/assets/snowflake-upload.png
  docs/gitbook/SUMMARY.md
  docs/gitbook/enterprise/snowflake.md
Labels: documentation

#742 Refactor cfn deploy process
  deployments/bootstrap_gateway.yml
  deployments/cloud_security.yml
  deployments/core.yml
  deployments/log_analysis.yml
  docs/gitbook/development.md
  docs/gitbook/operations/runbooks.md
  internal/core/analysis_api/main/integration_test.go
  pkg/shutil/archive.go
  requirements.txt
  tools/cfngen/cloudwatchcf/alarms.go
  tools/cfngen/cloudwatchcf/alarms_apigw.go
  tools/cfngen/cloudwatchcf/alarms_appsync.go
  tools/cfngen/cloudwatchcf/alarms_ddb.go
  tools/cfngen/cloudwatchcf/alarms_elb.go
  tools/cfngen/cloudwatchcf/alarms_lambda.go
  tools/cfngen/cloudwatchcf/alarms_sfn.go
  tools/cfngen/cloudwatchcf/alarms_sns.go
  tools/cfngen/cloudwatchcf/alarms_sqs.go
  tools/cfngen/cloudwatchcf/metrics.go
  tools/cfngen/cloudwatchcf/metrics_lambda.go
  tools/cfngen/cloudwatchcf/util.go
  tools/cfngen/cloudwatchcf/walkmap.go
  tools/cfnparse/parse.go
  tools/mage/build_namespace.go
  tools/mage/cfngen.go
  tools/mage/deploy.go
  tools/mage/deploy_certificate.go
  tools/mage/deploy_frontend.go
  tools/mage/deploy_onboard.go
  tools/mage/deploy_template.go
  tools/mage/deploy_test.go
  tools/mage/doc.go
  tools/mage/fmt.go
  tools/mage/fmt_license.go
  tools/mage/glue_namespace.go
  tools/mage/setup.go
  tools/mage/swagger.go
  tools/mage/swagger_test.go
  tools/mage/teardown.go
  tools/mage/test_namespace.go
  tools/mage/testdata/valid-api-expected-output.yml
  tools/mage/util.go
  tools/mage/util_cfn.go
Labels: mage

#787 Added some diagrams to the development page
  docs/gitbook/.gitbook/assets/data-flow-diagram.png
  docs/gitbook/.gitbook/assets/detailed-arch-diagram.png
  docs/gitbook/.gitbook/assets/high-level-arch-diagram.png
  docs/gitbook/development.md
Labels: documentation

#798 HTML escape user name in password reset email
  internal/core/users_api/api/cognito_trigger.go
Labels: security

#797 Update deployment role
  deployments/auxiliary/cloudformation/panther-deployment-role.yml
  deployments/auxiliary/terraform/panther_deployment_role/main.tf
Labels: bug

#809 Teardown fixes and consistent doc ordering
  docs/gitbook/operations/runbooks.md
  tools/cfndoc/cfndoc.go
  tools/cfndoc/cfndoc_test.go
  tools/mage/teardown.go
  tools/mage/util_cfn.go
  tools/mage/util_hash.go
Labels: mage
