Repository panther-labs/panther, pull requests merged in 2020-11, with the labels that each got.

#1905 Bugfixing small issues related to title links
  web/src/components/cards/AlertCard/AlertCard.tsx
  web/src/components/cards/AlertCard/__snapshots__/AlertCard.test.tsx.snap
  web/src/components/cards/RuleCard/RuleCard.test.tsx
  web/src/components/cards/RuleCard/RuleCard.tsx
  web/src/pages/ListAlerts/ListAlertBreadcrumbFilters/ListAlertBreadcrumbFilters.tsx
  web/src/pages/ListComplianceSources/ComplianceSourceCard/ComplianceSourceCard.tsx
  web/src/pages/ListDestinations/DestinationCards/DestinationCard.tsx
  web/src/pages/ListDestinations/DestinationCards/__tests__/__snapshots__/DestinationCard.test.tsx.snap
  web/src/pages/ListLogSources/LogSourceCards/LogSourceCard.tsx
  web/src/pages/ListRules/ListRules.tsx
  web/src/pages/ListRules/ListRulesBreadcrumbFilters/ListRulesBreadcrumbFilters.tsx
Labels: team:web

#1918 Sort return of ListLogTypes() for stable output (units tests were non-deterministic)
  internal/core/source_api/api/list_logtypes.go
Labels: enterprise-backport, sync-to-release

#1922 Remove unused env vars for the log processor tables custom resource
  deployments/log_analysis.yml
  internal/core/custom_resources/resources/log_processor_tables.go
Labels: team:data analytics

#1924 Chore: update pounce
  package-lock.json
  package.json
Labels: sync-to-release, team:web

#1927 fix: sort rules by enabled/disabled status
  web/src/pages/ListRules/ListRulesFilters/ListRulesFilters.tsx
Labels: bug, p0, sync-to-release, team:core infra

#1934 Rename "Dedup Message" to "Dedup String"
  web/src/components/forms/RuleForm/RuleFormTestResult/RuleFormTestResult.tsx
  web/src/components/forms/RuleForm/RuleFormTestResult/__snapshots__/RuleFormTestResult.test.tsx.snap
Labels: sync-to-release, team:web

#1932 Using regional STS endpoint
  internal/log_analysis/log_processor/sources/s3_client_cache.go
  internal/log_analysis/log_processor/sources/s3_client_cache_test.go
  internal/log_analysis/log_processor/sources/s3_test.go
Labels: bug, p0, sync-to-release

#1930 fix: integration tests
  internal/core/analysis_api/main/integration_test.go
Labels: bug, p0, sync-to-release

#1929 Fix credential generation
  internal/compliance/snapshot_poller/pollers/aws/clients.go
Labels: bug, sync-to-release, team:security engineering

#1951 Mitigate race in creating Athena views
  internal/log_analysis/datacatalog_updater/process/create_tables.go
Labels: sync-to-release

#1954 Fix wording
  web/src/constants.ts
Labels: sync-to-release

#1953 Update deployment role for athena ddb connector
  deployments/auxiliary/cloudformation/panther-deployment-role.yml
  deployments/auxiliary/terraform/panther_deployment_role/main.tf
Labels: sync-to-release

#1961 Tidy config for Athena workgroups
  deployments/bootstrap_gateway.yml
Labels: sync-to-release, team:data analytics

#1969 Fix Datepicker bugs
  package-lock.json
  package.json
  web/src/components/forms/BaseRuleForm/BaseRuleFormTestSection/BaseRuleFormTestSection.tsx
Labels: sync-to-release, team:web

#1948 Refactor log analysis sns code to prepare for s3sns opstool
  deployments/log_analysis.yml
  internal/compliance/aws_event_processor/processor/handler.go
  internal/log_analysis/datacatalog_updater/process/process.go
  internal/log_analysis/datacatalog_updater/process/process_test.go
  internal/log_analysis/datacatalog_updater/process/s3notification.go
  internal/log_analysis/log_processor/destinations/s3.go
  internal/log_analysis/log_processor/destinations/s3_test.go
  internal/log_analysis/notify/s3.go
  internal/log_analysis/notify/sns.go
Labels: team:data processing

#1962 Fix remediation permissions
  deployments/cloud_security.yml
Labels: bug, p0, sync-to-release

#1967 Fixing ddb filtering
  deployments/log_analysis.yml
  internal/log_analysis/alerts_api/table/list.go
Labels: bug, p0, sync-to-release

#1978 fix: broken redirect after sign-in
  web/src/apollo/createErrorLink.ts
  web/src/components/GuardedRoute/GuardedRoute.tsx
Labels: team:web

#1975 Quick fix for deployment updates
  internal/log_analysis/datacatalog_updater/process/create_tables.go
  internal/log_analysis/datacatalog_updater/process/create_tables_test.go
  pkg/stringset/stringset.go
  pkg/stringset/stringset_test.go
Labels: sync-to-release

#1964 Refactoring log pulling
  internal/log_analysis/log_processor/main/lambda.go
  internal/log_analysis/log_processor/main/lambda_test.go
  internal/log_analysis/log_processor/processor/rescale_test.go
  internal/log_analysis/log_processor/processor/stream.go
  internal/log_analysis/log_processor/processor/stream_test.go
  internal/log_analysis/log_processor/sources/s3.go
  internal/log_analysis/log_processor/sources/s3_test.go
  pkg/awsbatch/sqsbatch/receive_message.go
  pkg/testutils/awsmocks.go
Labels: p2

#1959 Feat: Remove Zoom-button controls from charts
  web/src/components/charts/ResetButton/ResetButton.tsx
  web/src/components/charts/ResetButton/index.tsx
  web/src/components/charts/TimeSeriesChart/TimeSeriesChart.tsx
  web/src/components/charts/ZoomControls/index.tsx
Labels: team:web

#1944 Fix time related date range offset
  package-lock.json
  package.json
  web/src/components/fields/DateRangeInput/DateRangeInput.test.tsx
  web/src/components/fields/DateRangeInput/DateRangeInput.tsx
  web/src/components/fields/DateRangeInput/__snapshots__/DateRangeInput.test.tsx.snap
Labels: sync-to-release, team:web

#1971 Slightly change default Log Analysis Overview Date Range
  web/src/components/GuardedRoute/GuardedRoute.tsx
  web/src/helpers/utils.tsx
  web/src/pages/LogAnalysisOverview/LogAnalysisOverview.test.tsx
  web/src/pages/LogAnalysisOverview/LogAnalysisOverview.tsx
Labels: enhancement, team:web

#1988 fix: reverse mini-chart for TimeSeries charts
  web/src/components/charts/TimeSeriesChart/TimeSeriesChart.tsx
Labels: bug, sync-to-release, team:web

#1995 Reverting reading change
  internal/log_analysis/log_processor/processor/processor.go
  internal/log_analysis/log_processor/sources/s3.go
Labels: sync-to-release

#1943 Feat: Add illustration for "no results found"
  web/src/assets/illustrations/nothing-found.svg
  web/src/components/NoResultsFound/NoResultsFound.test.tsx
  web/src/components/NoResultsFound/NoResultsFound.tsx
  web/src/components/NoResultsFound/__snapshots__/NoResultsFound.test.tsx.snap
  web/src/components/NoResultsFound/index.tsx
  web/src/pages/ListAlerts/ListAlerts.tsx
  web/src/pages/ListPolicies/ListPolicies.tsx
  web/src/pages/ListResources/ListResources.tsx
  web/src/pages/ListRules/ListRules.tsx
  web/src/pages/LogAnalysisOverview/AlertsSection/AlertsSection.tsx
  web/src/pages/PolicyDetails/PolicyDetails.tsx
  web/src/pages/ResourceDetails/ResourceDetails.tsx
  web/src/pages/RuleDetails/RuleAlertsListing/RuleAlertsListing.tsx
  web/src/pages/RuleDetails/RuleDetails.test.tsx
Labels: enhancement, team:web

#1990 fix: reset pagination upon filtering
  package-lock.json
  package.json
  web/src/pages/ListRules/ListRulesBreadcrumbFilters/ListRulesBreadcrumbFilters.tsx
Labels: sync-to-release, team:web

#2003 Remove remediation-api gateway
  api/gateway/remediation/api.yml
  api/gateway/remediation/client/operations/list_remediations_parameters.go
  api/gateway/remediation/client/operations/list_remediations_responses.go
  api/gateway/remediation/client/operations/operations_client.go
  api/gateway/remediation/client/operations/remediate_resource_async_parameters.go
  api/gateway/remediation/client/operations/remediate_resource_async_responses.go
  api/gateway/remediation/client/operations/remediate_resource_parameters.go
  api/gateway/remediation/client/operations/remediate_resource_responses.go
  api/gateway/remediation/client/panther_remediation_api_client.go
  api/gateway/remediation/models/error.go
  api/gateway/remediation/models/remediate_resource.go
  api/gateway/remediation/models/remediations.go
  api/lambda/remediation/models/api.go
  deployments/appsync.yml
  deployments/bootstrap_gateway.yml
  deployments/cloud_security.yml
  deployments/master.yml
  internal/compliance/alert_processor/processor/processor.go
  internal/compliance/alert_processor/processor/processor_test.go
  internal/compliance/remediation_api/handlers/apihandlers.go
  internal/compliance/remediation_api/handlers/apihandlers_test.go
  internal/compliance/remediation_api/handlers/get.go
  internal/compliance/remediation_api/handlers/get_test.go
  internal/compliance/remediation_api/handlers/post.go
  internal/compliance/remediation_api/handlers/post_test.go
  internal/compliance/remediation_api/main/lambda.go
  internal/compliance/remediation_api/main/lambda_test.go
  internal/compliance/remediation_api/remediation/invoke.go
  internal/compliance/remediation_api/remediation/invoke_test.go
  internal/compliance/remediation_api/remediation/remediation.go
  internal/compliance/remediation_processor/main/lambda.go
  tools/mage/deploy/deploy.go
Labels: team:core infra

#1994 Add complex FE testing in rule & alert filtering
  web/src/hooks/useUrlParams.tsx
  web/src/pages/ListAlerts/ListAlertBreadcrumbFilters/ListAlertBreadcrumbFilters.tsx
  web/src/pages/ListAlerts/ListAlertFilters/DropdownFilters.tsx
  web/src/pages/ListAlerts/ListAlerts.test.tsx
  web/src/pages/ListPolicies/ListPoliciesActions/ListPoliciesActions.tsx
  web/src/pages/ListResources/ListResourcesActions/ListResourcesActions.tsx
  web/src/pages/ListRules/ListRules.test.tsx
  web/src/pages/ListRules/ListRulesFilters/DropdownFilters.tsx
  web/src/pages/ListRules/ListRulesFilters/ListRulesFilters.tsx
  web/src/pages/LogAnalysisOverview/LogAnalysisOverviewBreadcrumbFilters/LogAnalysisOverviewBreadcrumbFilters.tsx
Labels: enhancement, team:web

#2002 Add destination data to Rule Cards
  api/gateway/analysis/api.yml
  api/gateway/analysis/models/policy_summary.go
  api/gateway/analysis/models/rule_summary.go
  api/graphql/schema.graphql
  internal/core/analysis_api/handlers/dynamo.go
  internal/core/analysis_api/handlers/list.go
  internal/core/analysis_api/handlers/list_test.go
  internal/core/analysis_api/main/integration_test.go
  web/__generated__/schema.tsx
  web/__tests__/__mocks__/builders.generated.ts
  web/src/components/RelatedDestinations/RelatedDestinations.tsx
  web/src/components/cards/RuleCard/RuleCard.test.tsx
  web/src/components/cards/RuleCard/RuleCard.tsx
  web/src/graphql/fragments/PolicyTeaser.generated.ts
  web/src/graphql/fragments/PolicyTeaser.graphql
  web/src/graphql/queries/listDestinations.generated.ts
  web/src/graphql/queries/listDestinations.graphql
  web/src/hooks/__tests__/useDetectionDestinations.test.tsx
  web/src/hooks/useDetectionDestinations.tsx
  web/src/pages/ListRules/graphql/listRules.generated.ts
  web/src/pages/ListRules/graphql/listRules.graphql
  web/src/pages/RuleDetails/RuleCardDetails/RuleCardDetails.tsx
  web/src/pages/RuleDetails/RuleDetails.test.tsx
Labels: team:web

#2011 chore: update to v1.12.0
  VERSION
Labels: sync-to-release

#2008 Bulk change for Alert status [2/2]
  web/src/components/dropdowns/UpdateAlertDropdown/UpdateAlertDropdown.tsx
  web/src/components/utils/SelectContext/SelectAllCheckbox.tsx
  web/src/components/utils/SelectContext/SelectCheckbox.tsx
  web/src/components/utils/SelectContext/SelectContext.test.tsx
  web/src/components/utils/SelectContext/SelectContext.tsx
  web/src/graphql/queries/index.tsx
  web/src/graphql/queries/updateAlertStatus.generated.ts
  web/src/graphql/queries/updateAlertStatus.graphql
  web/src/helpers/analytics.ts
  web/src/pages/ListAlerts/ListAlertSelection/ListAlertSelection.tsx
  web/src/pages/ListAlerts/ListAlerts.test.tsx
  web/src/pages/ListAlerts/ListAlerts.tsx
  web/src/pages/RuleDetails/RuleAlertsListing/RuleAlertsListing.tsx
  web/src/pages/RuleDetails/RuleDetails.test.tsx
Labels: team:web

#2006 Update tables only if integration adds new log types
  internal/core/source_api/api/update_integration.go
  internal/core/source_api/api/update_integration_test.go
Labels: sync-to-release

#2013 Extract domains from CT sourceIPAddress field
  internal/log_analysis/log_processor/parsers/awslogs/cloudtrail.go
  internal/log_analysis/log_processor/parsers/awslogs/testdata/cloudtrail_tests.yml
Labels: sync-to-release

#2020 Keep only 1 required field for each Cloudflare log type
  internal/log_analysis/log_processor/parsers/cloudflarelogs/cloudflarelogs.go
  internal/log_analysis/log_processor/parsers/cloudflarelogs/firewall.go
  internal/log_analysis/log_processor/parsers/cloudflarelogs/http_request.go
  internal/log_analysis/log_processor/parsers/cloudflarelogs/spectrum.go
  internal/log_analysis/log_processor/parsers/cloudflarelogs/testdata/cloudflare_tests.yml
Labels: sync-to-release

#2017 Fixed 2 break lines issues & inactive color for Chart legend
  package-lock.json
  package.json
  web/src/components/GenericItemCard/GenericItemCard.tsx
  web/src/components/cards/AlertCard/__snapshots__/AlertCard.test.tsx.snap
  web/src/components/charts/TimeSeriesChart/TimeSeriesChart.tsx
  web/src/constants.ts
  web/src/pages/ListDestinations/DestinationCards/__tests__/__snapshots__/DestinationCard.test.tsx.snap
Labels: team:web

#2023 Version bump to v1.12.1
  VERSION
Labels: sync-to-release

#2030 Several AWS client-related fixes for log processor
  internal/log_analysis/log_processor/common/common.go
  internal/log_analysis/log_processor/sources/s3_client_cache.go
Labels: sync-to-release

#2035 Bump warn threshold for custom resources lambda
  deployments/bootstrap_gateway.yml
Labels: monitoring

#2040 GraphQL: Use undocumented `Long` scalar
  api/graphql/schema.graphql
  web/__generated__/schema.tsx
  web/__tests__/__mocks__/builders.generated.ts
  web/codegen.yml
  web/codegen/buildGraphqlResourcesPlugin.js
  web/codegen/buildGraphqlResourcesPlugin.ts
  web/src/components/charts/TimeSeriesChart/TimeSeriesChart.tsx
  web/src/pages/LogAnalysisOverview/AlertsBySeverity/AlertsBySeverity.tsx
  web/src/pages/LogAnalysisOverview/AlertsCharts/AlertsCharts.tsx
  web/src/pages/LogAnalysisOverview/EventsByLatency/EventsByLatency.tsx
  web/src/pages/LogAnalysisOverview/EventsByLogType/EventsByLogType.tsx
  web/src/pages/LogAnalysisOverview/LogTypeCharts/LogTypeCharts.tsx
  web/src/pages/LogAnalysisOverview/graphql/getLogAnalysisMetrics.generated.ts
Labels: bug, sync-to-release, team:web

#1863 Opsgenie eu region
  api/graphql/schema.graphql
  api/lambda/outputs/models/api.go
  internal/core/alert_delivery/outputs/opsgenie.go
  internal/core/alert_delivery/outputs/opsgenie_test.go
  internal/core/alert_delivery/outputs/utils.go
  internal/core/outputs_api/api/get_output.go
  internal/core/outputs_api/api/get_outputs.go
  internal/core/outputs_api/api/utils.go
  package-lock.json
  web/__generated__/schema.jsx
  web/__generated__/schema.tsx
  web/__tests__/__mocks__/builders.generated.ts
  web/__tests__/env.ts
  web/__tests__/jest.config.js
  web/src/assets/custom-webhook-minimal-logo.svg
  web/src/components/forms/DestinationFormSwitcher/DestinationFormSwitcher.tsx
  web/src/components/forms/OpsgenieDestinationForm/OpsGenieDestinationForm.test.tsx
  web/src/components/forms/OpsgenieDestinationForm/OpsgenieDestinationForm.tsx
  web/src/components/wizards/CreateDestinationWizard/ConfigureDestinationPanel/ConfigureDestinationPanel.tsx
  web/src/graphql/fragments/DestinationFull.generated.ts
  web/src/graphql/fragments/DestinationFull.graphql
  web/src/pages/EditDestination/EditDestination.test.tsx
  web/src/pages/ListDestinations/DestinationCards/OpsGenieDestinationCard.tsx
  web/src/pages/ListDestinations/DestinationCards/__tests__/OpsGenieDestinationCard.test.tsx
Labels: bug, p0, sync-to-release, team:web

#2037 Add support for scanning indicators on slice fields
  internal/log_analysis/log_processor/pantherlog/encoders.go
  internal/log_analysis/log_processor/pantherlog/jsoniter.go
  internal/log_analysis/log_processor/pantherlog/jsoniter_test.go
  internal/log_analysis/log_processor/pantherlog/meta.go
Labels: sync-to-release

#2054 fix: opsgenie default value
  internal/core/alert_delivery/outputs/opsgenie.go
  internal/core/alert_delivery/outputs/opsgenie_test.go
  internal/core/alert_delivery/outputs/utils.go
  internal/core/outputs_api/api/utils.go
Labels: bug, sync-to-release, team:web

#2057 Opsgenie incorrect region display
  internal/core/outputs_api/api/utils.go
Labels: bug, p0, sync-to-release

#2051 Redesign multiple Cards in UI
  web/src/components/GenericItemCard/GenericItemCard.test.tsx
  web/src/components/GenericItemCard/GenericItemCard.tsx
  web/src/components/GenericItemCard/__snapshots__/GenericItemCard.test.tsx.snap
  web/src/components/RelatedDestinations/RelatedDestinations.tsx
  web/src/components/cards/AlertCard/AlertCard.test.tsx
  web/src/components/cards/AlertCard/AlertCard.tsx
  web/src/components/cards/AlertCard/__snapshots__/AlertCard.test.tsx.snap
  web/src/components/cards/RuleCard/RuleCard.test.tsx
  web/src/components/cards/RuleCard/RuleCard.tsx
  web/src/components/cards/RuleCard/RuleCardOptions/RuleCardOptions.tsx
  web/src/pages/ListAlerts/ListAlerts.tsx
  web/src/pages/ListComplianceSources/ComplianceSourceCard/ComplianceSourceCard.tsx
  web/src/pages/ListComplianceSources/ComplianceSourceCard/ComplianceSourceCardOptions.tsx
  web/src/pages/ListDestinations/DestinationCards/DestinationCard.tsx
  web/src/pages/ListDestinations/DestinationCards/DestinationCardOptions.tsx
  web/src/pages/ListDestinations/DestinationCards/__tests__/__snapshots__/DestinationCard.test.tsx.snap
  web/src/pages/ListLogSources/LogSourceCards/LogSourceCard.tsx
  web/src/pages/ListLogSources/LogSourceCards/LogSourceCardOptions.tsx
  web/src/pages/LogAnalysisOverview/LogAnalysisOverview.test.tsx
  web/src/pages/RuleDetails/RuleAlertsListing/RuleAlertsListing.tsx
  web/src/pages/RuleDetails/RuleDetails.test.tsx
Labels: team:web

#2066 Minor polling fixes
  internal/compliance/aws_event_processor/processor/elbv2.go
  internal/compliance/aws_event_processor/processor/rds.go
  internal/compliance/aws_event_processor/processor/waf-regional.go
  internal/compliance/snapshot_poller/pollers/aws/awstest/eks.go
  internal/compliance/snapshot_poller/pollers/aws/eks_cluster.go
  internal/compliance/snapshot_poller/pollers/aws/eks_cluster_test.go
Labels: bug, cloud security, sync-to-release

#2074 chore: bump to v1.13.0-RC
  VERSION
Labels: sync-to-release

#2078 Don't fail the full batch in case of partial failures
  internal/log_analysis/log_processor/processor/stream.go
  internal/log_analysis/log_processor/processor/stream_test.go
Labels: sync-to-release

#2083 fix: adds missing snowflake permissions
  deployments/auxiliary/cloudformation/panther-deployment-role.yml
  deployments/auxiliary/terraform/panther_deployment_role/main.tf
Labels: sync-to-release

#2070 Redesign Cards fixes
  web/src/components/BulletedLogTypeList/__snapshots__/BulletedLogTypeList.test.tsx.snap
  web/src/components/GenericItemCard/GenericItemCard.tsx
  web/src/components/LimitItemDisplay/LimitItemDisplay.tsx
  web/src/components/LimitItemDisplay/__snapshots__/LimitItemDisplay.test.tsx.snap
  web/src/components/NotificationJewel/NotificationJewel.tsx
  web/src/components/NotificationJewel/index.tsx
  web/src/components/RelatedDestinations/RelatedDestinations.tsx
  web/src/components/cards/AlertCard/AlertCard.tsx
  web/src/components/cards/AlertCard/__snapshots__/AlertCard.test.tsx.snap
  web/src/components/cards/RuleCard/RuleCard.tsx
  web/src/components/cards/RuleCard/RuleCardOptions/RuleCardOptions.tsx
  web/src/pages/ListComplianceSources/ComplianceSourceCard/ComplianceSourceCard.tsx
  web/src/pages/ListComplianceSources/ComplianceSourceCard/ComplianceSourceCardOptions.tsx
  web/src/pages/ListDestinations/DestinationCards/DestinationCard.tsx
  web/src/pages/ListDestinations/DestinationCards/DestinationCardOptions.tsx
  web/src/pages/ListDestinations/DestinationCards/__tests__/__snapshots__/DestinationCard.test.tsx.snap
  web/src/pages/ListLogSources/LogSourceCards/LogSourceCard.tsx
  web/src/pages/ListLogSources/LogSourceCards/LogSourceCardOptions.tsx
Labels: team:web

#2082 role policy lookup return nil rather than throw error
  internal/compliance/snapshot_poller/pollers/aws/awstest/iam.go
  internal/compliance/snapshot_poller/pollers/aws/iam_role.go
  internal/compliance/snapshot_poller/pollers/aws/iam_role_test.go
Labels: bug

#2077 Oncall Fixes
  deployments/core.yml
  internal/compliance/aws_event_processor/processor/process.go
  internal/compliance/snapshot_poller/pollers/aws/cloudformation_stack.go
  internal/core/source_api/api/get_integration_template.go
  internal/core/source_api/api/vars.go
  web/src/components/wizards/ComplianceSourceWizard/StackDeploymentPanel/StackDeployment.tsx
  web/src/components/wizards/S3LogSourceWizard/StackDeploymentPanel/StackDeployment.tsx
Labels: bug, sync-to-release

#2087 Sort by displayName by default instead of ID
  api/graphql/schema.graphql
  api/lambda/analysis/models/rules.go
  go.mod
  go.sum
  internal/core/analysis_api/handlers/list.go
  internal/core/analysis_api/handlers/list_rules.go
  internal/core/analysis_api/handlers/list_test.go
  web/__generated__/schema.tsx
  web/__tests__/__mocks__/builders.generated.ts
  web/src/pages/ListRules/ListRulesFilters/ListRulesFilters.tsx
Labels: team:core infra

#2089 Kill Swagger
  .circleci/config.yml
  build/images/README.md
  deployments/bootstrap_gateway.yml
  deployments/master.yml
  internal/core/alert_delivery/api/deliver_alert.go
  internal/core/alert_delivery/outputs/outputs.go
  internal/core/analysis_api/handlers/bulk_upload.go
  internal/core/analysis_api/handlers/dynamo.go
  internal/log_analysis/alerts_api/api/get_alert.go
  internal/log_analysis/alerts_api/api/list_alerts.go
  internal/log_analysis/alerts_api/api/update_alert_delivery.go
  pkg/gatewayapi/README.md
  pkg/gatewayapi/gateway_sig4_client.go
  pkg/gatewayapi/gateway_sig4_client_test.go
  pkg/gatewayapi/router.go
  pkg/gatewayapi/router_test.go
  pkg/genericapi/replace_nils.go
  pkg/genericapi/replace_nils_test.go
  pkg/genericapi/router.go
  tools/cfnstacks/cfnstacks.go
  tools/mage/build/swagger.go
  tools/mage/build/swagger_test.go
  tools/mage/build/testdata/api/first.yml
  tools/mage/build/testdata/no-api.yml
  tools/mage/build/testdata/valid-api-expected-output.yml
  tools/mage/build/testdata/valid-api.yml
  tools/mage/clients/aws.go
  tools/mage/deploy/deploy.go
  tools/mage/gen/gen.go
  tools/mage/master/build.go
  tools/mage/setup/setup.go
  tools/mage/test/cfn.go
  tools/mage/util/files.go
Labels: team:core infra

#2098 Add default sortBy for policies and data models
  internal/core/analysis_api/handlers/list.go
  internal/core/analysis_api/handlers/list_data_models.go
  internal/core/analysis_api/handlers/list_policies.go
  internal/core/analysis_api/handlers/list_rules.go
Labels: team:core infra

#2081 FE: Showcase S3 & Cloud Security Additional Steps
  web/src/assets/box-logo.svg
  web/src/assets/crowdstrike-minimal-logo.svg
  web/src/assets/panther-enterprise-minimal-logo.svg
  web/src/assets/statuses/real-time-notification.svg
  web/src/components/wizards/ComplianceSourceWizard/SourceConfigurationPanel/SourceConfigurationPanel.tsx
  web/src/components/wizards/ComplianceSourceWizard/ValidationPanel/ValidationPanel.tsx
  web/src/components/wizards/S3LogSourceWizard/ValidationPanel/ValidationPanel.tsx
  web/src/constants.ts
  web/src/hooks/useHover.test.tsx
  web/src/hooks/useHover.tsx
  web/src/pages/CreateComplianceSource/CreateComplianceSource.test.tsx
  web/src/pages/CreateLogSource/CreateS3LogSource/CreateS3LogSource.test.tsx
  web/src/pages/EditComplianceSource/ΕditComplianceSource.test.tsx
  web/src/pages/EditS3LogSource/ΕditS3LogSource.test.tsx
  web/src/pages/LogSourceOnboarding/LogSourceCard/LogSourceCard.tsx
  web/src/pages/LogSourceOnboarding/LogSourceOnboarding.tsx
Labels: team:web

#2102 Fix: visual bugs & issues with TimeSeriesChart
  web/src/components/charts/TimeSeriesChart/ChartTooltip.tsx
  web/src/components/charts/TimeSeriesChart/TimeSeriesChart.tsx
  web/src/components/charts/TimeSeriesChart/index.tsx
Labels: bug, enhancement, team:web

#2099 Add EU regions for publishing
  tools/mage/master/deploy.go
Labels: team:core infra

#2096 Update Go/Python libs, prevent dirty repo states
  deployments/panther_config.yml
  go.mod
  go.sum
  internal/log_analysis/awsglue/table_metadata_test.go
  pkg/genericapi/validator.go
  requirements-top-level.txt
  requirements.txt
  tools/mage/build/layer.go
  tools/mage/master/build.go
  tools/mage/master/deploy.go
  tools/mage/setup/setup.go
Labels: mage, team:core infra

#2104 Fix bug that prevented successful check of EnsureDatabase()
  internal/log_analysis/awsglue/wrappers.go
Labels: bug

#2097 Scanning rate limit error fixes
  internal/compliance/aws_event_processor/processor/dynamodb.go
  internal/compliance/aws_event_processor/processor/rds.go
  internal/compliance/snapshot_poller/pollers/aws/clients.go
  internal/compliance/snapshot_poller/pollers/aws/dynamodb_table.go
  internal/compliance/snapshot_poller/pollers/aws/dynamodb_table_test.go
  internal/compliance/snapshot_poller/pollers/aws/poll.go
  internal/compliance/snapshot_poller/pollers/aws/rds_instance.go
  internal/compliance/snapshot_poller/pollers/aws/rds_instance_test.go
  internal/compliance/snapshot_poller/pollers/lambda_test.go
Labels: cloud security, sync-to-release

#2071 Fix connection reset by peer errors in log processor
  cmd/opstools/s3queue/s3queue.go
  deployments/log_analysis.yml
  deployments/master.yml
  deployments/panther_config.yml
  internal/log_analysis/log_processor/common/common.go
  internal/log_analysis/log_processor/destinations/s3.go
  internal/log_analysis/log_processor/destinations/s3_test.go
  internal/log_analysis/log_processor/main/lambda.go
  internal/log_analysis/log_processor/processor/processor.go
  internal/log_analysis/log_processor/processor/processor_test.go
  internal/log_analysis/log_processor/processor/rescale.go
  internal/log_analysis/log_processor/processor/rescale_test.go
  internal/log_analysis/log_processor/processor/stream.go
  internal/log_analysis/log_processor/processor/stream_test.go
  internal/log_analysis/log_processor/s3pipe/s3pipe.go
  internal/log_analysis/log_processor/s3pipe/s3pipe_test.go
  internal/log_analysis/log_processor/sources/s3.go
  internal/log_analysis/log_processor/sources/s3_test.go
  pkg/priorityq/priorityq.go
  pkg/priorityq/priorityq_test.go
  pkg/testutils/awsmocks.go
  tools/mage/deploy/config.go
  tools/mage/deploy/deploy.go
Labels: p0, sync-to-release, team:data analytics

#2111 Backport glueschema.InferColumnsCustom
  internal/log_analysis/awsglue/glueschema/glueschema.go
  internal/log_analysis/awsglue/glueschema/glueschema_test.go
Labels: enterprise-backport

#2047 SNS Title Input Validation
  internal/core/alert_delivery/outputs/sns.go
  internal/core/alert_delivery/outputs/sns_test.go
  pkg/testutils/awsmocks.go
Labels: bug

#2075 minor udm update
  internal/log_analysis/rules_engine/src/data_model.py
  internal/log_analysis/rules_engine/src/enriched_event.py
  internal/log_analysis/rules_engine/tests/test_enriched_event.py
Labels: team:security engineering

#2108 Update supported regions (and publish all of them)
  tools/mage/clients/aws.go
  tools/mage/deploy/deploy.go
  tools/mage/deploy/deploy_template.go
  tools/mage/deploy/frontend.go
  tools/mage/master/build.go
  tools/mage/master/deploy.go
  tools/mage/master/publish.go
  tools/mage/util/s3.go
  tools/mage/util/version.go
Labels: mage, team:core infra

#1884 Build alarms with explicit name instead of reference and other small CFN fixes
  deployments/cloud_security.yml
  deployments/core.yml
  deployments/log_analysis.yml
Labels: team:core infra

#2101 fix: add default SERVER_PORT to Dockerfile (web)
  deployments/Dockerfile
Labels: bug, team:web

#2124 ci: run web tests in worker pool
  package.json
Labels: team:web

#2121 Feat: Support Page
  web/src/assets/illustrations/feedback.svg
  web/src/assets/illustrations/mail.svg
  web/src/components/Navigation/Navigation.tsx
  web/src/helpers/analytics.ts
  web/src/pages/Support/Support.test.tsx
  web/src/pages/Support/Support.tsx
  web/src/pages/Support/SupportItemCard.tsx
  web/src/pages/Support/__snapshots__/Support.test.tsx.snap
  web/src/pages/Support/index.tsx
  web/src/routes.tsx
  web/src/urls.ts
Labels: team:web

#2128 FE: Fix issues with running web tests locally
  web/__tests__/.env.test
  web/__tests__/jest.config.js
  web/__tests__/setupEnv.ts
  web/__tests__/setupPantherConfig.ts
  web/__tests__/setupTests.ts
  web/src/pages/RuleDetails/RuleDetails.test.tsx
Labels: bug, team:web

#2136 fix: web dockerfile
  deployments/Dockerfile
Labels: team:web

#2140 FE: Add anonymous analytics to sources
  web/src/components/GenericItemCard/GenericItemCard.tsx
  web/src/components/wizards/S3LogSourceWizard/S3SourceConfigurationPanel/S3SourceConfigurationPanel.tsx
  web/src/components/wizards/SqsSourceWizard/SqsSourceConfigurationPanel/SqsSourceConfigurationPanel.tsx
  web/src/helpers/analytics.ts
  web/src/pages/CreateComplianceSource/CreateComplianceSource.test.tsx
  web/src/pages/CreateComplianceSource/CreateComplianceSource.tsx
  web/src/pages/CreateLogSource/CreateS3LogSource/CreateS3LogSource.test.tsx
  web/src/pages/CreateLogSource/CreateS3LogSource/CreateS3LogSource.tsx
  web/src/pages/CreateLogSource/CreateSqsLogSource/CreateSqsLogSource.test.tsx
  web/src/pages/CreateLogSource/CreateSqsLogSource/CreateSqsLogSource.tsx
  web/src/pages/EditComplianceSource/EditComplianceSource.tsx
  web/src/pages/EditComplianceSource/ΕditComplianceSource.test.tsx
  web/src/pages/EditS3LogSource/EditS3LogSource.tsx
  web/src/pages/EditS3LogSource/ΕditS3LogSource.test.tsx
  web/src/pages/EditSqsLogSource/EditSqsLogSource.tsx
  web/src/pages/EditSqsLogSource/ΕditSqsLogSource.test.tsx
  web/src/pages/ListDestinations/DestinationCards/__tests__/__snapshots__/DestinationCard.test.tsx.snap
Labels: sync-to-release, team:web

#2139 FE: change default order for rules
  web/src/components/Navigation/SecondaryNavigations/ComplianceNavigation.tsx
  web/src/components/Navigation/SecondaryNavigations/LogAnalysisNavigation.tsx
  web/src/pages/AlertDetails/AlertDetailsBanner/AlertDetailsBanner.tsx
  web/src/pages/AlertDetails/AlertDetailsBanner/__snapshots__/AlertDetailsBanner.test.tsx.snap
Labels: sync-to-release, team:web

#2150 Removed lastEventReceived from S3 & SQS card
  web/src/pages/ListLogSources/LogSourceCards/S3LogSourceCard.test.tsx
  web/src/pages/ListLogSources/LogSourceCards/S3LogSourceCard.tsx
  web/src/pages/ListLogSources/LogSourceCards/SqsLogSourceCard.test.tsx
  web/src/pages/ListLogSources/LogSourceCards/SqsLogSourceCard.tsx
Labels: bug, sync-to-release, team:web

#2118 Fix rule error
  internal/log_analysis/rules_engine/src/engine.py
  internal/log_analysis/rules_engine/src/main.py
  internal/log_analysis/rules_engine/src/rule.py
  internal/log_analysis/rules_engine/tests/test_main.py
  internal/log_analysis/rules_engine/tests/test_rule.py
Labels: sync-to-release

#2142 Validate instance IDs exist before sending
  internal/compliance/aws_event_processor/processor/rds.go
Labels: bug, cloud security

#2160 Hardcode source-api version
  deployments/core.yml
Labels: bug, p0
