Repository panther-labs/panther, pull requests merged in 2020-07, with the labels that each got.

#1100 Fixing classifier behavior
  internal/log_analysis/log_processor/classification/classifier.go
  internal/log_analysis/log_processor/classification/classifier_test.go
  internal/log_analysis/log_processor/parsers/awslogs/vpc_flow.go
  internal/log_analysis/log_processor/parsers/awslogs/vpc_flow_test.go
  internal/log_analysis/log_processor/parsers/juniperlogs/access.go
  internal/log_analysis/log_processor/parsers/testutil/testutil.go
Labels: bug

#1107 Update ops and snowflake docs
  docs/gitbook/enterprise/snowflake.md
  docs/gitbook/operations/ops-home.md
Labels: documentation

#1093 Remove mage migrations
  tools/mage/deploy.go
  tools/mage/migrations.go
  tools/mage/teardown.go
  tools/mage/test_namespace.go
  tools/mage/util_cfn.go
Labels: mage

#1117 Prevent persistence after user deletion
  api/lambda/users/models/api.go
  api/lambda/users/models/validator_test.go
  deployments/appsync.yml
  deployments/core.yml
  internal/core/custom_resources/resources/panther_user.go
  internal/core/users_api/api/api.go
  internal/core/users_api/api/invite_user.go
  internal/core/users_api/api/invite_user_test.go
  internal/core/users_api/api/list_users_test.go
  internal/core/users_api/api/remove_user.go
  internal/core/users_api/api/remove_user_test.go
  internal/core/users_api/api/reset_user_password.go
  internal/core/users_api/api/reset_user_password_test.go
  internal/core/users_api/api/update_user.go
  internal/core/users_api/api/update_user_test.go
  internal/core/users_api/cognito/delete_user.go
  internal/core/users_api/cognito/delete_user_test.go
  internal/core/users_api/cognito/list_users.go
  internal/core/users_api/cognito/list_users_test.go
  internal/core/users_api/cognito/mock_cognito_client.go
  internal/core/users_api/cognito/mock_gateway.go
  internal/core/users_api/cognito/users_gateway.go
  internal/core/users_api/main/integration_test.go
Labels: p1, security

#1115 Destination overrides (oss)
  api/gateway/analysis/api.yml
  api/gateway/analysis/configmodels.go
  api/gateway/analysis/models/enabled_policy.go
  api/gateway/analysis/models/output_ids.go
  api/gateway/analysis/models/policy.go
  api/gateway/analysis/models/rule.go
  api/gateway/analysis/models/update_policy.go
  api/gateway/analysis/models/update_rule.go
  api/graphql/schema.graphql
  api/lambda/outputs/models/api.go
  docs/gitbook/cloud-security/policies/README.md
  internal/compliance/alert_processor/models/api.go
  internal/compliance/alert_processor/processor/processor.go
  internal/compliance/resource_processor/processor/handler.go
  internal/core/alert_delivery/delivery/dispatch.go
  internal/core/alert_delivery/delivery/dispatch_test.go
  internal/core/alert_delivery/delivery/handle.go
  internal/core/alert_delivery/delivery/outputs.go
  internal/core/alert_delivery/delivery/outputs_test.go
  internal/core/alert_delivery/models/api.go
  internal/core/alert_delivery/outputs/asana_test.go
  internal/core/alert_delivery/outputs/github_test.go
  internal/core/alert_delivery/outputs/jira_test.go
  internal/core/alert_delivery/outputs/msteams_test.go
  internal/core/alert_delivery/outputs/opsgenie_test.go
  internal/core/alert_delivery/outputs/slack_test.go
  internal/core/analysis_api/handlers/bulk_upload.go
  internal/core/analysis_api/handlers/create_policy.go
  internal/core/analysis_api/handlers/create_rule.go
  internal/core/analysis_api/handlers/dynamo.go
  internal/core/analysis_api/handlers/get_enabled_analyses.go
  internal/core/analysis_api/handlers/modify_policy.go
  internal/core/analysis_api/handlers/modify_rule.go
  internal/core/analysis_api/handlers/util.go
  internal/core/analysis_api/handlers/util_test.go
  internal/core/analysis_api/main/integration_test.go
  internal/core/analysis_api/main/test_policies/always_true.json
  internal/core/analysis_api/main/test_policies/always_true.yml
  internal/core/analysis_api/main/test_policies/aws_cloudtrail_log_validation_enabled.py
  internal/core/analysis_api/main/test_policies/aws_cloudtrail_log_validation_enabled.yml
  internal/log_analysis/alert_forwarder/forwarder/forwarder.go
  web/__generated__/schema.tsx
  web/src/components/forms/BaseRuleForm/BaseRuleFormCoreSection/BaseRuleFormCoreSection.tsx
  web/src/components/forms/BaseRuleForm/useListAvailableDestinations.tsx
  web/src/graphql/fragments/PolicyDetailsMain.generated.ts
  web/src/graphql/fragments/PolicyDetailsMain.graphql
  web/src/graphql/fragments/RuleBasic.generated.ts
  web/src/graphql/fragments/RuleBasic.graphql
  web/src/hooks/useFormSessionRestoration.tsx
  web/src/pages/CreatePolicy/CreatePolicy.tsx
  web/src/pages/CreateRule/CreateRule.tsx
  web/src/pages/EditPolicy/EditPolicy.tsx
  web/src/pages/EditPolicy/graphql/updatePolicy.generated.ts
  web/src/pages/EditPolicy/graphql/updatePolicy.graphql
  web/src/pages/EditRule/EditRule.tsx
  web/src/pages/EditRule/graphql/ruleDetails.generated.ts
  web/src/pages/EditRule/graphql/ruleDetails.graphql
Labels: alerting, backend team, frontend, p1

#1131 Fix typo and minor UI button stretch
  web/src/pages/ListAlerts/ListAlertsTable/ListAlertsTable.tsx
  web/src/pages/ListPolicies/ListPoliciesTable/ListPoliciesTable.tsx
Labels: bug, frontend

#1030 Add embedded metric wrapper
  internal/log_analysis/log_processor/common/metrics.go
  internal/log_analysis/log_processor/processor/processor.go
  internal/log_analysis/log_processor/processor/processor_test.go
  pkg/metrics/logger.go
Labels: enhancement, monitoring

#1099 Docs Refresh for Panther Analysis Tool and More
  docs/gitbook/.gitbook/assets/diagrams/panther_overview_transparent.png
  docs/gitbook/.gitbook/assets/globals/create-new-global.png
  docs/gitbook/.gitbook/assets/globals/list-globals.png
  docs/gitbook/README.md
  docs/gitbook/SUMMARY.md
  docs/gitbook/analysis/built-in-packs.md
  docs/gitbook/analysis/caching.md
  docs/gitbook/analysis/globals.md
  docs/gitbook/analysis/panther-analysis-tool.md
  docs/gitbook/analysis/run-time.md
  docs/gitbook/cloud-security/automatic-remediation/README.md
  docs/gitbook/cloud-security/automatic-remediation/writing-custom-remediations.md
  docs/gitbook/cloud-security/policies/README.md
  docs/gitbook/destinations/README.md
  docs/gitbook/destinations/asana.md
  docs/gitbook/destinations/github.md
  docs/gitbook/destinations/jira.md
  docs/gitbook/destinations/microsoft-teams.md
  docs/gitbook/destinations/opsgenie.md
  docs/gitbook/destinations/pagerduty.md
  docs/gitbook/destinations/slack.md
  docs/gitbook/log-analysis/README.md
  docs/gitbook/log-analysis/log-processing/log-setup/gsuite.md
  docs/gitbook/log-analysis/log-processing/writing-parsers.md
  docs/gitbook/log-analysis/panther-fields.md
  docs/gitbook/log-analysis/rules/README.md
  docs/gitbook/log-analysis/rules/panther-cli.md
  docs/gitbook/log-analysis/rules/ui-workflow.md
  docs/gitbook/quick-start.md
  docs/gitbook/tutorials/osquery-log-analysis.md
Labels: documentation

#1124 Remove policy test resourcetype fields
  api/gateway/analysis/api.yml
  api/gateway/analysis/engine.go
  api/gateway/analysis/models/unit_test_swagger.go
  api/graphql/schema.graphql
  internal/core/analysis_api/handlers/bulk_upload.go
  internal/core/analysis_api/handlers/test_policy.go
  internal/core/analysis_api/handlers/util.go
  internal/core/analysis_api/main/integration_test.go
  web/__generated__/schema.tsx
  web/src/components/forms/BaseRuleForm/BaseRuleFormTestSection/BaseRuleFormTestSection.tsx
  web/src/components/forms/PolicyForm/PolicyForm.tsx
  web/src/components/forms/RuleForm/RuleForm.tsx
  web/src/graphql/fragments/PolicyDetailsExtra.generated.ts
  web/src/graphql/fragments/PolicyDetailsExtra.graphql
  web/src/graphql/fragments/RuleFull.generated.ts
  web/src/graphql/fragments/RuleFull.graphql
  web/src/pages/EditPolicy/graphql/updatePolicy.generated.ts
  web/src/pages/EditPolicy/graphql/updatePolicy.graphql
  web/src/pages/EditRule/graphql/ruleDetails.generated.ts
  web/src/pages/EditRule/graphql/ruleDetails.graphql
Labels: backend team, frontend

#1137 Fix Navlink active URL checking
  web/src/components/Navigation/NavLink.tsx
  web/src/helpers/utils.tsx
Labels: bug, frontend

#1130 Added CloudWatch Events parser
  docs/gitbook/log-analysis/log-processing/supported-logs/AWS.md
  internal/log_analysis/log_processor/parsers/awslogs/awslogs.go
  internal/log_analysis/log_processor/parsers/awslogs/cloudwatch_events.go
  internal/log_analysis/log_processor/parsers/awslogs/cloudwatch_events_test.go
  internal/log_analysis/log_processor/parsers/testutil/testutil.go
  web/src/constants.ts
Labels: logs

#1126 Updating Gitlab production logs
  docs/gitbook/log-analysis/log-processing/supported-logs/GitLab.md
  internal/log_analysis/log_processor/parsers/awslogs/cloudtrail_test.go
  internal/log_analysis/log_processor/parsers/awslogs/cloudwatch_events_test.go
  internal/log_analysis/log_processor/parsers/awslogs/guardduty_test.go
  internal/log_analysis/log_processor/parsers/awslogs/utils_test.go
  internal/log_analysis/log_processor/parsers/gitlablogs/rails.go
  internal/log_analysis/log_processor/parsers/gitlablogs/rails_test.go
  internal/log_analysis/log_processor/parsers/testutil/testutil.go
  pkg/box/box.go
  pkg/unbox/unbox.go
Labels: bug, logs

#1128 Invalidate sessions on Password Change
  web/src/components/Header/Header.tsx
  web/src/components/forms/ChangePasswordForm/ChangePasswordForm.tsx
  web/src/components/forms/EditProfileForm/EditProfileForm.tsx
  web/src/components/modals/DeleteUserModal/DeleteUserModal.tsx
  web/src/components/sidesheets/EditAccountSidesheet/EditAccountSidesheet.tsx
  web/src/components/utils/AuthContext/AuthContext.tsx
Labels: frontend, p1, security

#1090 Lessen differences between dev & prod front-end environments
  package-lock.json
  package.json
  web/scripts/serve.js
  web/scripts/start.js
  web/scripts/utils.js
  web/webpack.config.js
Labels: frontend

#1127 Update pouncejs to ^0.45.1
  package-lock.json
  package.json
Labels: bug, frontend

#1144 Refactor: stabilize module imports
  web/src/apollo/cleanParamsLink.ts
  web/src/apollo/createErrorLink.ts
  web/src/components/modals/ResetUserPasswordModal/ResetUserPasswordModal.tsx
  web/src/components/sidesheets/PolicyBulkUploadSidesheet/PolicyBulkUploadSidesheet.tsx
  web/src/hooks/usePolicySuppression.tsx
  web/src/hooks/useResourceRemediation.tsx
Labels: frontend

#1154 Fix up custom certificate documentation
  docs/gitbook/SUMMARY.md
  docs/gitbook/operations/configuring-custom-domains.md
Labels: documentation

#1133 Remove session storage entries upon form submission
  web/src/hooks/useFormSessionRestoration.tsx
Labels: bug, frontend

#1123 Updated Totp form to showcase code instead of only showing QR
  web/src/components/forms/MfaForm/MfaForm.tsx
  web/src/components/forms/TotpForm/TotpForm.tsx
  web/src/helpers/utils.tsx
Labels: waiting for feedback

#1139 Add an illustrated blank slate when no alerts are in place
  web/src/pages/RuleDetails/RuleDetails.tsx
Labels: enhancement, frontend

#1147 Remove build:lambda and build:tools from CI
  tools/mage/test_namespace.go
Labels: mage

#1159 Add extra validation for string parameters in master stack
  deployments/master.yml
Labels: bug, deployment

#1165 Configurable ALB ingress security group
  deployments/bootstrap.yml
  deployments/master.yml
  deployments/panther_config.yml
  tools/config/config.go
  tools/mage/deploy.go
Labels: deployment

#1173 Feat: Lazy-load charting library
  web/src/components/charts/BarChart/BarChart.tsx
Labels: frontend

#1167 Add initial SAML documentation, fix broken links
  docs/gitbook/.gitbook/assets/saml-okta-metadata.png
  docs/gitbook/.gitbook/assets/saml-okta-new-app.png
  docs/gitbook/.gitbook/assets/saml-okta1.png
  docs/gitbook/.gitbook/assets/saml-okta2.png
  docs/gitbook/.gitbook/assets/saml-okta3.png
  docs/gitbook/.gitbook/assets/saml-okta4.png
  docs/gitbook/.gitbook/assets/saml-onelogin1.png
  docs/gitbook/.gitbook/assets/saml-onelogin2.png
  docs/gitbook/.gitbook/assets/saml-onelogin3.png
  docs/gitbook/.gitbook/assets/saml-onelogin4-inset.png
  docs/gitbook/.gitbook/assets/saml-onelogin4.png
  docs/gitbook/.gitbook/assets/saml-onelogin5.png
  docs/gitbook/SUMMARY.md
  docs/gitbook/analysis/globals.md
  docs/gitbook/analysis/panther-analysis-tool.md
  docs/gitbook/destinations/slack.md
  docs/gitbook/development.md
  docs/gitbook/enterprise/README.md
  docs/gitbook/enterprise/data-analytics/data-explorer.md
  docs/gitbook/enterprise/data-analytics/example-queries.md
  docs/gitbook/enterprise/saml/generic.md
  docs/gitbook/enterprise/saml/okta.md
  docs/gitbook/enterprise/saml/onelogin.md
  docs/gitbook/enterprise/saml/overview.md
  docs/gitbook/log-analysis/README.md
  docs/gitbook/log-analysis/log-processing/writing-parsers.md
  docs/gitbook/log-analysis/rules/README.md
  docs/gitbook/log-analysis/rules/ui-workflow.md
  docs/gitbook/log-analysis/setup.md
  docs/gitbook/quick-start.md
  docs/gitbook/tutorials/osquery-log-analysis.md
  docs/gitbook/tutorials/s3-monitoring-fundamentals.md
Labels: documentation

#1181 Use a composite alarm over all the primitive lambda alarms to reduce pages
  deployments/bootstrap_gateway.yml
  internal/core/custom_resources/resources/alarms.go
  internal/core/custom_resources/resources/alarms_api_gateway.go
  internal/core/custom_resources/resources/alarms_appsync.go
  internal/core/custom_resources/resources/alarms_dynamo.go
  internal/core/custom_resources/resources/alarms_elb.go
  internal/core/custom_resources/resources/alarms_lambda.go
  internal/core/custom_resources/resources/alarms_sfn.go
  internal/core/custom_resources/resources/alarms_sns.go
  internal/core/custom_resources/resources/alarms_sqs.go
Labels: operations

#1185 Prepend account info to alarm descriptions
  deployments/bootstrap_gateway.yml
  deployments/master.yml
  internal/core/custom_resources/main/lambda.go
  internal/core/custom_resources/resources/alarms.go
  internal/core/custom_resources/resources/clients.go
  tools/mage/deploy.go
Labels: operations

#1180 Metrics API Rework
  api/lambda/metrics/models/api.go
  internal/core/alert_delivery/delivery/dispatch.go
  internal/core/alert_delivery/main/lambda.go
  internal/core/metrics_api/api/alert_metrics.go
  internal/core/metrics_api/api/get_metrics.go
  internal/core/metrics_api/api/get_metrics_test.go
  internal/core/metrics_api/api/log_processor_metrics.go
  internal/core/metrics_api/main/integration_test.go
  internal/log_analysis/alert_forwarder/forwarder/forwarder.go
  internal/log_analysis/log_processor/common/metrics.go
  internal/log_analysis/log_processor/processor/processor.go
  internal/log_analysis/log_processor/processor/processor_test.go
Labels: alerting, backend team, monitoring, p1

#1199 Fixing nil pointer dereference
  internal/compliance/snapshot_poller/pollers/aws/cloudwatchlogs_log_group.go
  internal/log_analysis/log_processor/destinations/s3.go
Labels: bug

#1215 fix: issue with zIndex on error pages
  web/src/components/Layout/Layout.tsx
  web/src/pages/403/403.tsx
  web/src/pages/404/404.tsx
  web/src/pages/500/500.tsx
Labels: bug, p2

#1218 Fix issue with wrong test payload
  web/src/components/forms/BaseRuleForm/BaseRuleFormTestResultList/BaseRuleFormTestResultList.tsx
  web/src/hooks/useFastField.tsx
Labels: bug, frontend, p0

#1222 Add snowflake api configuration documentation
  docs/gitbook/.gitbook/assets/snowflake-secrets-page1.png
  docs/gitbook/.gitbook/assets/snowflake-secrets-page2.png
  docs/gitbook/.gitbook/assets/snowflake-secrets-page3.png
  docs/gitbook/enterprise/snowflake.md
Labels: documentation

#1220 Front-end: Don't restore form values if Cancel is clicked
  web/__tests__/jest.config.js
  web/__tests__/setup.ts
  web/__tests__/utils/helpers.ts
  web/src/components/forms/GlobalPythonModuleForm/GlobalPythonModuleForm.tsx
  web/src/components/forms/PolicyForm/PolicyForm.tsx
  web/src/components/forms/RuleForm/RuleForm.tsx
  web/src/components/utils/FormSessionRestoration/FormSessionRestoration.test.tsx
  web/src/components/utils/FormSessionRestoration/FormSessionRestoration.tsx
  web/src/hooks/useFormSessionRestoration.tsx
  web/src/pages/ListPolicies/ListPolicies.tsx
Labels: enhancement, frontend, p2

#1221 Add FOSSA directly to CI
  .circleci/config.yml
  .fossa.yml
  .golangci.yml
  README.md
Labels: ci

#1232 Finish SAML docs with Panther screenshots
  docs/gitbook/.gitbook/assets/login-page-with-sso.png
  docs/gitbook/.gitbook/assets/saml-okta-metadata.png
  docs/gitbook/.gitbook/assets/saml-panther-okta.png
  docs/gitbook/.gitbook/assets/saml-panther-onelogin.png
  docs/gitbook/.gitbook/assets/saml-parameters.png
  docs/gitbook/SUMMARY.md
  docs/gitbook/enterprise/saml/generic.md
  docs/gitbook/enterprise/saml/okta.md
  docs/gitbook/enterprise/saml/onelogin.md
  docs/gitbook/enterprise/saml/overview.md
Labels: documentation

#1234 Update snowflake docs
  docs/gitbook/enterprise/snowflake.md
Labels: documentation

#1202 Add `tcodec` package to handle timestamps during JSON decoding/encoding
  internal/log_analysis/awsglue/schema.go
  internal/log_analysis/log_processor/pantherlog/tcodec/extension.go
  internal/log_analysis/log_processor/pantherlog/tcodec/extension_test.go
  internal/log_analysis/log_processor/pantherlog/tcodec/registry.go
  internal/log_analysis/log_processor/pantherlog/tcodec/registry_test.go
  internal/log_analysis/log_processor/pantherlog/tcodec/tcodec.go
  internal/log_analysis/log_processor/pantherlog/tcodec/tcodec_test.go
Labels: backend team, enhancement, p2

#1204 Add jsoniter extension to force `omitempty` on all fields
  go.mod
  go.sum
  internal/log_analysis/log_processor/pantherlog/omitempty/omitempty.go
  internal/log_analysis/log_processor/pantherlog/omitempty/omitempty_test.go
Labels: backend team, enhancement, p2

#1239 Update SUMMARY.md to include Box setup docs
  docs/gitbook/SUMMARY.md
Labels: p1

#1242 Update SUMMARY.md to include Box setup docs
  docs/gitbook/SUMMARY.md
Labels: documentation

#1244 Move initial analysis set and add CFN parameter validation
  deployments/appsync.yml
  deployments/auxiliary/cloudformation/panther-deployment-role.yml
  deployments/bootstrap.yml
  deployments/bootstrap_gateway.yml
  deployments/cloud_security.yml
  deployments/core.yml
  deployments/log_analysis.yml
  deployments/master.yml
  deployments/onboard.yml
  deployments/panther_config.yml
  deployments/web_server.yml
  internal/core/custom_resources/resources/analysis_set.go
  internal/core/custom_resources/resources/clients.go
  tools/mage/deploy.go
  tools/mage/deploy_frontend.go
Labels: deployment

#1206 Decouple `awsglue` from other modules defining mappings
  internal/log_analysis/awsglue/quirks.go
  internal/log_analysis/awsglue/schema.go
  internal/log_analysis/log_processor/destinations/s3_test.go
  internal/log_analysis/log_processor/logtypes/registry.go
  internal/log_analysis/log_processor/logtypes/registry_test.go
  internal/log_analysis/log_processor/pantherlog/null/null_benchmark_test.go
  internal/log_analysis/log_processor/parsers/pantherlog.go
  internal/log_analysis/log_processor/parsers/parsers.go
  internal/log_analysis/log_processor/parsers/timestamp/timestamp.go
Labels: backend team, p2

#1263 Update snowflake docs for UI
  docs/gitbook/enterprise/snowflake.md
Labels: documentation

#1273 Missing a slash in the quick-start docs
  docs/gitbook/quick-start.md
Labels: documentation

#1278 Flatten mage build:tools output
  tools/mage/build_namespace.go
Labels: mage
