Repository panther-labs/panther, pull requests merged in 2020-09, with the labels that each got.

#1438 Fix deployment role permissions
  deployments/auxiliary/cloudformation/panther-deployment-role.yml
Labels: bug, deployment

#1450 Autogenerate deployment TF policy
  deployments/auxiliary/cloudformation/panther-deployment-role.yml
  deployments/auxiliary/terraform/panther_deployment_role/main.tf
  deployments/auxiliary/terraform/panther_deployment_role/variables.tf
  tools/mage/fmt.go
Labels: team:enterprise & automation

#1457 Fail when a source has an unknown log type
  internal/log_analysis/log_processor/processor/processor.go
  internal/log_analysis/log_processor/processor/processor_test.go
Labels: p1

#1441 Enhance Compliance Workflow
  web/src/assets/illustrations/cogs.svg
  web/src/assets/illustrations/lightning.svg
  web/src/assets/statuses/waiting.svg
  web/src/components/Wizard/Wizard.test.tsx
  web/src/components/Wizard/Wizard.tsx
  web/src/components/Wizard/WizardContext.tsx
  web/src/components/Wizard/WizardPanel.tsx
  web/src/components/Wizard/__snapshots__/Wizard.test.tsx.snap
  web/src/components/wizards/ComplianceSourceWizard/ComplianceSourceWizard.tsx
  web/src/components/wizards/ComplianceSourceWizard/SourceConfigurationPanel/SourceConfigurationPanel.tsx
  web/src/components/wizards/ComplianceSourceWizard/StackDeploymentPanel/StackDeployment.tsx
  web/src/components/wizards/ComplianceSourceWizard/SuccessPanel/SuccessPanel.tsx
  web/src/components/wizards/ComplianceSourceWizard/ValidationPanel/ValidationPanel.tsx
  web/src/components/wizards/ComplianceSourceWizard/ValidationPanel/index.tsx
  web/src/components/wizards/ComplianceSourceWizard/index.tsx
  web/src/components/wizards/CreateDestinationWizard/ChooseDestinationPanel/ChooseDestinationPanel.tsx
  web/src/components/wizards/CreateDestinationWizard/ConfigureDestinationPanel/ConfigureDestinationPanel.tsx
  web/src/components/wizards/CreateDestinationWizard/CreateDestinationWizard.tsx
  web/src/components/wizards/EditDestinationWizard/ConfigureDestinationPanel/ConfigureDestinationPanel.tsx
  web/src/components/wizards/S3LogSourceWizard/StackDeploymentPanel/StackDeployment.tsx
  web/src/components/wizards/common/DestinationTestPanel/DestinationTestPanel.tsx
  web/src/helpers/utils.tsx
  web/src/pages/CreateComplianceSource/CreateComplianceSource.test.tsx
  web/src/pages/CreateComplianceSource/CreateComplianceSource.tsx
  web/src/pages/EditComplianceSource/EditComplianceSource.tsx
  web/src/pages/EditComplianceSource/ΕditComplianceSource.test.tsx
  web/src/pages/ListComplianceSources/ComplianceSourceCard/ComplianceSourceCard.tsx
  web/src/pages/LogSourceOnboarding/LogSourceOnboarding.tsx
Labels: team:web

#1465 http redirect
  deployments/web_server.yml
Labels: team:security engineering

#1467 Fix nil ptr in filterByTitleContains()
  internal/log_analysis/alerts_api/table/list.go
Labels: bug

#1469 Remove unused model field from the alert
  internal/core/alert_delivery/api/deliver_alert.go
  internal/core/alert_delivery/api/deliver_alert_test.go
  internal/log_analysis/alerts_api/table/table.go
Labels: bug, team:operations

#1454 Backport changes to apigen and lambdamux
  api/lambda/logtypes/models_gen.go
  internal/core/logtypesapi/api.go
  internal/core/logtypesapi/api_test.go
  internal/core/logtypesapi/available.go
  internal/core/logtypesapi/available_test.go
  internal/core/logtypesapi/client/lambdaclient_gen.go
  internal/core/logtypesapi/dynamodb.go
  internal/core/logtypesapi/lambdaclient_gen.go
  internal/core/logtypesapi/main/lambda.go
  pkg/x/apigen/apigen.go
  pkg/x/apigen/internal/methods.go
  pkg/x/apigen/internal/models.go
  pkg/x/apigen/lambdaclient/lambdaclient.go
  pkg/x/apigen/templates.go
  pkg/x/lambdamux/batch.go
  pkg/x/lambdamux/batch_test.go
  pkg/x/lambdamux/demux.go
  pkg/x/lambdamux/demux_test.go
  pkg/x/lambdamux/mux.go
Labels: enterprise-backport

#1461 Fix conflict for GitLab logs
  internal/log_analysis/log_processor/parsers/gitlablogs/api_test.go
  internal/log_analysis/log_processor/parsers/gitlablogs/rails.go
  internal/log_analysis/log_processor/parsers/gitlablogs/rails_test.go
Labels: bug, team:data processing

#1478 hotfix: Fix Label link for source
  web/src/pages/ListLogSources/LogSourceCards/LogSourceCard.tsx
Labels: team:web

#1479 Re-fetch alerts on every rule page visit
  web/src/pages/RuleDetails/RuleDetails.tsx
Labels: team:web

#1493 Fix mage master:deploy
  magefile.go
  tools/mage/master/build.go
  tools/mage/master/deploy.go
  tools/mage/master/publish.go
Labels: mage, team:enterprise & automation

#1495 Remove app client custom resource and other release fixes
  deployments/auxiliary/cloudformation/panther-deployment-role.yml
  deployments/bootstrap_gateway.yml
  deployments/master.yml
  go.mod
  go.sum
  internal/core/custom_resources/resources/cognito_client_token_expiration.go
  internal/core/custom_resources/resources/map.go
  tools/mage/srcfmt/fmt.go
Labels: deployment, mage

#1489 Fix classification and source fields for SQS sources
  cmd/devtools/logprocessor/logprocessor/main.go
  cmd/devtools/pantherlog/pantherlog/main.go
  internal/log_analysis/log_processor/classification/classifier.go
  internal/log_analysis/log_processor/classification/classifier_test.go
  internal/log_analysis/log_processor/common/common.go
  internal/log_analysis/log_processor/processor/processor.go
  internal/log_analysis/log_processor/processor/processor_test.go
  internal/log_analysis/log_processor/sources/s3.go
  internal/log_analysis/log_processor/sources/s3_client_cache.go
  internal/log_analysis/log_processor/sources/s3_client_cache_test.go
  internal/log_analysis/log_processor/sources/sources.go
  internal/log_analysis/log_processor/sources/sqs.go
  internal/log_analysis/log_processor/sources/sqs_test.go
Labels: p0, team:data processing

#1502 fix: add dynamic width to profile popup
  web/src/components/Navigation/ProfileIcon/ProfileIcon.tsx
Labels: team:web

#1503 Fix issue with form General Setting's form initial values
  web/src/apollo/typePolicies.ts
Labels: team:web

#1515 fix: change the license to an acceptable format
  package.json
Labels: team:operations

#1519 Fix multi-region publication
  tools/mage/clients/aws.go
  tools/mage/master/publish.go
Labels: bug, mage

#1520 Re-export common field types from the pantherlog module
  internal/log_analysis/log_processor/pantherlog/pantherlog.go
Labels: team:data processing

#1506 Speed up web testing
  .circleci/config.yml
  web/__tests__/__mocks__/@reach/dialog.tsx
Labels: ci, team:web

#1512 feat: add Formik date range component
  package-lock.json
  package.json
  web/src/components/Wizard/__snapshots__/Wizard.test.tsx.snap
  web/src/components/fields/DateRangeInput/DateRangeInput.tsx
  web/src/components/fields/DateRangeInput/index.tsx
  web/src/components/fields/SensitiveTextInput/__snapshots__/SensitiveTextInput.test.tsx.snap
Labels: team:web

#1516 add name to ec2 resources
  deployments/bootstrap.yml
Labels: team:security engineering

#1537 Make get alert more efficient listing S3 files
  internal/log_analysis/alerts_api/api/get_alert.go
  internal/log_analysis/alerts_api/api/get_alert_test.go
Labels: enhancement

#1543 fix: JSON tree overflow
  web/src/components/JsonViewer/JsonViewer.tsx
Labels: bug, team:web

#1544 feat: return logTypes for alerts
  api/graphql/schema.graphql
  api/lambda/alerts/models/api.go
  api/lambda/delivery/models/api.go
  internal/log_analysis/alert_forwarder/forwarder/forwarder.go
  internal/log_analysis/alert_forwarder/forwarder/forwarder_test.go
  internal/log_analysis/alert_forwarder/forwarder/models.go
  internal/log_analysis/alerts_api/api/get_alert_test.go
  internal/log_analysis/alerts_api/api/list_alerts_test.go
  internal/log_analysis/alerts_api/utils/utils.go
  web/__generated__/schema.tsx
  web/__tests__/__mocks__/builders.generated.ts
  web/src/graphql/fragments/AlertDetailsFull.generated.ts
  web/src/graphql/fragments/AlertDetailsFull.graphql
  web/src/graphql/fragments/AlertSummaryFull.generated.ts
  web/src/graphql/fragments/AlertSummaryFull.graphql
Labels: team:operations

#1545 Improve log processor aggregation by seeing into the future
  deployments/log_analysis.yml
  deployments/master.yml
  deployments/panther_config.yml
  internal/log_analysis/log_processor/common/common.go
  internal/log_analysis/log_processor/processor/stream.go
  internal/log_analysis/log_processor/processor/stream_test.go
  tools/mage/deploy/config.go
  tools/mage/deploy/deploy.go
Labels: enhancement, team:data analytics

#1539 Add partition indexes when creating a glue table
  go.mod
  go.sum
  internal/log_analysis/awsglue/table_metadata.go
Labels: enhancement, team:data analytics

#1509 Enhance destination testing
  web/src/components/forms/AsanaDestinationForm/AsanaDestinationForm.test.tsx
  web/src/components/forms/CustomWebhookDestinationForm/CustomWebhookDestinationForm.test.tsx
  web/src/components/forms/GithubDestinationForm/GithubDestinationForm.test.tsx
  web/src/components/forms/JiraDestinationForm/JiraDestinationForm.test.tsx
  web/src/components/forms/MicrosoftTeamsDestinationForm/MicrosoftTeamsDestinationForm.test.tsx
  web/src/components/forms/OpsgenieDestinationForm/OpsGenieDestinationForm.test.tsx
  web/src/components/forms/PagerdutyDestinationForm/PagerdutyDestinationForm.test.tsx
  web/src/components/forms/SlackDestinationForm/SlackDestinationForm.test.tsx
  web/src/components/forms/SnsDestinationForm/SnsDestinationForm.test.tsx
  web/src/components/forms/SqsDestinationForm/SqsDestinationForm.test.tsx
  web/src/components/wizards/CreateDestinationWizard/ConfigureDestinationPanel/ConfigureDestinationPanel.tsx
  web/src/pages/CreateDestination/CreateDestination.test.tsx
  web/src/pages/EditDestination/EditDestination.test.tsx
  web/src/pages/ListDestinations/DestinationCards/__tests__/AsanaDestinationCard.test.tsx
  web/src/pages/ListDestinations/DestinationCards/__tests__/CustomWebhookDestinationCard.test.tsx
  web/src/pages/ListDestinations/DestinationCards/__tests__/GithubDestinationCard.test.tsx
  web/src/pages/ListDestinations/DestinationCards/__tests__/JiraDestinationCard.test.tsx
  web/src/pages/ListDestinations/DestinationCards/__tests__/MsTeamsDestinationCard.test.tsx
  web/src/pages/ListDestinations/DestinationCards/__tests__/OpsGenieDestinationCard.test.tsx
  web/src/pages/ListDestinations/DestinationCards/__tests__/PagerDutyDestinationCard.test.tsx
  web/src/pages/ListDestinations/DestinationCards/__tests__/SlackDestinationCard.test.tsx
  web/src/pages/ListDestinations/DestinationCards/__tests__/SnsDestinationCard.test.tsx
  web/src/pages/ListDestinations/DestinationCards/__tests__/SqsDestinationCard.test.tsx
Labels: team:web

#1550 Support more than 10 services per ECS cluster
  internal/compliance/snapshot_poller/pollers/aws/awstest/ecs.go
  internal/compliance/snapshot_poller/pollers/aws/ecs_cluster.go
  internal/compliance/snapshot_poller/pollers/aws/ecs_cluster_test.go
Labels: team:security engineering

#1549 Force `node-fetch` resolution to avoid vulnerabilities
  package-lock.json
  package.json
  tools/mage/setup/setup.go
Labels: security, team:web

#1552 mage master:publish: double-prompt to allow overwriting existing release
  tools/mage/master/publish.go
Labels: mage

#1531 Enhance: Limit idToken to 15 minutes
  deployments/bootstrap_gateway.yml
Labels: team:web

#1541 New Alert Card component & deprecation of Alerts Table
  web/src/components/GenericItemCard/GenericItemCard.tsx
  web/src/components/cards/AlertCard/AlertCard.test.tsx
  web/src/components/cards/AlertCard/AlertCard.tsx
  web/src/components/cards/AlertCard/index.tsx
  web/src/pages/ListAlerts/ListAlerts.tsx
  web/src/pages/ListAlerts/ListAlertsTable/ListAlertsTable.tsx
  web/src/pages/ListAlerts/ListAlertsTable/index.tsx
  web/src/pages/LogAnalysisOverview/AlertsTable/AlertsTable.tsx
  web/src/pages/LogAnalysisOverview/AlertsTable/index.tsx
  web/src/pages/LogAnalysisOverview/LogAnalysisOverview.tsx
  web/src/pages/RuleDetails/RuleDetails.tsx
  web/src/pages/RuleDetails/RuleDetailsAlertsTable/RuleDetailsAlertsTable.tsx
Labels: team:web

#1546 Feat: PR syncing between master <-> release
  .github/workflows/main.yml
Labels: sync-to-release, team:enterprise & automation, team:web

#1564 ci: force clone entire repo
  .github/workflows/main.yml
Labels: ci, sync-to-release, team:web

#1567 ci: Fix target branch of release syncs
  .github/workflows/main.yml
Labels: team:web

#1568 fix: grammatical error in docs
  README.md
Labels: enterprise-backport, sync-to-release, team:web

#1553 Added retries for Access Denied errors in Log Processor
  internal/log_analysis/log_processor/common/common.go
  internal/log_analysis/log_processor/sources/s3_client_cache.go
  pkg/awsretry/access_denied_retryer.go
  pkg/awsretry/access_denied_retryer_test.go
Labels: sync-to-release

#1533 Add proper grid alignment for rows in rule details
  web/src/pages/AlertDetails/AlertDetailsInfo/AlertDetailsInfo.tsx
  web/src/pages/PolicyDetails/PolicyDetailsInfo/PolicyDetailsInfo.tsx
  web/src/pages/RuleDetails/RuleDetailsInfo/RuleDetailsInfo.tsx
Labels: bug, team:web

#1575 Sensitive TextInput fix
  web/src/components/fields/SensitiveTextInput/SensitiveTextInput.test.tsx
  web/src/components/fields/SensitiveTextInput/SensitiveTextInput.tsx
  web/src/components/fields/SensitiveTextInput/__snapshots__/SensitiveTextInput.test.tsx.snap
  web/src/components/forms/AsanaDestinationForm/AsanaDestinationForm.test.tsx
  web/src/components/forms/AsanaDestinationForm/AsanaDestinationForm.tsx
  web/src/components/forms/CustomWebhookDestinationForm/CustomWebhookDestinationForm.tsx
  web/src/components/forms/GithubDestinationForm/GithubDestinationForm.tsx
  web/src/components/forms/JiraDestinationForm/JiraDestinationForm.tsx
  web/src/components/forms/MicrosoftTeamsDestinationForm/MicrosoftTeamsDestinationForm.tsx
  web/src/components/forms/OpsgenieDestinationForm/OpsgenieDestinationForm.tsx
  web/src/components/forms/PagerdutyDestinationForm/PagerdutyDestinationForm.tsx
  web/src/components/forms/SlackDestinationForm/SlackDestinationForm.tsx
  web/src/pages/CreateDestination/CreateDestination.test.tsx
Labels: sync-to-release, team:web

#1585 Add meta data options
  internal/compliance/snapshot_poller/models/aws/ec2_instance.go
  internal/compliance/snapshot_poller/pollers/aws/ec2_instance.go
Labels: team:security engineering

#1586 Fix edge case in role assumption
  internal/compliance/snapshot_poller/pollers/aws/awstest/assume_role.go
  internal/compliance/snapshot_poller/pollers/aws/clients.go
  internal/compliance/snapshot_poller/pollers/aws/poll_test.go
  internal/compliance/snapshot_poller/pollers/aws/utils_test.go
Labels: bug, sync-to-release, team:security engineering

#1587 Ensure master template is published with same version tag as repo
  deployments/master.yml
  tools/mage/master/publish.go
Labels: sync-to-release

#1594 Fixing minor UI issue
  web/src/pages/AlertDetails/AlertDetailsInfo/AlertDetailsInfo.tsx
Labels: sync-to-release

#1595 Backport gluesync fix to work with master stack
  cmd/opstools/gluesync/gluesync/main.go
  tools/cfnstacks/cfnstacks.go
Labels: sync-to-release, team:data analytics

#1602 Remove redundant version prefix
  tools/mage/deploy/frontend.go
  tools/mage/master/publish.go
Labels: sync-to-release

#1605 Fixing few issues with Glue Sync tool
  api/lambda/source/models/integration.go
  cmd/opstools/gluesync/gluesync/main.go
  internal/core/source_api/api/put_integration.go
Labels: sync-to-release

#1604 AnalyticsConsent for General settings
  api/graphql/schema.graphql
  api/lambda/organization/models/api.go
  internal/core/custom_resources/resources/map.go
  internal/core/organization_api/main/integration_test.go
  internal/core/organization_api/table/update.go
  web/__generated__/schema.tsx
  web/__tests__/__mocks__/builders.generated.ts
Labels: team:web

#1611 Fix warnings in FE tests
  web/src/components/forms/AsanaDestinationForm/AsanaDestinationForm.test.tsx
  web/src/components/forms/CustomWebhookDestinationForm/CustomWebhookDestinationForm.test.tsx
  web/src/components/forms/GithubDestinationForm/GithubDestinationForm.test.tsx
  web/src/components/forms/JiraDestinationForm/JiraDestinationForm.test.tsx
  web/src/components/forms/MicrosoftTeamsDestinationForm/MicrosoftTeamsDestinationForm.test.tsx
  web/src/components/forms/OpsgenieDestinationForm/OpsGenieDestinationForm.test.tsx
  web/src/components/forms/PagerdutyDestinationForm/PagerdutyDestinationForm.test.tsx
  web/src/components/forms/SlackDestinationForm/SlackDestinationForm.test.tsx
  web/src/components/forms/SnsDestinationForm/SnsDestinationForm.test.tsx
  web/src/components/forms/SqsDestinationForm/SqsDestinationForm.test.tsx
  web/src/components/wizards/CreateDestinationWizard/ConfigureDestinationPanel/ConfigureDestinationPanel.tsx
Labels: team:web

#1612 Refactor: Abstract common code under `BorderedTab`
  web/src/components/BorderedTab/BorderedTab.test.tsx
  web/src/components/BorderedTab/BorderedTab.tsx
  web/src/components/BorderedTab/__snapshots__/BorderedTab.test.tsx.snap
  web/src/components/modals/ProfileSettingsModal/ProfileSettingsModal.tsx
  web/src/pages/AlertDetails/AlertDetails.tsx
  web/src/pages/LogAnalysisOverview/LogTypeCharts/LogTypeCharts.tsx
  web/src/pages/LogAnalysisOverview/Skeleton/Skeleton.tsx
Labels: team:web

#1573 Telemetry implementation [1/2]
  package-lock.json
  package.json
  web/.eslintrc.js
  web/scripts/serve.js
  web/src/components/modals/DeleteUserModal/DeleteUserModal.tsx
  web/src/components/utils/AuthContext/AuthContext.tsx
  web/src/components/wizards/CreateDestinationWizard/ChooseDestinationPanel/ChooseDestinationPanel.tsx
  web/src/components/wizards/CreateDestinationWizard/ConfigureDestinationPanel/ConfigureDestinationPanel.tsx
  web/src/constants.ts
  web/src/helpers/analytics.ts
  web/src/hooks/useTrackPageView.tsx
  web/src/pages/ComplianceOverview/ComplianceOverview.tsx
  web/src/pages/CreateRule/CreateRule.tsx
  web/src/pages/Landing/Landing.tsx
  web/src/pages/ListAlerts/ListAlerts.tsx
  web/src/pages/ListLogSources/ListLogSources.tsx
  web/src/pages/ListRules/ListRules.tsx
  web/src/pages/LogAnalysisOverview/LogAnalysisOverview.tsx
Labels: team:web

#1619 Refactor: simplify React code on Alerts page
  web/src/pages/AlertDetails/AlertDetails.tsx
  web/src/pages/AlertDetails/AlertDetailsBanner/AlertDetailsBanner.test.tsx
  web/src/pages/AlertDetails/AlertDetailsBanner/AlertDetailsBanner.tsx
  web/src/pages/AlertDetails/AlertDetailsBanner/__snapshots__/AlertDetailsBanner.test.tsx.snap
Labels: team:web
