Repository panther-labs/panther, pull requests merged in 2020-08, with the labels that each got.

#1271 Declarative log parser definition
  cmd/devtools/pantherlog/pantherlog.go
  go.sum
  internal/log_analysis/awsglue/quirks.go
  internal/log_analysis/awsglue/schema.go
  internal/log_analysis/gluetables/gluetables_test.go
  internal/log_analysis/log_processor/classification/classifier_test.go
  internal/log_analysis/log_processor/common/json.go
  internal/log_analysis/log_processor/destinations/s3.go
  internal/log_analysis/log_processor/destinations/s3_test.go
  internal/log_analysis/log_processor/logtypes/registry.go
  internal/log_analysis/log_processor/logtypes/registry_test.go
  internal/log_analysis/log_processor/pantherlog/jsoniter.go
  internal/log_analysis/log_processor/pantherlog/jsoniter_test.go
  internal/log_analysis/log_processor/pantherlog/meta.go
  internal/log_analysis/log_processor/pantherlog/meta_test.go
  internal/log_analysis/log_processor/pantherlog/nocopy.go
  internal/log_analysis/log_processor/pantherlog/result.go
  internal/log_analysis/log_processor/pantherlog/result_test.go
  internal/log_analysis/log_processor/pantherlog/rowid/rowid.go
  internal/log_analysis/log_processor/pantherlog/rowid/rowid_test.go
  internal/log_analysis/log_processor/pantherlog/scanners.go
  internal/log_analysis/log_processor/pantherlog/scanners_test.go
  internal/log_analysis/log_processor/pantherlog/tcodec/extension.go
  internal/log_analysis/log_processor/pantherlog/tcodec/extension_test.go
  internal/log_analysis/log_processor/pantherlog/tcodec/tcodec.go
  internal/log_analysis/log_processor/pantherlog/values.go
  internal/log_analysis/log_processor/pantherlog/values_test.go
  internal/log_analysis/log_processor/parsers/awslogs/extractor_test.go
  internal/log_analysis/log_processor/parsers/awslogs/testdata/s3_server_access_samples.log
  internal/log_analysis/log_processor/parsers/factory.go
  internal/log_analysis/log_processor/parsers/pantherlog.go
  internal/log_analysis/log_processor/parsers/parsers.go
  internal/log_analysis/log_processor/parsers/testutil/testutil.go
  internal/log_analysis/log_processor/processor/processor_test.go
  pkg/box/box.go
Labels: backend team, enhancement, logs, p1

#1290 Refactor cfn stacks and utilities out of mage
  pkg/README.md
  pkg/awscfn/awscfn.go
  tools/cfnstacks/cfnstacks.go
  tools/mage/deploy.go
  tools/mage/deploy_frontend.go
  tools/mage/deploy_template.go
  tools/mage/glue_namespace.go
  tools/mage/master_namespace.go
  tools/mage/swagger.go
  tools/mage/teardown.go
  tools/mage/test_namespace.go
  tools/mage/util_cfn.go
Labels: deployment

#1292 Begin CI doc enforcement
  docs/gitbook/.gitbook/assets/operations/hosted-zone-alias.png
  docs/gitbook/README.md
  docs/gitbook/SUMMARY.md
  docs/gitbook/analysis/panther-analysis-tool.md
  docs/gitbook/cloud-security/policies/README.md
  docs/gitbook/log-analysis/README.md
  docs/gitbook/log-analysis/log-processing/supported-logs/AWS.md
  docs/gitbook/log-analysis/log-processing/supported-logs/Apache.md
  docs/gitbook/log-analysis/log-processing/supported-logs/Fluentd.md
  docs/gitbook/log-analysis/log-processing/supported-logs/GitLab.md
  docs/gitbook/log-analysis/log-processing/supported-logs/Juniper.md
  docs/gitbook/log-analysis/log-processing/supported-logs/Lacework.md
  docs/gitbook/log-analysis/log-processing/supported-logs/Nginx.md
  docs/gitbook/log-analysis/log-processing/supported-logs/OSSEC.md
  docs/gitbook/log-analysis/log-processing/supported-logs/Osquery.md
  docs/gitbook/log-analysis/log-processing/supported-logs/README.md
  docs/gitbook/log-analysis/log-processing/supported-logs/Suricata.md
  docs/gitbook/log-analysis/log-processing/supported-logs/Syslog.md
  docs/gitbook/log-analysis/log-processing/supported-logs/Zeek.md
  docs/gitbook/log-analysis/rules/README.md
  docs/gitbook/operations/configuring-custom-domains.md
  docs/gitbook/operations/runbooks.md
  docs/gitbook/quick-start.md
  docs/gitbook/tutorials/osquery-log-analysis.md
  docs/gitbook/tutorials/s3-monitoring-fundamentals.md
  tools/mage/doc.go
  tools/mage/doc_test.go
  tools/mage/test_namespace.go
Labels: documentation, testing

#1291 Add section to ops docs to show how to assess ingest volume
  docs/gitbook/.gitbook/assets/operations/cloudwatch-dashboards-log-analysis-input-select-time.png
  docs/gitbook/.gitbook/assets/operations/cloudwatch-dashboards-log-analysis-input-select.png
  docs/gitbook/.gitbook/assets/operations/cloudwatch-dashboards-log-analysis-input-show.png
  docs/gitbook/.gitbook/assets/operations/cloudwatch-dashboards-log-analysis.png
  docs/gitbook/.gitbook/assets/operations/cloudwatch-dashboards.png
  docs/gitbook/operations/ops-home.md
Labels: documentation

#1295 Fix bug when no permissions where specified for the SQS queue
  api/graphql/schema.graphql
  api/lambda/source/models/integration.go
  internal/core/source_api/api/put_integration.go
  internal/core/source_api/api/put_integration_test.go
  internal/core/source_api/api/sqs_utils.go
  internal/core/source_api/api/update_integration.go
  internal/core/source_api/api/utils.go
  internal/core/source_api/ddb/items.go
  pkg/awssqs/permissions.go
  web/__generated__/schema.tsx
  web/__tests__/__mocks__/builders.generated.ts
  web/src/components/wizards/SqsSourceWizard/SqsSourceConfigurationPanel/SqsSourceConfigurationPanel.tsx
  web/src/components/wizards/SqsSourceWizard/SqsSourceWizard.tsx
  web/src/graphql/fragments/SqsLogSourceIntegrationDetails.generated.ts
  web/src/graphql/fragments/SqsLogSourceIntegrationDetails.graphql
  web/src/pages/CreateLogSource/CreateSqsLogSource/CreateSqsLogSource.tsx
  web/src/pages/CreateLogSource/CreateSqsLogSource/__tests__/CreateSqsLogSource.test.tsx
  web/src/pages/EditSqsLogSource/EditSqsLogSource.tsx
Labels: bug

#1296 Fixing/reordering SaaS log documentation
  docs/gitbook/.gitbook/assets/enterprise/saas-logs/eventbridge.png
  docs/gitbook/SUMMARY.md
  docs/gitbook/enterprise/README.md
  docs/gitbook/enterprise/saas-logs/box.md
  docs/gitbook/enterprise/saas-logs/gsuite.md
  docs/gitbook/enterprise/saas-logs/okta.md
  docs/gitbook/enterprise/saas-logs/onelogin.md
  docs/gitbook/enterprise/saas-logs/saas-logs.md
  docs/gitbook/log-analysis/log-processing/supported-logs/Box.md
  docs/gitbook/log-analysis/log-processing/supported-logs/CiscoUmbrella.md
  docs/gitbook/log-analysis/log-processing/supported-logs/GCP.md
  docs/gitbook/log-analysis/log-processing/supported-logs/GSuite.md
  docs/gitbook/log-analysis/log-processing/supported-logs/Okta.md
  docs/gitbook/log-analysis/log-processing/supported-logs/OneLogin.md
Labels: documentation

#1299 Make opstools interactive
  cmd/opstools/requeue/requeue/main.go
  cmd/opstools/s3queue/s3queue/main.go
Labels: operations

#1298 gluesync opstool
  cmd/devtools/pantherlog/pantherlog/main.go
  cmd/opstools/gluesync/gluesync/main.go
  docs/gitbook/operations/ops-home.md
  tools/mage/build_namespace.go
  tools/mage/deploy.go
  tools/mage/glue_namespace.go
  tools/mage/util.go
Labels: operations

#1303 Simplify pantherlog Result handling and schema generation
  internal/log_analysis/log_processor/classification/classifier_test.go
  internal/log_analysis/log_processor/pantherlog/jsoniter.go
  internal/log_analysis/log_processor/pantherlog/jsoniter_test.go
  internal/log_analysis/log_processor/pantherlog/meta.go
  internal/log_analysis/log_processor/pantherlog/meta_test.go
  internal/log_analysis/log_processor/pantherlog/result.go
  internal/log_analysis/log_processor/pantherlog/result_test.go
  internal/log_analysis/log_processor/pantherlog/scanners.go
  internal/log_analysis/log_processor/pantherlog/values.go
  internal/log_analysis/log_processor/parsers/factory.go
  internal/log_analysis/log_processor/parsers/pantherlog.go
  internal/log_analysis/log_processor/parsers/testutil/testutil.go
Labels: backend team, logs

#1308 Improve flag default behavior for requeue
  cmd/opstools/gluesync/gluesync/main.go
  cmd/opstools/requeue/requeue.go
  cmd/opstools/requeue/requeue/main.go
  cmd/opstools/s3queue/integration_test.go
  cmd/opstools/s3queue/s3queue.go
  cmd/opstools/s3queue/s3queue/main.go
  cmd/opstools/s3queue/s3queue_test.go
  docs/gitbook/operations/ops-home.md
Labels: operations

#1311 Update ops doc with notes on how to configure PagerDuty
  docs/gitbook/operations/ops-home.md
Labels: documentation

#1302 Validate links to images and other documentation files
  docs/gitbook/SUMMARY.md
  docs/gitbook/development.md
  docs/gitbook/enterprise/saas-logs/saas-logs.md
  tools/mage/doc.go
  tools/mage/doc_parse.go
  tools/mage/doc_parse_test.go
  tools/mage/test_namespace.go
  tools/mage/testdata/docs/.gitbook/assets/logo.png
  tools/mage/testdata/docs/development.md
  tools/mage/testdata/docs/invalid.md
  tools/mage/testdata/docs/quick-start.md
  tools/mage/util.go
  tools/mage/util_hash.go
Labels: documentation, testing

#1310 Add actions near Breadcrumbs
  web/__tests__/example.test.tsx
  web/src/components/Breadcrumbs/Breadcrumbs.test.tsx
  web/src/components/Breadcrumbs/Breadcrumbs.tsx
  web/src/components/Header/Header.tsx
  web/src/components/Navigation/Navigation.tsx
  web/src/components/Navigation/SecondaryNavigations/ComplianceNavigation.tsx
  web/src/components/Navigation/SecondaryNavigations/LogAnalysisNavigation.tsx
  web/src/components/Navigation/SecondaryNavigations/SettingsNavigation.tsx
  web/src/pages/ListAlerts/ListAlertsActions/ListAlertsActions.tsx
  web/src/pages/ListPolicies/ListPoliciesActions/ListPoliciesActions.tsx
  web/src/pages/ListResources/ListResourcesActions/ListResourcesActions.tsx
  web/src/pages/ListRules/ListRulesActions/ListRulesActions.tsx
Labels: frontend, p1

#1319 Refine alarm descriptions
  internal/core/custom_resources/resources/alarms.go
  internal/core/custom_resources/resources/clients.go
Labels: operations

#1314 PantherUser custom resource only allows creation
  internal/core/custom_resources/resources/map.go
  internal/core/custom_resources/resources/panther_user.go
Labels: deployment

#1329 [CI]: Re-introduce PR syncing
  .github/workflows/main.yml
  .github/workflows/main.yml.disabled
  build/actions/pr_sync/action.yml
  build/actions/pr_sync/dist/index.js
  build/actions/pr_sync/index.js
Labels: ci

#1307 Adds parsers for Teleport.AuditLog
  cmd/devtools/pantherlog/pantherlog/main.go
  internal/log_analysis/awsglue/quirks.go
  internal/log_analysis/log_processor/logtypes/logtypes.go
  internal/log_analysis/log_processor/logtypes/registry.go
  internal/log_analysis/log_processor/pantherlog/meta.go
  internal/log_analysis/log_processor/pantherlog/result.go
  internal/log_analysis/log_processor/pantherlog/scanners.go
  internal/log_analysis/log_processor/parsers/gravitationallogs/audit.go
  internal/log_analysis/log_processor/parsers/gravitationallogs/audit_test.go
  internal/log_analysis/log_processor/parsers/gravitationallogs/testdata/telelport_audit_samples.jsonl
  internal/log_analysis/log_processor/parsers/testutil/testutil.go
  internal/log_analysis/log_processor/registry/registry.go
  web/src/constants.ts
Labels: logs

#1333 Fix Sync automation milestone issue
  build/actions/pr_sync/dist/index.js
  build/actions/pr_sync/index.js
Labels: ci

#1324 fix source status bug
  internal/core/source_api/api/check_integration.go
Labels: backend team, bug, cloud security

#1337 Fix wrong dir for tools in fmt_license.go, update tools
  cmd/devtools/logprocessor/logprocessor/main.go
  cmd/opstools/gluesync/gluesync/main.go
  cmd/opstools/requeue/integration_test.go
  cmd/opstools/requeue/requeue.go
  cmd/opstools/requeue/requeue/main.go
  cmd/opstools/s3queue/integration_test.go
  cmd/opstools/s3queue/s3queue.go
  cmd/opstools/s3queue/s3queue/main.go
  cmd/opstools/s3queue/s3queue_test.go
  cmd/opstools/testutils/testutils.go
  tools/mage/fmt_license.go
Labels: bug

#1325 Log processor latency metric
  internal/core/metrics_api/api/get_metrics.go
  internal/core/metrics_api/api/log_processor_metrics.go
  internal/log_analysis/log_processor/classification/classifier.go
  internal/log_analysis/log_processor/classification/classifier_test.go
  internal/log_analysis/log_processor/common/metrics.go
  internal/log_analysis/log_processor/processor/processor.go
  internal/log_analysis/log_processor/processor/processor_test.go
  pkg/metrics/logger.go
Labels: backend team, log analysis

#1335 Enhance Log Overview charts
  package-lock.json
  package.json
  web/src/components/charts/TimeSeriesChart/TimeSeriesChart.tsx
  web/src/components/charts/TimeSeriesChart/colors.ts
  web/src/components/forms/BaseRuleForm/BaseRuleFormCoreSection/BaseRuleFormCoreSection.tsx
  web/src/helpers/utils.tsx
  web/src/pages/CreateLogSource/CreateSqsLogSource/CreateSqsLogSource.test.tsx
  web/src/pages/LogAnalysisOverview/AlertsBySeverity/AlertsBySeverity.tsx
  web/src/pages/LogAnalysisOverview/EventsByLogType/EventsByLogType.tsx
  web/src/pages/LogAnalysisOverview/LogAnalysisOverview.test.tsx
  web/src/pages/LogAnalysisOverview/LogAnalysisOverview.tsx
  web/src/pages/RuleDetails/RuleDetailsInfo/RuleDetailsInfo.tsx
Labels: enhancement, frontend

#1320 Fix documentation links in web app
  web/src/components/Navigation/Navigation.tsx
  web/src/components/forms/AnalyticsConsentForm/ErrorReportingSection.tsx
  web/src/components/forms/PolicyForm/PolicyFormAutoRemediationSection/PolicyFormAutoRemediationSection.tsx
  web/src/components/sidesheets/PolicyBulkUploadSidesheet/PolicyBulkUploadSidesheet.tsx
  web/src/components/wizards/ComplianceSourceWizard/SourceConfigurationPanel/SourceConfigurationPanel.tsx
  web/src/constants.ts
  web/src/pages/Landing/Landing.tsx
Labels: documentation

#1338 Fix bug with log processor destination S3 object key
  cmd/devtools/logprocessor/logprocessor/main.go
  internal/log_analysis/log_processor/destinations/s3.go
  internal/log_analysis/log_processor/destinations/s3_test.go
  internal/log_analysis/log_processor/processor/stream.go
Labels: bug, p0

#1345 [deployments] improved clarity on CF stack descriptions
  deployments/auxiliary/cloudformation/panther-cloudwatch-events.yml
  deployments/auxiliary/cloudformation/panther-log-processing-notifications.yml
Labels: deployment

#1349 Add support for session.network events in Gravitational.TeleportAudit
  internal/log_analysis/log_processor/pantherlog/scanners.go
  internal/log_analysis/log_processor/parsers/gravitationallogs/audit.go
  internal/log_analysis/log_processor/parsers/gravitationallogs/audit_test.go
Labels: logs, p0

#1342 Standardize `tcodec` behavior when no struct tags are set on the field
  cmd/devtools/pantherlog/pantherlog/main.go
  internal/log_analysis/awsglue/quirks.go
  internal/log_analysis/log_processor/common/json.go
  internal/log_analysis/log_processor/pantherlog/jsoniter.go
  internal/log_analysis/log_processor/pantherlog/result_test.go
  internal/log_analysis/log_processor/pantherlog/tcodec/extension.go
  internal/log_analysis/log_processor/pantherlog/tcodec/extension_test.go
  internal/log_analysis/log_processor/pantherlog/tcodec/registry.go
  internal/log_analysis/log_processor/pantherlog/tcodec/tcodec.go
  internal/log_analysis/log_processor/pantherlog/tcodec/tcodec_test.go
  internal/log_analysis/log_processor/parsers/testutil/testutil.go
Labels: logs

#1353 Backport pantherlog fixes from EE
  internal/log_analysis/log_processor/logtypes/registry.go
  internal/log_analysis/log_processor/pantherlog/jsoniter.go
  internal/log_analysis/log_processor/pantherlog/jsoniter_test.go
  internal/log_analysis/log_processor/parsers/gravitationallogs/audit_test.go
Labels: bug, enterprise-backport, p1

#1351 Verify master stack in CI
  tools/cfnparse/parse.go
  tools/mage/build_namespace.go
  tools/mage/doc.go
  tools/mage/fmt.go
  tools/mage/fmt_license.go
  tools/mage/master_namespace.go
  tools/mage/swagger.go
  tools/mage/swagger_test.go
  tools/mage/test_cfn.go
  tools/mage/test_ci.go
  tools/mage/test_go.go
  tools/mage/test_integration.go
  tools/mage/test_namespace.go
  tools/mage/test_python.go
  tools/mage/test_web.go
  tools/mage/util.go
  tools/mage/util_hash.go
Labels: testing

#1363 Don't run go tests in isolation in CI
  tools/mage/test_ci.go
Labels: testing

#1365 Wizard UI & Accessibility Enhancements
  web/src/components/Wizard/WizardPanelWrapper.tsx
  web/src/components/Wizard/__snapshots__/Wizard.test.tsx.snap
  web/src/components/wizards/ComplianceSourceWizard/StackDeploymentPanel/StackDeployment.tsx
  web/src/components/wizards/ComplianceSourceWizard/SuccessPanel/SuccessPanel.tsx
  web/src/components/wizards/S3LogSourceWizard/StackDeploymentPanel/StackDeployment.tsx
  web/src/components/wizards/S3LogSourceWizard/SuccessPanel/SuccessPanel.tsx
  web/src/components/wizards/SqsSourceWizard/InformationPanel/InformationPanel.tsx
  web/src/components/wizards/SqsSourceWizard/SuccessPanel/SuccessPanel.tsx
  web/src/pages/CreateDestination/CreateDestination.tsx
  web/src/pages/EditDestination/EditDestination.tsx
Labels: enterprise-backport, frontend

#1373 Minimize allocations in AWS.CloudTrail parser
  internal/log_analysis/log_processor/parsers/awslogs/cloudtrail.go
Labels: backend team

#1347 fix: show only open/triaged alerts by default
  web/src/components/Navigation/SecondaryNavigations/LogAnalysisNavigation.tsx
  web/src/pages/Landing/Landing.tsx
Labels: frontend

#1377 Add missing EC2 delete permissions for deployment role
  deployments/auxiliary/cloudformation/panther-deployment-role.yml
  deployments/auxiliary/terraform/panther_deployment_role/main.tf
Labels: deployment

#1389 Fix start date flag for gluesync
  cmd/opstools/gluesync/gluesync/main.go
Labels: bug

#1418 Fix awsretry to initialize with NumMaxRetries
  internal/compliance/snapshot_poller/pollers/aws/clients.go
  internal/log_analysis/log_processor/common/common.go
  pkg/awsretry/connection_retryer.go
  pkg/awsretry/connection_retryer_test.go
Labels: bug

#1425 Adds AWS indicator fields
  internal/log_analysis/log_processor/pantherlog/meta.go
  internal/log_analysis/log_processor/pantherlog/scanners.go
  internal/log_analysis/log_processor/parsers/awslogs/indicators.go
Labels: backend team

#1372 CI: Add mage_fmt job
  .circleci/config.yml
Labels: ci

#1431 Migrate to latest pounce
  package-lock.json
  package.json
  web/src/components/BorderedTab/BorderedTab.tsx
  web/src/components/Navigation/NavLink/NavLink.tsx
  web/src/components/Wizard/__snapshots__/Wizard.test.tsx.snap
  web/src/pages/ListAlerts/ListAlertsTable/ListAlertsTable.tsx
  web/src/pages/LogAnalysisOverview/AlertsTable/AlertsTable.tsx
  web/src/pages/LogSourceOnboarding/LogSourceCard/LogSourceCard.tsx
Labels: frontend

#1435 Add custom app client token expiration
  deployments/bootstrap_gateway.yml
  go.mod
  go.sum
  internal/core/custom_resources/resources/cognito_client_token_expiration.go
  internal/core/custom_resources/resources/map.go
  internal/log_analysis/awsglue/table_metadata_test.go
Labels: security-feature

#1437 Update mage test:cfn with check for S3 bucket ForceSSL statement IDs
  deployments/bootstrap.yml
  tools/mage/test_cfn.go
Labels: mage, team:enterprise & automation

#1427 LogTypes API ListAvailableLogTypes
  api/graphql/schema.graphql
  deployments/appsync.yml
  deployments/core.yml
  go.mod
  go.sum
  internal/core/logtypesapi/api.go
  internal/core/logtypesapi/api_test.go
  internal/core/logtypesapi/available.go
  internal/core/logtypesapi/available_test.go
  internal/core/logtypesapi/client/lambdaclient_gen.go
  internal/core/logtypesapi/dynamodb.go
  internal/core/logtypesapi/main/lambda.go
  internal/log_analysis/log_processor/common/oplog.go
  pkg/lambdalogger/lambdalogger.go
  pkg/lambdalogger/logger.go
  pkg/x/apigen/apigen.go
  pkg/x/apigen/internal/methods.go
  pkg/x/apigen/internal/models.go
  pkg/x/apigen/internal/models_test.go
  pkg/x/apigen/lambdaclient/lambdaclient.go
  pkg/x/apigen/templates.go
  pkg/x/lambdamux/batch.go
  pkg/x/lambdamux/batch_test.go
  pkg/x/lambdamux/demux.go
  pkg/x/lambdamux/demux_test.go
  pkg/x/lambdamux/lambadmux.go
  pkg/x/lambdamux/middleware.go
  pkg/x/lambdamux/mux.go
  pkg/x/lambdamux/mux_test.go
  pkg/x/lambdamux/route.go
  pkg/x/lambdamux/route_test.go
  tools/mage/build_namespace.go
  web/__generated__/schema.tsx
  web/__tests__/__mocks__/builders.generated.ts
Labels: backend team, p1

#1406 fix: Navigation should highlight alerts page
  web/src/components/Navigation/NavLink/NavLink.test.tsx
  web/src/components/Navigation/NavLink/NavLink.tsx
  web/src/helpers/utils.tsx
Labels: bug
