Repository panther-labs/panther, pull requests merged in 2020-01, with the labels that each got.

#57 [docs] email documentation and light rewording on destinations
  docs/gitbook/.gitbook/assets/default-destinations.png
  docs/gitbook/destinations/alert-setup/README.md
  docs/gitbook/destinations/alert-setup/email.md
  docs/gitbook/destinations/alert-setup/jira.md
  docs/gitbook/destinations/alert-setup/pagerduty.md
  docs/gitbook/destinations/alert-setup/sns.md
  docs/gitbook/destinations/background.md
Labels: documentation

#58 Update quick-start and development docs
  docs/gitbook/.gitbook/assets/docker-status.png
  docs/gitbook/.gitbook/assets/self-signed-cert-warning.png
  docs/gitbook/README.md
  docs/gitbook/development.md
  docs/gitbook/quick-start.md
Labels: documentation

#65 [gitbook] add supported-logs to summary index
  docs/gitbook/SUMMARY.md
Labels: documentation

#62 Adding Nginx Access logs parser
  internal/log_analysis/log_processor/parsers/awslogs/alb.go
  internal/log_analysis/log_processor/parsers/awslogs/aurora_mysql_audit.go
  internal/log_analysis/log_processor/parsers/awslogs/s3_server_access.go
  internal/log_analysis/log_processor/parsers/awslogs/vpc_flow.go
  internal/log_analysis/log_processor/parsers/csv_utils.go
  internal/log_analysis/log_processor/parsers/nginx/access.go
  internal/log_analysis/log_processor/parsers/nginx/access_test.go
  internal/log_analysis/log_processor/registry/registry.go
  web/src/constants.ts
Labels: logs

#78 Additional JIRA Destination Configuration
  api/lambda/outputs/models/api.go
  internal/core/alert_delivery/outputs/jira.go
  internal/core/alert_delivery/outputs/jira_test.go
Labels: enhancement

#72 Updated documentation to include Nginx logs
  docs/gitbook/log-analysis/supported-logs/README.md
  internal/log_analysis/log_processor/parsers/nginxlogs/access.go
  internal/log_analysis/log_processor/parsers/nginxlogs/access_test.go
  internal/log_analysis/log_processor/registry/registry.go
Labels: documentation, logs

#87 [ENG-1469] Real-time source deletion
  web/src/client.ts
  web/src/pages/list-sources/subcomponents/infra-source-table.tsx
  web/src/pages/list-sources/subcomponents/log-source-table.tsx
Labels: bug

#86 [Feature] Add Asana Destination
  api/graphql/schema.graphql
  web/__generated__/schema.tsx
  web/src/assets/asana-minimal-logo.svg
  web/src/assets/aws-logo.svg
  web/src/assets/aws-sns-minimal-logo.svg
  web/src/assets/aws-sns.svg
  web/src/assets/aws-sqs-minimal-logo.svg
  web/src/assets/aws-sqs.svg
  web/src/components/destination-card.tsx
  web/src/components/forms/destination-form/asana-destination-form.tsx
  web/src/components/forms/destination-form/index.tsx
  web/src/components/sidesheets/add-destination-sidesheet.tsx
  web/src/components/sidesheets/select-destination-sidesheet.tsx
  web/src/components/sidesheets/update-destination-sidesheet.tsx
  web/src/helpers/utils.tsx
  web/src/pages/destinations/index.tsx
Labels: enhancement

#69 Add IAM fallback for ACM certificate import
  tools/mage/deploy_certificate.go
Labels: bug, deployment

#85 [Docs] Update web docs
  web/README.md
Labels: documentation

#61 Support AWS Partition deployment within Cloudformation.
  deployments/auxiliary/cloudformation/panther-cloudwatch-events.yml
  deployments/auxiliary/cloudformation/panther-compliance-iam.yml
  deployments/auxiliary/cloudformation/panther-log-processing-iam.yml
  deployments/auxiliary/cloudformation/panther-log-processing-infra.yml
  deployments/auxiliary/cloudformation/panther-log-processing-notifications.yml
  deployments/auxiliary/cloudformation/panther-remediations-iam.yml
  deployments/auxiliary/cloudformation/panther-stackset-iam-admin-role.yml
  deployments/backend.yml
  dev.sh
Labels: deployment
