Repository panther-labs/panther, pull requests merged in 2020-10, with the labels that each got.

#1618 feat: CI check for code vulnerabilities
  .github/workflows/code-analysis.yml
Labels: team:web

#1629 Fix: color of Policy & Rule"test" handles
  web/src/components/forms/BaseRuleForm/BaseRuleFormTestSection/BaseRuleFormTestSection.tsx
Labels: bug, sync-to-release, team:web

#1649 Add support for strftime and unix microseconds/nanoseconds to tcodec
  go.mod
  go.sum
  internal/log_analysis/log_processor/pantherlog/tcodec/extension.go
  internal/log_analysis/log_processor/pantherlog/tcodec/extension_test.go
  internal/log_analysis/log_processor/pantherlog/tcodec/registry.go
  internal/log_analysis/log_processor/pantherlog/tcodec/tcodec.go
  internal/log_analysis/log_processor/pantherlog/tcodec/tcodec_test.go
  internal/log_analysis/log_processor/pantherlog/tcodec/unix.go
Labels: team:data processing

#1652 Support versioned release branches in release sync
  .github/workflows/main.yml
Labels: team:core infra

#1655 Bump version in master stack
  deployments/master.yml
Labels: sync-to-release

#1657 Sync automation: fix release branch base
  .github/workflows/main.yml
Labels: sync-to-release

#1658 Release sync automation: Strip origin prefix from branch name
  .github/workflows/main.yml
Labels: sync-to-release

#1659 Small comment change to trigger release sync again
  .golangci.yml
Labels: sync-to-release

#1430 Multiple scanners in panther tags and use separate event_time tag
  internal/log_analysis/log_processor/destinations/s3.go
  internal/log_analysis/log_processor/destinations/s3_test.go
  internal/log_analysis/log_processor/pantherlog/jsoniter.go
  internal/log_analysis/log_processor/pantherlog/jsoniter_test.go
  internal/log_analysis/log_processor/pantherlog/meta.go
  internal/log_analysis/log_processor/pantherlog/result_test.go
  internal/log_analysis/log_processor/pantherlog/scanners.go
  internal/log_analysis/log_processor/parsers/cloudflarelogs/firewall.go
  internal/log_analysis/log_processor/parsers/cloudflarelogs/http_request.go
  internal/log_analysis/log_processor/parsers/cloudflarelogs/spectrum.go
  internal/log_analysis/log_processor/parsers/gravitationallogs/audit.go
Labels: p2

#1662 fix: c/p typo in analytics
  web/src/pages/ListLogSources/ListLogSources.tsx
Labels: sync-to-release, team:web

#1666 Add s3 access log bucket for data processing buckets to break feedback loop
  deployments/bootstrap.yml
Labels: sync-to-release, team:data analytics

#1672 Fix: Bundlesize CI check
  web/.env.analytics
  web/.env.telemetry
  web/scripts/build.js
  web/src/apollo/createErrorLink.ts
  web/src/components/ErrorBoundary/ErrorBoundary.tsx
  web/src/helpers/analytics.ts
  web/src/helpers/errors.ts
  web/src/pages/ComplianceOverview/PoliciesBySeverityChart/PoliciesBySeverityChart.tsx
Labels: enhancement, team:web

#1675 Bugfix: remove duplicate logType from GraphQL schema
  api/graphql/schema.graphql
Labels: bug

#1671 Describe Large Number of Tasks
  internal/compliance/snapshot_poller/pollers/aws/awstest/ecs.go
  internal/compliance/snapshot_poller/pollers/aws/ecs_cluster.go
  internal/compliance/snapshot_poller/pollers/aws/ecs_cluster_test.go
Labels: bug, sync-to-release, team:security engineering

#1674 handle case where sns subject is over 100 characters
  internal/core/alert_delivery/outputs/sns.go
  internal/core/alert_delivery/outputs/sns_test.go
  pkg/testutils/awsmocks.go
Labels: bug, sync-to-release

#1696 Removed data from trackError for analytics
  web/src/components/utils/AuthContext/AuthContext.tsx
  web/src/components/wizards/CreateDestinationWizard/ConfigureDestinationPanel/ConfigureDestinationPanel.tsx
  web/src/helpers/analytics.ts
  web/src/pages/CreateRule/CreateRule.tsx
Labels: sync-to-release, team:web

#1693 CI: Use authenticated docker pulls
  .circleci/config.yml
Labels: sync-to-release, team:core infra, testing

#1694 fix: alert delivery status calculation
  web/src/pages/AlertDetails/AlertDetailsInfo/AlertDeliverySection/AlertDeliverySection.test.tsx
  web/src/pages/AlertDetails/AlertDetailsInfo/AlertDeliverySection/AlertDeliverySection.tsx
  web/src/pages/AlertDetails/AlertDetailsInfo/AlertDeliverySection/AlertDeliveryTable/AlertDeliveryTable.test.tsx
  web/src/pages/AlertDetails/AlertDetailsInfo/AlertDeliverySection/AlertDeliveryTable/AlertDeliveryTable.tsx
Labels: sync-to-release

#1704 Sequential mage setup and update dev image version
  dev.sh
  tools/mage/setup/setup.go
Labels: sync-to-release, team:core infra

#1707 Fixing redirect of successful SQS onboarding
  web/src/components/wizards/SqsSourceWizard/ValidationPanel/ValidationPanel.tsx
Labels: bug, sync-to-release

#1706 Support custom VPCs
  deployments/bootstrap.yml
  deployments/master.yml
  deployments/panther_config.yml
  tools/mage/deploy/config.go
  tools/mage/deploy/deploy.go
Labels: deployment, security-feature, sync-to-release

#1713 Fix VPC input check
  deployments/bootstrap.yml
Labels: bug, sync-to-release

#1717 Avoid errors during self-onboarding
  internal/core/custom_resources/resources/self_registration.go
Labels: bug, sync-to-release

#1720 Add version to all tracking events
  web/src/helpers/analytics.ts
Labels: sync-to-release, team:web

#1695 Tests for tracking utils
  package-lock.json
  package.json
  web/__tests__/.env.test
  web/__tests__/env.ts
  web/__tests__/setup.ts
  web/__tests__/utils/index.ts
  web/src/helpers/__tests__/analytics.test.tsx
  web/src/helpers/__tests__/erros.test.tsx
  web/src/helpers/analytics.ts
  web/src/hooks/__tests__/useTrackPageView.test.tsx
Labels: team:web

#1723 Add panther version check to opstools gluesync and gluerecover
  cmd/opstools/gluerecover/gluerecover/main.go
  cmd/opstools/gluesync/gluesync/main.go
  cmd/opstools/opstools.go
Labels: sync-to-release

#1730 Added warning in case we fail to delete SQS messages
  pkg/awsbatch/sqsbatch/delete_message_batch.go
Labels: bug, sync-to-release

#1735 fix: use semver package to compare versions
  tools/mage/deploy/deploy.go
  tools/mage/master/deploy.go
  tools/mage/master/publish.go
Labels: sync-to-release

#1737 fix: version bump for templates
  deployments/master.yml
Labels: sync-to-release

#1751 Fix gluesync and gluerecover prefix match
  internal/log_analysis/gluetasks/recover.go
  internal/log_analysis/gluetasks/sync.go
Labels: bug, sync-to-release

#1759 Add dependency to UpdateTables resource
  deployments/log_analysis.yml
Labels: bug, sync-to-release

#1757 fix: Alert Delivery text
  web/src/pages/AlertDetails/AlertDetailsInfo/AlertDeliverySection/AlertDeliverySection.test.tsx
  web/src/pages/AlertDetails/AlertDetailsInfo/AlertDeliverySection/AlertDeliverySection.tsx
Labels: team:web

#1764 Aggelos fix overview tables
  web/src/pages/ComplianceOverview/TopFailingPoliciesTable/TopFailingPoliciesTable.tsx
  web/src/pages/ComplianceOverview/TopFailingResourcesTable/TopFailingResourcesTable.tsx
Labels: bug, p2, team:web

#1758 Backport required changes for implementing custom logs.
  api/lambda/logtypes/models_gen.go
  cmd/devtools/logprocessor/logprocessor/main.go
  internal/core/custom_resources/resources/glue.go
  internal/core/logtypesapi/lambdaclient_gen.go
  internal/log_analysis/alerts_api/api/get_alert.go
  internal/log_analysis/athenaviews/athenaviews.go
  internal/log_analysis/datacatalog_updater/process/create_tables.go
  internal/log_analysis/datacatalog_updater/process/create_tables_test.go
  internal/log_analysis/datacatalog_updater/process/process.go
  internal/log_analysis/datacatalog_updater/process/process_test.go
  internal/log_analysis/datacatalog_updater/process/setup.go
  internal/log_analysis/gluetables/gluetables.go
  internal/log_analysis/log_processor/destinations/s3.go
  internal/log_analysis/log_processor/destinations/s3_test.go
  internal/log_analysis/log_processor/logtypes/logtesting/logtesting.go
  internal/log_analysis/log_processor/logtypes/logtypes.go
  internal/log_analysis/log_processor/logtypes/registry.go
  internal/log_analysis/log_processor/logtypes/resolver.go
  internal/log_analysis/log_processor/main/lambda.go
  internal/log_analysis/log_processor/pantherlog/null/null.go
  internal/log_analysis/log_processor/pantherlog/null/null_test.go
  internal/log_analysis/log_processor/parsers/cloudflarelogs/cloudflarelogs_test.go
  internal/log_analysis/log_processor/processor/processor.go
  internal/log_analysis/log_processor/processor/processor_test.go
  internal/log_analysis/log_processor/processor/stream.go
  internal/log_analysis/log_processor/processor/stream_test.go
  internal/log_analysis/log_processor/registry/registry.go
  internal/log_analysis/log_processor/sources/sources.go
  internal/log_analysis/log_processor/sources/sqs.go
  internal/log_analysis/log_processor/sources/sqs_test.go
  pkg/testutils/awsmocks.go
  pkg/x/apigen/apigen.go
  pkg/x/apigen/internal/models.go
  pkg/x/apigen/templates.go
  pkg/x/lambdamux/mux.go
Labels: p0, sync-to-release

#1765 [Sync] 1.10.1 Bug fixes
  deployments/log_analysis.yml
  internal/log_analysis/gluetasks/recover.go
  internal/log_analysis/gluetasks/sync.go
Labels: bug

#1774 Minor UX Improvements
  web/.eslintrc.js
  web/src/components/charts/TimeSeriesChart/TimeSeriesChart.tsx
  web/src/pages/ComplianceOverview/PoliciesBySeverityChart/PoliciesBySeverityChart.tsx
  web/src/pages/ComplianceOverview/PoliciesByStatusChart/PoliciesByStatusChart.tsx
  web/src/pages/ComplianceOverview/ResourcesByStatusChart/ResourcesByStatusChart.tsx
  web/src/pages/CreatePolicy/CreatePolicy.tsx
  web/src/pages/CreateRule/CreateRule.tsx
  web/src/pages/EditPolicy/EditPolicy.tsx
  web/src/pages/EditRule/EditRule.tsx
  web/src/pages/LogAnalysisOverview/LogAnalysisOverview.test.tsx
  web/src/pages/LogAnalysisOverview/LogAnalysisOverview.tsx
  web/src/pages/LogAnalysisOverview/graphql/getOverviewAlerts.generated.ts
  web/src/pages/LogAnalysisOverview/graphql/getOverviewAlerts.graphql
Labels: sync-to-release, team:web

#1785 Create shared VERSION file
  VERSION
  deployments/auxiliary/cloudformation/Makefile
  deployments/auxiliary/cloudformation/README.md
  deployments/auxiliary/cloudformation/panther-cloudsec-iam.yml
  deployments/auxiliary/cloudformation/panther-cloudwatch-events.yml
  deployments/auxiliary/cloudformation/panther-deployment-role.yml
  deployments/auxiliary/cloudformation/panther-log-analysis-iam.yml
  deployments/auxiliary/cloudformation/panther-log-processing-notifications.yml
  deployments/auxiliary/cloudformation/panther-stackset-iam-admin-role.yml
  deployments/master.yml
  internal/core/source_api/api/testdata/panther-cloudsec-iam-updated.yml
  internal/core/source_api/api/testdata/panther-log-analysis-iam-updated.yml
  tools/mage/deploy/deploy.go
  tools/mage/deploy/deploy_template.go
  tools/mage/master/build.go
  tools/mage/master/deploy.go
  tools/mage/master/publish.go
  tools/mage/test/cfn.go
  tools/mage/util/version.go
Labels: sync-to-release, team:core infra

#1782 [CircleCI] Fail without commit in Autofmt and inform users when a PR is from a fork
  .circleci/config.yml
Labels: ci

#1787 Rename erros.test.tsx to errors.test.tsx
  web/src/helpers/__tests__/errors.test.tsx
Labels: team:web

#1770 Parser for Sophos Central logs
  internal/log_analysis/log_processor/parsers/sophoslogs/central.go
  internal/log_analysis/log_processor/parsers/sophoslogs/central_test.go
  internal/log_analysis/log_processor/parsers/sophoslogs/sophos.go
  internal/log_analysis/log_processor/parsers/sophoslogs/testdata/central_tests.yml
  internal/log_analysis/log_processor/registry/registry.go
Labels: sync-to-release, team:data processing

#1784 Handle scanning large resources better
  internal/compliance/resources_api/handlers/add_resources.go
  internal/compliance/snapshot_poller/models/aws/ec2_vpc.go
  internal/compliance/snapshot_poller/pollers/aws/ec2_vpc.go
  pkg/awsbatch/dynamodbbatch/item_size.go
  pkg/awsbatch/dynamodbbatch/item_size_test.go
  requirements.txt
Labels: bug, sync-to-release, team:security engineering

#1800 Onboarding Logs validation fix
  web/src/components/wizards/SqsSourceWizard/SqsSourceConfigurationPanel/SqsSourceConfigurationPanel.tsx
  web/src/components/wizards/SqsSourceWizard/ValidationPanel/ValidationPanel.tsx
  web/src/pages/CreateLogSource/CreateSqsLogSource/CreateSqsLogSource.test.tsx
  web/src/pages/EditSqsLogSource/ΕditSqsLogSource.test.tsx
Labels: bug, sync-to-release, team:web

#1803 Updating threshold for analysis API
  deployments/bootstrap_gateway.yml
Labels: bug, sync-to-release

#1808 fix: split lines in contributors table
  README.md
Labels: documentation

#1795 Allow individual Lambda deploys
  tools/mage/build/lambda.go
  tools/mage/deploy/deploy.go
Labels: mage, team:core infra

#1811 Bugfix for custom-resources lambda
  tools/mage/deploy/deploy.go
Labels: bug, enterprise-backport, mage, team:core infra

#1807 Fixing threshold for Log Processor input queue
  deployments/log_analysis.yml
  internal/core/custom_resources/resources/alarms_sqs.go
Labels: bug, sync-to-release

#1820 Slight increase in source-api retries
  internal/core/source_api/api/list_integrations.go
  internal/core/source_api/api/vars.go
  internal/core/source_api/ddb/ddb.go
Labels: sync-to-release

#1819 Ignore "S3 folder" objects
  internal/log_analysis/log_processor/sources/s3.go
  internal/log_analysis/log_processor/sources/s3_test.go
Labels: bug, sync-to-release

#1822 Fixing issue when retrieving events for an alert
  internal/log_analysis/alerts_api/api/get_alert.go
Labels: bug, sync-to-release

#1835 fix rule threshold in summary
  api/README.md
  api/gateway/analysis/api.yml
  api/gateway/analysis/models/policy_summary.go
  api/gateway/analysis/models/rule_summary.go
  api/graphql/schema.graphql
  internal/core/analysis_api/handlers/dynamo.go
  internal/core/analysis_api/handlers/list.go
  internal/core/analysis_api/main/integration_test.go
  web/__generated__/schema.tsx
  web/src/components/cards/RuleCard/RuleCard.tsx
  web/src/components/forms/BaseRuleForm/BaseRuleFormCoreSection/BaseRuleFormCoreSection.tsx
  web/src/components/forms/RuleForm/RuleForm.tsx
  web/src/pages/ListRules/EmptyDataFallback/EmptyDataFallback.tsx
Labels: bug, sync-to-release

#1840 VPC Scanning bug fix
  internal/compliance/snapshot_poller/pollers/aws/ec2_vpc.go
  internal/compliance/snapshot_poller/pollers/aws/ec2_vpc_test.go
Labels: bug, cloud security, sync-to-release, team:security engineering

#1825 Increase retries when reading CloudTrail objects from S3
  internal/compliance/aws_event_processor/processor/accounts.go
  internal/compliance/aws_event_processor/processor/handler.go
  internal/compliance/aws_event_processor/processor/handler_test.go
Labels: sync-to-release

#1802 Removed error from metrics API
  api/lambda/metrics/models/api.go
  internal/core/metrics_api/api/get_metrics.go
Labels: bug, sync-to-release

#1841 Use rev-parse to get branch name
  tools/mage/util/version.go
Labels: mage, sync-to-release, team:core infra

#1849 Change doc branch name
  web/src/constants.ts
  web/src/pages/GeneralSettings/__snapshots__/GeneralSettings.test.tsx.snap
Labels: sync-to-release

#1851 Updating evaluation periods for SQS queue threshold
  internal/core/custom_resources/resources/alarms_sqs.go
Labels: bug, sync-to-release

#1792 Add maxbuffer limit check to log processor
  internal/log_analysis/log_processor/destinations/s3.go
  internal/log_analysis/log_processor/destinations/s3_test.go
Labels: enhancement, team:data analytics

#1854 Feat: use pounce's `Popover` for filters
  package-lock.json
  package.json
  web/src/components/Navigation/ProfileIcon/ProfileIcon.test.tsx
  web/src/components/Navigation/ProfileIcon/ProfileIcon.tsx
  web/src/pages/ListAlerts/ListAlertFilters/DropdownFilters.tsx
  web/src/pages/ListRules/ListRulesFilters/DropdownFilters.tsx
Labels: enhancement, sync-to-release, team:web

#1858 Make auto remediations more consistent
  internal/compliance/alert_processor/processor/processor.go
Labels: bug, cloud security, sync-to-release, team:security engineering

#1870 Update use of custom retriers to only be used on clients (fixes `mage test:integration`)
  internal/compliance/snapshot_poller/pollers/aws/clients.go
  internal/log_analysis/datacatalog_updater/process/setup.go
  internal/log_analysis/log_processor/common/common.go
  internal/log_analysis/log_processor/sources/s3_client_cache.go
Labels: team:data analytics

#1860 Update default settings
  deployments/master.yml
  deployments/panther_config.yml
Labels: deployment, sync-to-release

#1864 Remove global vars in alerts_api (sync from enterprise)
  api/lambda/alerts/models/api.go
  internal/core/alert_delivery/api/deliver_alert.go
  internal/core/alert_delivery/api/deliver_alert_test.go
  internal/core/alert_delivery/api/update_delivery_test.go
  internal/log_analysis/alerts_api/api/api.go
  internal/log_analysis/alerts_api/api/get_alert.go
  internal/log_analysis/alerts_api/api/get_alert_test.go
  internal/log_analysis/alerts_api/api/list_alerts.go
  internal/log_analysis/alerts_api/api/list_alerts_test.go
  internal/log_analysis/alerts_api/api/update_alert_delivery.go
  internal/log_analysis/alerts_api/api/update_alert_delivery_test.go
  internal/log_analysis/alerts_api/api/update_alert_status.go
  internal/log_analysis/alerts_api/api/update_alert_status_test.go
  internal/log_analysis/alerts_api/main/lambda.go
  internal/log_analysis/alerts_api/main/lambda_test.go
  internal/log_analysis/alerts_api/table/get_alert.go
  internal/log_analysis/alerts_api/table/get_alert_test.go
  internal/log_analysis/alerts_api/table/table.go
  internal/log_analysis/alerts_api/utils/utils.go
Labels: enterprise-backport, team:data analytics

#1872 Fix config issues with recent refactor of alerts_api
  deployments/log_analysis.yml
  internal/log_analysis/alerts_api/api/api.go
Labels: enterprise-backport

#1868 Filtering: bugfixes & UX enhancements
  api/graphql/schema.graphql
  deployments/appsync.yml
  web/__generated__/schema.tsx
  web/__tests__/__mocks__/builders.generated.ts
  web/src/pages/ListAlerts/ListAlertBreadcrumbFilters/ListAlertBreadcrumbFilters.tsx
  web/src/pages/ListAlerts/ListAlertFilters/DropdownFilters.tsx
  web/src/pages/ListAlerts/ListAlertFilters/ListAlertFilters.tsx
  web/src/pages/ListRules/ListRules.tsx
  web/src/pages/ListRules/ListRulesBreadcrumbFilters/ListRulesBreadcrumbFilters.tsx
  web/src/pages/ListRules/ListRulesFilters/DropdownFilters.tsx
  web/src/pages/ListRules/ListRulesFilters/ListRulesFilters.tsx
  web/src/pages/LogAnalysisOverview/LogAnalysisOverview.test.tsx
  web/src/pages/LogAnalysisOverview/LogAnalysisOverview.tsx
  web/src/pages/LogAnalysisOverview/LogAnalysisOverviewBreadcrumbFilters/LogAnalysisOverviewBreadcrumbFilters.tsx
Labels: bug, sync-to-release, team:web

#1873 fix: update options passed on listeners
  web/src/components/charts/TimeSeriesChart/TimeSeriesChart.tsx
Labels: bug, sync-to-release, team:web

#1881 feat: update to stable version
  VERSION
Labels: sync-to-release

#1878 Add cloudsecurity database and tables to Glue
  deployments/bootstrap_gateway.yml
  deployments/cloud_security.yml
  deployments/log_analysis.yml
  internal/compliance/awsglue/awsglue.go
  internal/core/custom_resources/resources/athena.go
  internal/core/custom_resources/resources/cloud_security_tables.go
  internal/core/custom_resources/resources/log_processor_tables.go
  internal/core/custom_resources/resources/map.go
Labels: team:data analytics

#1883 Pass workgroup to create athena views
  deployments/bootstrap_gateway.yml
  deployments/log_analysis.yml
  deployments/master.yml
  internal/core/custom_resources/resources/log_processor_tables.go
  internal/log_analysis/athenaviews/athenaviews.go
  internal/log_analysis/datacatalog_updater/process/create_tables.go
  internal/log_analysis/datacatalog_updater/process/integration_test.go
  internal/log_analysis/datacatalog_updater/process/setup.go
  pkg/awsathena/integration_test.go
  pkg/awsathena/query.go
  pkg/awsathena/workgroup.go
  tools/mage/deploy/deploy.go
Labels: enterprise-backport, team:data analytics

#1891 Revert the change to the log processor glue customer resource id
  internal/core/custom_resources/resources/log_processor_tables.go
  internal/core/custom_resources/resources/map.go
Labels: enterprise-backport

#1896 Rename log processor custom resource
  deployments/log_analysis.yml
  internal/core/custom_resources/resources/log_processor_tables.go
  internal/core/custom_resources/resources/map.go
Labels: enterprise-backport

#1857 Improve Log Processor Aggregation
  deployments/log_analysis.yml
  deployments/master.yml
  deployments/panther_config.yml
  internal/log_analysis/log_processor/common/common.go
  internal/log_analysis/log_processor/main/lambda.go
  internal/log_analysis/log_processor/main/lambda_test.go
  internal/log_analysis/log_processor/processor/rescale.go
  internal/log_analysis/log_processor/processor/stream.go
  internal/log_analysis/log_processor/processor/stream_test.go
  tools/mage/deploy/config.go
  tools/mage/deploy/deploy.go
Labels: enhancement, team:data analytics

#1874 Destination Success hook + adding indication to Alert Card
  web/__tests__/jest.config.js
  web/src/components/RelatedDestinations/RelatedDestinations.tsx
  web/src/components/cards/AlertCard/AlertCard.test.tsx
  web/src/components/cards/AlertCard/AlertCard.tsx
  web/src/components/cards/AlertCard/__snapshots__/AlertCard.test.tsx.snap
  web/src/hooks/useAlertDestinationsDeliverySuccess.tsx
  web/src/pages/AlertDetails/AlertDetailsInfo/AlertDeliverySection/AlertDeliverySection.test.tsx
  web/src/pages/AlertDetails/AlertDetailsInfo/AlertDeliverySection/AlertDeliverySection.tsx
  web/src/pages/AlertDetails/AlertDetailsInfo/AlertDetailsInfo.tsx
  web/src/pages/RuleDetails/RuleDetails.tsx
Labels: team:web

#1904 Minor Athena/Glue Tidies
  internal/compliance/awsglue/awsglue.go
  internal/core/custom_resources/resources/cloud_security_tables.go
  internal/core/custom_resources/resources/log_processor_tables.go
  internal/log_analysis/athenaviews/athenaviews.go
  pkg/awsathena/integration_test.go
  pkg/awsathena/query.go
Labels: enterprise-backport

#1886 Added option to send test Alerts from List Destinations page
  web/src/components/wizards/common/DestinationTestPanel/DestinationTestPanel.tsx
  web/src/graphql/queries/index.tsx
  web/src/graphql/queries/sendTestAlert.generated.ts
  web/src/graphql/queries/sendTestAlert.graphql
  web/src/pages/ListDestinations/DestinationCards/DestinationCardOptions.tsx
  web/src/pages/ListDestinations/DestinationCards/__tests__/DestinationCard.test.tsx
  web/src/pages/ListDestinations/DestinationCards/__tests__/__snapshots__/DestinationCard.test.tsx.snap
Labels: team:web

#1910 Restore url-decoding for getResource
  internal/compliance/resources_api/handlers/get_resource.go
Labels: bug, enterprise-backport, team:core infra
