Repository panther-labs/panther, pull requests merged in 2020-02, with the labels that each got.

#95 Fix issue with persistent compliance filters
  web/src/components/utils/table-compliance-filter-control.tsx
  web/src/pages/policy-details/index.tsx
  web/src/pages/resource-details/index.tsx
Labels: bug

#91 Document panther standard fields and example Athena queries
  docs/gitbook/.gitbook/assets/PantherStandardFieldRule.png
  docs/gitbook/SUMMARY.md
  docs/gitbook/historical-search/README.md
  docs/gitbook/historical-search/example-queries.md
  docs/gitbook/historical-search/panther-fields.md
  docs/gitbook/log-analysis/log-processing/README.md
Labels: documentation

#88 Std fields
  internal/log_analysis/log_processor/parsers/awslogs/alb.go
  internal/log_analysis/log_processor/parsers/awslogs/alb_test.go
  internal/log_analysis/log_processor/parsers/awslogs/aurora_mysql_audit.go
  internal/log_analysis/log_processor/parsers/awslogs/aurora_mysql_audit_test.go
  internal/log_analysis/log_processor/parsers/awslogs/cloudtrail.go
  internal/log_analysis/log_processor/parsers/awslogs/cloudtrail_test.go
  internal/log_analysis/log_processor/parsers/awslogs/extractor.go
  internal/log_analysis/log_processor/parsers/awslogs/extractor_test.go
  internal/log_analysis/log_processor/parsers/awslogs/guardduty.go
  internal/log_analysis/log_processor/parsers/awslogs/guardduty_test.go
  internal/log_analysis/log_processor/parsers/awslogs/pantherlog.go
  internal/log_analysis/log_processor/parsers/awslogs/pantherlog_test.go
  internal/log_analysis/log_processor/parsers/awslogs/s3_server_access.go
  internal/log_analysis/log_processor/parsers/awslogs/s3_server_access_test.go
  internal/log_analysis/log_processor/parsers/awslogs/utils_test.go
  internal/log_analysis/log_processor/parsers/awslogs/vpc_flow.go
  internal/log_analysis/log_processor/parsers/awslogs/vpc_flow_test.go
  internal/log_analysis/log_processor/parsers/nginxlogs/access.go
  internal/log_analysis/log_processor/parsers/nginxlogs/access_test.go
  internal/log_analysis/log_processor/parsers/osquerylogs/batch.go
  internal/log_analysis/log_processor/parsers/osquerylogs/batch_test.go
  internal/log_analysis/log_processor/parsers/osquerylogs/differential.go
  internal/log_analysis/log_processor/parsers/osquerylogs/differential_test.go
  internal/log_analysis/log_processor/parsers/osquerylogs/snapshot.go
  internal/log_analysis/log_processor/parsers/osquerylogs/snapshot_test.go
  internal/log_analysis/log_processor/parsers/osquerylogs/status.go
  internal/log_analysis/log_processor/parsers/osquerylogs/status_test.go
  internal/log_analysis/log_processor/parsers/pantherlog_test.go
  internal/log_analysis/log_processor/parsers/patherlog.go
  pkg/extract/extractor.go
  pkg/extract/extractor_test.go
  tools/athenaviews/athenaviews.go
  tools/athenaviews/athenaviews_test.go
Labels: enhancement

#132 Document parser fields
  internal/log_analysis/log_processor/parsers/awslogs/alb.go
  internal/log_analysis/log_processor/parsers/awslogs/aurora_mysql_audit.go
  internal/log_analysis/log_processor/parsers/awslogs/cloudtrail.go
  internal/log_analysis/log_processor/parsers/awslogs/guardduty.go
  internal/log_analysis/log_processor/parsers/awslogs/guardduty_test.go
  internal/log_analysis/log_processor/parsers/awslogs/s3_server_access.go
  internal/log_analysis/log_processor/parsers/awslogs/vpc_flow.go
  internal/log_analysis/log_processor/parsers/nginxlogs/access.go
  internal/log_analysis/log_processor/parsers/osquerylogs/batch.go
  internal/log_analysis/log_processor/parsers/osquerylogs/differential.go
  internal/log_analysis/log_processor/parsers/osquerylogs/snapshot.go
  internal/log_analysis/log_processor/parsers/osquerylogs/status.go
  tools/athenaviews/athenaviews_test.go
  tools/cfngen/gluecf/gluecf_test.go
  tools/cfngen/gluecf/schema.go
  tools/cfngen/gluecf/schema_test.go
  tools/cfngen/gluecf/testdata/gluecf.json.cf
Labels: documentation

#133 Add text around example queries to give better context
  docs/gitbook/.gitbook/assets/AthenaTablesWithColumnDescriptions.png
  docs/gitbook/.gitbook/assets/screen-shot-2020-01-22-at-2.15.29-pm.png
  docs/gitbook/historical-search/README.md
  docs/gitbook/historical-search/example-queries.md
Labels: documentation

#147 [README] Logo update, CLA, and more
  README.md
  docs/CONTRIBUTING.md
  docs/img/logo-banner.png
  docs/img/panther-logo-github.jpg
Labels: ci

#139 Support Custom VPC Flow Logs
  internal/log_analysis/log_processor/classification/classifier_test.go
  internal/log_analysis/log_processor/classification/parser_queue.go
  internal/log_analysis/log_processor/parsers/awslogs/alb.go
  internal/log_analysis/log_processor/parsers/awslogs/aurora_mysql_audit.go
  internal/log_analysis/log_processor/parsers/awslogs/cloudtrail.go
  internal/log_analysis/log_processor/parsers/awslogs/guardduty.go
  internal/log_analysis/log_processor/parsers/awslogs/s3_server_access.go
  internal/log_analysis/log_processor/parsers/awslogs/vpc_flow.go
  internal/log_analysis/log_processor/parsers/awslogs/vpc_flow_test.go
  internal/log_analysis/log_processor/parsers/nginxlogs/access.go
  internal/log_analysis/log_processor/parsers/osquerylogs/batch.go
  internal/log_analysis/log_processor/parsers/osquerylogs/differential.go
  internal/log_analysis/log_processor/parsers/osquerylogs/snapshot.go
  internal/log_analysis/log_processor/parsers/osquerylogs/status.go
  internal/log_analysis/log_processor/parsers/parsers.go
Labels: backend team, enhancement, logs

#160 Clear rules on update
  internal/log_analysis/rules_engine/src/engine.py
Labels: bug

#173 S3access validate http status if not null
  internal/log_analysis/log_processor/parsers/awslogs/s3_server_access.go
Labels: logs

#169 ECS Cluster Scanning Support
  go.mod
  go.sum
  internal/compliance/aws_event_processor/processor/classify.go
  internal/compliance/aws_event_processor/processor/ec2.go
  internal/compliance/aws_event_processor/processor/ecs.go
  internal/compliance/snapshot_poller/models/aws/ecs_cluster.go
  internal/compliance/snapshot_poller/pollers/aws/acm_certificate.go
  internal/compliance/snapshot_poller/pollers/aws/awstest/ecs.go
  internal/compliance/snapshot_poller/pollers/aws/clients.go
  internal/compliance/snapshot_poller/pollers/aws/ec2_volume.go
  internal/compliance/snapshot_poller/pollers/aws/ecs_cluster.go
  internal/compliance/snapshot_poller/pollers/aws/ecs_cluster_test.go
  internal/compliance/snapshot_poller/pollers/aws/poll.go
  internal/compliance/snapshot_poller/pollers/lambda_test.go
  internal/compliance/snapshot_poller/pollers/utils/logging.go
  web/src/constants.ts
Labels: cloud security, enhancement

#172 [Feature] Add x-ray to appsync
  deployments/backend.yml
  deployments/core/appsync.yml
  requirements.txt
Labels: enhancement

#170 [Feat] Error logging mechanism
  .github/ISSUE_TEMPLATE/epic.md
  .gitignore
  deployments/web/Dockerfile
  deployments/web/server.yml
  package-lock.json
  package.json
  tools/mage/deploy_frontend.go
  web/.env.sentry
  web/README.md
  web/scripts/build.js
  web/scripts/start.js
  web/scripts/utils.js
  web/src/helpers/loggers.ts
  web/webpack.config.js
Labels: frontend

#174 Update mage glue:sync to not require input of time range
  tools/mage/glue_namespace.go
Labels: deployment

#177 Oplog for genericapi
  internal/compliance/snapshot_api/main/handler.go
  internal/core/organization_api/main/lambda.go
  internal/core/outputs_api/main/lambda.go
  internal/core/users_api/main/lambda.go
  internal/log_analysis/alerts_api/main/lambda.go
  pkg/genericapi/router.go
  pkg/genericapi/router_test.go
  pkg/genericapi/verify_test.go
Labels: operations

#188 Fix user dropdown bug
  web/src/components/forms/user-invitation-form/index.tsx
Labels: frontend

#185 Oplog with memstats
  pkg/oplog/oplog.go
  pkg/oplog/oplog_test.go
Labels: operations

#189 Fix undefined TOTP label
  web/src/components/forms/signin-form/index.tsx
  web/src/components/utils/auth-context.tsx
Labels: frontend

#184 Add Error Reporting Prompt
  api/graphql/schema.graphql
  deployments/core/appsync.yml
  deployments/core/buckets.yml
  docs/gitbook/SUMMARY.md
  docs/gitbook/privacy/error-reporting.md
  web/__generated__/schema.tsx
  web/src/app.tsx
  web/src/client.ts
  web/src/components/forms/analytics-consent-form/error-reporting-section.tsx
  web/src/components/forms/analytics-consent-form/index.tsx
  web/src/components/forms/company-information-form/index.tsx
  web/src/components/forms/policy-form/policy-form-auto-remediation-fields.tsx
  web/src/components/modals/analytics-consent-modal.tsx
  web/src/components/utils/modal-context.tsx
  web/src/components/utils/modal-manager.tsx
  web/src/components/utils/prompt-controller.tsx
  web/src/constants.ts
  web/src/helpers/loggers.ts
  web/src/pages/create-source/subcomponents/create-infra-source/subcomponents/real-time-event-panel.tsx
  web/src/pages/create-source/subcomponents/create-infra-source/subcomponents/remediation-panel.tsx
  web/src/pages/create-source/subcomponents/create-infra-source/subcomponents/resource-scanning-panel.tsx
  web/src/pages/general-settings/index.tsx
  web/src/pages/general-settings/skeleton.tsx
  web/src/pages/general-settings/subcomponent/company-information-form.tsx
  web/src/pages/general-settings/subcomponent/company-information-panel.tsx
Labels: enhancement, frontend

#191 Deployment role and doc updates
  .gitignore
  deployments/auxiliary/README.md
  deployments/auxiliary/cloudformation/Makefile
  deployments/auxiliary/cloudformation/README.md
  deployments/auxiliary/cloudformation/panther-deployment-role.yml
  deployments/auxiliary/cloudformation/panther-log-processing-notifications.yml
  deployments/auxiliary/cloudformation/panther-stackset-iam-admin-role.yml
  deployments/auxiliary/terraform/README.md
  deployments/auxiliary/terraform/panther-deployment-role.tf
  docs/gitbook/quick-start.md
  web/src/pages/overview/index.tsx
Labels: documentation

#195 [docs] new high-level diagram, custom parser docs, cost page edits
  docs/gitbook/.gitbook/assets/glue-catalog.png
  docs/gitbook/.gitbook/assets/high-level-diagram.png
  docs/gitbook/README.md
  docs/gitbook/SUMMARY.md
  docs/gitbook/cost.md
  docs/gitbook/log-analysis/supported-logs/README.md
  docs/gitbook/log-analysis/supported-logs/writing-parsers.md
  docs/gitbook/operations/ops-home.md
Labels: documentation

#208 Remove swagger from deploy precheck
  docs/gitbook/quick-start.md
  tools/mage/build_namespace.go
  tools/mage/deploy.go
Labels: documentation, mage

#211 Updated audit role permissions
  deployments/auxiliary/cloudformation/panther-compliance-iam.yml
  go.mod
  go.sum
Labels: bug, cloud security

#186 Cloud Security CloudTrail Processing
  deployments/auxiliary/cloudformation/panther-log-processing-infra.yml
  deployments/backend.yml
  deployments/compliance/aws_event_processor.yml
  internal/compliance/aws_event_processor/processor/accounts.go
  internal/compliance/aws_event_processor/processor/classify.go
  internal/compliance/aws_event_processor/processor/classify_test.go
  internal/compliance/aws_event_processor/processor/handler.go
  internal/compliance/aws_event_processor/processor/handler_test.go
Labels: backend team, cloud security, enhancement

#223 [login page] edit text on left side of auth page
  web/src/components/auth-page-container.tsx
Labels: frontend

#241 Complete FOSSA Configuration
  .fossa.yml
Labels: ci

#251 Dashboards and alarms
  deployments/backend.yml
  deployments/core/appsync.yml
  deployments/monitoring.yml
  deployments/panther_config.yml
  deployments/web/alb.yml
  docs/gitbook/operations/ops-home.md
  tools/cfngen/cf.go
  tools/cfngen/cloudwatchcf/alarms.go
  tools/cfngen/cloudwatchcf/alarms_apigw.go
  tools/cfngen/cloudwatchcf/alarms_appsync.go
  tools/cfngen/cloudwatchcf/alarms_ddb.go
  tools/cfngen/cloudwatchcf/alarms_elb.go
  tools/cfngen/cloudwatchcf/alarms_lambda.go
  tools/cfngen/cloudwatchcf/alarms_sns.go
  tools/cfngen/cloudwatchcf/alarms_sqs.go
  tools/cfngen/cloudwatchcf/alarms_test.go
  tools/cfngen/cloudwatchcf/dashboard.go
  tools/cfngen/cloudwatchcf/dashboards_test.go
  tools/cfngen/cloudwatchcf/metrics.go
  tools/cfngen/cloudwatchcf/metrics_lambda.go
  tools/cfngen/cloudwatchcf/metrics_test.go
  tools/cfngen/cloudwatchcf/testdata/cf.yml
  tools/cfngen/cloudwatchcf/testdata/generated_test_alarms.json
  tools/cfngen/cloudwatchcf/testdata/generated_test_metrics.json
  tools/cfngen/cloudwatchcf/util.go
  tools/cfngen/cloudwatchcf/util_test.go
  tools/cfngen/cloudwatchcf/walkyaml.go
  tools/cfngen/gluecf/gluecf.go
  tools/cfngen/gluecf/testdata/db.template.json
  tools/cfngen/gluecf/testdata/tables.template.json
  tools/dashboards/alerts.go
  tools/dashboards/dashboards.go
  tools/dashboards/infra.go
  tools/dashboards/log_processing.go
  tools/dashboards/overview.go
  tools/dashboards/remediation.go
  tools/mage/cfngen.go
  tools/mage/config.go
  tools/mage/deploy.go
  tools/mage/deploy_monitoring.go
Labels: operations

#254 Add rule match Athena/Glue tables
  docs/gitbook/log-analysis/supported-logs/README.md
  internal/log_analysis/log_processor/registry/registry.go
  internal/log_analysis/rules_engine/src/output.py
  pkg/awsglue/glue.go
  pkg/awsglue/integration_test.go
  pkg/awsglue/partition_test.go
  tools/athenaviews/athenaviews.go
  tools/athenaviews/athenaviews_test.go
  tools/cfngen/gluecf/db_test.go
  tools/cfngen/gluecf/gluecf.go
  tools/cfngen/gluecf/gluecf_test.go
  tools/cfngen/gluecf/table_test.go
  tools/cfngen/gluecf/testdata/gluecf.json.cf
  tools/cfngen/gluecf/util_test.go
  tools/mage/deploy.go
  tools/mage/glue_namespace.go
Labels: log analysis

#242 AWS Event Processor doesn't process duplicate S3/CWE data
  deployments/compliance/aws_event_processor.yml
  deployments/compliance/snapshot.yml
  go.mod
  go.sum
  internal/compliance/aws_event_processor/processor/accounts.go
  internal/compliance/aws_event_processor/processor/acm.go
  internal/compliance/aws_event_processor/processor/classify.go
  internal/compliance/aws_event_processor/processor/classify_test.go
  internal/compliance/aws_event_processor/processor/cloudformation.go
  internal/compliance/aws_event_processor/processor/cloudtrail.go
  internal/compliance/aws_event_processor/processor/cloudwatch_log_group.go
  internal/compliance/aws_event_processor/processor/config.go
  internal/compliance/aws_event_processor/processor/dynamodb.go
  internal/compliance/aws_event_processor/processor/ec2.go
  internal/compliance/aws_event_processor/processor/ecs.go
  internal/compliance/aws_event_processor/processor/elbv2.go
  internal/compliance/aws_event_processor/processor/guardduty.go
  internal/compliance/aws_event_processor/processor/handler.go
  internal/compliance/aws_event_processor/processor/handler_test.go
  internal/compliance/aws_event_processor/processor/iam.go
  internal/compliance/aws_event_processor/processor/kms.go
  internal/compliance/aws_event_processor/processor/lambda.go
  internal/compliance/aws_event_processor/processor/process.go
  internal/compliance/aws_event_processor/processor/process_test.go
  internal/compliance/aws_event_processor/processor/rds.go
  internal/compliance/aws_event_processor/processor/redshift.go
  internal/compliance/aws_event_processor/processor/s3.go
  internal/compliance/aws_event_processor/processor/waf-regional.go
  internal/compliance/aws_event_processor/processor/waf.go
Labels: backend team, cloud security

#265 Update Historical Search Docs Page
  docs/gitbook/historical-search/README.md
Labels: documentation

#285 Update example-queries.md
  docs/gitbook/historical-search/example-queries.md
Labels: documentation

#290 Update ops-home.md
  docs/gitbook/operations/ops-home.md
Labels: documentation

#291 Update sqs.md
  docs/gitbook/destinations/alert-setup/sqs.md
Labels: documentation

#294 Update sns.md
  docs/gitbook/destinations/alert-setup/sns.md
Labels: documentation

#295 Update pagerduty.md
  docs/gitbook/destinations/alert-setup/pagerduty.md
Labels: documentation

#296 Update opsgenie.md
  docs/gitbook/destinations/alert-setup/opsgenie.md
Labels: documentation

#297 Update microsoft-teams.md
  docs/gitbook/destinations/alert-setup/microsoft-teams.md
Labels: documentation

#303 Policy/Alert URLs + Cloud Sec Overview Wording
  deployments/core/outputs.yml
  web/src/components/auth-page-container.tsx
  web/src/pages/compliance-overview/index.tsx
  web/src/pages/compliance-overview/skeleton.tsx
Labels: bug, frontend

#311 Replace vulnerable front-end package
  package-lock.json
  package.json
  tools/mage/test_namespace.go
  web/webpack.config.js
Labels: security

#310 Update quick-start.md
  docs/gitbook/quick-start.md
Labels: documentation

#307 Update asana.md
  docs/gitbook/destinations/alert-setup/asana.md
Labels: documentation

#306 Update github.md
  docs/gitbook/destinations/alert-setup/github.md
Labels: documentation

#305 Update jira.md
  docs/gitbook/destinations/alert-setup/jira.md
Labels: documentation

#322 Fix alarms url link
  tools/cfngen/cloudwatchcf/alarms.go
  tools/cfngen/cloudwatchcf/testdata/generated_test_alarms.json
Labels: bug
