Repository panther-labs/panther, pull requests merged in 2020-06, with the labels that each got.

#968 Use client helper to get session for custom resource analysis set
  internal/core/custom_resources/resources/analysis_set.go
Labels: bug

#969 Update snowflake documentation to be consistent with changes this release
  docs/gitbook/enterprise/snowflake.md
Labels: documentation

#965 Fix regression in glue:sync for testing existence of data in a partition
  internal/log_analysis/awsglue/glue_timebin.go
  internal/log_analysis/awsglue/table_metadata_test.go
Labels: bug

#970 Add web stack to master template
  deployments/master.yml
  deployments/onboard.yml
  deployments/web_server.yml
  go.mod
  go.sum
  internal/core/custom_resources/resources/alarms.go
  internal/core/custom_resources/resources/analysis_set.go
  internal/core/custom_resources/resources/athena.go
  internal/core/custom_resources/resources/certificate.go
  internal/core/custom_resources/resources/clients.go
  internal/core/custom_resources/resources/cognito_user_pool_mfa.go
  internal/core/custom_resources/resources/glue.go
  internal/core/custom_resources/resources/guardduty_destination.go
  internal/core/custom_resources/resources/lambda_metric_filters.go
  internal/core/custom_resources/resources/panther_settings.go
  internal/core/custom_resources/resources/panther_user.go
  internal/core/custom_resources/resources/s3_bucket_notification.go
  internal/core/custom_resources/resources/self_registration.go
  tools/mage/deploy.go
  tools/mage/deploy_frontend.go
  tools/mage/master.go
Labels: deployment

#971 Teardown supports master stack
  deployments/bootstrap.yml
  deployments/bootstrap_gateway.yml
  deployments/master.yml
  internal/core/custom_resources/resources/clients.go
  internal/core/custom_resources/resources/map.go
  internal/core/custom_resources/resources/panther_teardown.go
  tools/mage/deploy.go
  tools/mage/deploy_frontend.go
  tools/mage/migrations.go
  tools/mage/teardown.go
  tools/mage/util_cfn.go
Labels: deployment

#982 fix: removes the pip upgrade warning when running `mage setup`
  requirements-top-level.txt
  requirements.txt
Labels: dependency

#991 Add mage temp file to .gitignore
  .gitignore
Labels: mage

#992 fix: web development environment for node v12
  package-lock.json
  package.json
  web/__generated__/schema.tsx
  web/codegen.yml
  web/src/routes.tsx
Labels: dependency

#998 Add glue:CreatePartition permission
  deployments/bootstrap_gateway.yml
Labels: bug

#1002 Removing -v argument
  tools/mage/test_namespace.go
Labels: mage

#1004 Updated prettier version
  .prettierrc
  package-lock.json
  package.json
  web/src/components/forms/AsanaDestinationForm/AsanaDestinationForm.tsx
  web/src/components/forms/CompanyInformationForm/CompanyInformationForm.tsx
  web/src/components/forms/ForgotPasswordForm/ForgotPasswordForm.tsx
  web/src/components/forms/JiraDestinationForm/JiraDestination.tsx
  web/src/components/forms/MicrosoftTeamsDestinationForm/MicrosoftTeamsDestinationForm.tsx
  web/src/components/forms/PagerdutyDestinationForm/PagerdutyDestinationForm.tsx
  web/src/components/forms/RuleForm/RuleForm.tsx
  web/src/components/forms/SigninForm/SigninForm.tsx
  web/src/components/forms/SlackDestinationForm/SlackDestinationForm.tsx
  web/src/components/forms/SqsDestinationForm/SqsDestinationForm.tsx
  web/src/components/wizards/S3LogSourceWizard/S3LogSourceWizard.tsx
Labels: mage

#1000 Updating build commands
  tools/mage/build_namespace.go
  tools/mage/test_namespace.go
Labels: mage

#1022 Add Zeek.DNS to ui log type list
  web/src/constants.ts
Labels: bug

#1027 Support single-stack updates in mage
  docs/gitbook/development.md
  docs/gitbook/quick-start.md
  tools/cfnparse/parse.go
  tools/mage/deploy.go
  tools/mage/deploy_frontend.go
  tools/mage/deploy_template.go
  tools/mage/glue_namespace.go
  tools/mage/master_namespace.go
  tools/mage/migrations.go
  tools/mage/swagger.go
  tools/mage/swagger_test.go
  tools/mage/teardown.go
  tools/mage/test_namespace.go
  tools/mage/util.go
  tools/mage/util_cfn.go
Labels: deployment, documentation

#1040 Standardize CFN parameters
  deployments/appsync.yml
  deployments/bootstrap.yml
  deployments/bootstrap_gateway.yml
  deployments/cloud_security.yml
  deployments/core.yml
  deployments/log_analysis.yml
  deployments/master.yml
  deployments/onboard.yml
  deployments/panther_config.yml
  deployments/web_server.yml
  tools/config/config.go
  tools/mage/deploy.go
  tools/mage/deploy_frontend.go
  tools/mage/test_namespace.go
Labels: deployment

#1041 Fix outputs-api integration tests
  deployments/cloud_security.yml
  deployments/core.yml
  deployments/master.yml
  internal/core/outputs_api/main/integration_test.go
  tools/mage/deploy.go
  tools/mage/test_namespace.go
Labels: bug

#1043 Secrets manager permissions
  deployments/cloud_security.yml
  deployments/log_analysis.yml
Labels: enhancement

#1051 Add CustomResourceVersion
  deployments/appsync.yml
  deployments/bootstrap_gateway.yml
  deployments/cloud_security.yml
  deployments/core.yml
  deployments/log_analysis.yml
  deployments/master.yml
  deployments/onboard.yml
  deployments/web_server.yml
  docs/gitbook/development.md
  tools/mage/deploy.go
  tools/mage/deploy_frontend.go
  tools/mage/master_namespace.go
Labels: deployment

#1047 Standardizing the fields sent for PagerDuty/Sns/Sqs
  internal/compliance/alert_forwarder/forwarder/forwarder.go
  internal/compliance/alert_forwarder/forwarder/forwarder_test.go
  internal/compliance/alert_processor/processor/processor.go
  internal/compliance/alert_processor/processor/processor_test.go
  internal/core/alert_delivery/delivery/dispatch.go
  internal/core/alert_delivery/delivery/dispatch_test.go
  internal/core/alert_delivery/delivery/handle.go
  internal/core/alert_delivery/delivery/handle_test.go
  internal/core/alert_delivery/delivery/outputs.go
  internal/core/alert_delivery/models/api.go
  internal/core/alert_delivery/outputs/asana_test.go
  internal/core/alert_delivery/outputs/custom_webhook.go
  internal/core/alert_delivery/outputs/custom_webhook_test.go
  internal/core/alert_delivery/outputs/github.go
  internal/core/alert_delivery/outputs/github_test.go
  internal/core/alert_delivery/outputs/jira.go
  internal/core/alert_delivery/outputs/jira_test.go
  internal/core/alert_delivery/outputs/msteams.go
  internal/core/alert_delivery/outputs/msteams_test.go
  internal/core/alert_delivery/outputs/opsgenie.go
  internal/core/alert_delivery/outputs/opsgenie_test.go
  internal/core/alert_delivery/outputs/outputs.go
  internal/core/alert_delivery/outputs/outputs_test.go
  internal/core/alert_delivery/outputs/pagerduty.go
  internal/core/alert_delivery/outputs/pagerduty_test.go
  internal/core/alert_delivery/outputs/slack.go
  internal/core/alert_delivery/outputs/slack_test.go
  internal/core/alert_delivery/outputs/sns.go
  internal/core/alert_delivery/outputs/sns_test.go
  internal/core/alert_delivery/outputs/sqs.go
  internal/core/alert_delivery/outputs/sqs_test.go
  internal/log_analysis/alert_forwarder/forwarder/forwarder.go
  internal/log_analysis/alert_forwarder/forwarder/forwarder_test.go
  pkg/testutils/awsmocks.go
Labels: alerting

#1065 Bug fixing/improvements in log processor
  internal/log_analysis/log_processor/parsers/awslogs/alb.go
  internal/log_analysis/log_processor/parsers/awslogs/s3_server_access.go
  internal/log_analysis/log_processor/parsers/awslogs/vpc_flow.go
  internal/log_analysis/log_processor/parsers/csv_utils.go
  internal/log_analysis/log_processor/sources/errors.go
  internal/log_analysis/log_processor/sources/s3.go
  internal/log_analysis/log_processor/sources/s3_test.go
Labels: bug

#1061 Fix python lambda metric filter expressions
  internal/core/custom_resources/resources/lambda_metric_filters.go
Labels: bug

#1058 Migration: remove deleted alarm
  internal/core/custom_resources/resources/alarms_elb.go
Labels: bug

#1069 Fixed error handling case
  internal/compliance/snapshot_poller/pollers/aws/iam_user.go
Labels: bug

#1070 Updated docs
  docs/gitbook/SUMMARY.md
  docs/gitbook/log-analysis/log-processing/supported-logs/CiscoUmbrella.md
  docs/gitbook/log-analysis/log-processing/supported-logs/GSuite.md
Labels: documentation

#1072 Move VPC flow logs to bootstrap stack
  deployments/bootstrap.yml
  deployments/master.yml
  deployments/onboard.yml
  tools/mage/deploy.go
Labels: security

#1080 Add firehose permissions to deployment role
  deployments/auxiliary/cloudformation/panther-deployment-role.yml
  deployments/auxiliary/terraform/panther_deployment_role/main.tf
Labels: bug, deployment

#1081 Support updates to Custom::GuardDutyDestination resource
  deployments/bootstrap_gateway.yml
  internal/core/custom_resources/resources/guardduty_destination.go
Labels: bug, deployment

#1079 Updating API to remove pointers
  api/lambda/source/models/api.go
  api/lambda/source/models/integration.go
  api/lambda/source/models/validator_test.go
  internal/compliance/aws_event_processor/processor/accounts.go
  internal/compliance/aws_event_processor/processor/accounts_test.go
  internal/compliance/aws_event_processor/processor/process.go
  internal/compliance/snapshot_scheduler/scheduler/schedule.go
  internal/compliance/snapshot_scheduler/scheduler/schedule_test.go
  internal/core/custom_resources/resources/self_registration.go
  internal/core/source_api/api/check_integration.go
  internal/core/source_api/api/delete_integration.go
  internal/core/source_api/api/delete_integration_test.go
  internal/core/source_api/api/get_integration_template.go
  internal/core/source_api/api/get_integration_template_test.go
  internal/core/source_api/api/glue_utils.go
  internal/core/source_api/api/list_integrations_test.go
  internal/core/source_api/api/put_integration.go
  internal/core/source_api/api/put_integration_test.go
  internal/core/source_api/api/update_integration.go
  internal/core/source_api/api/update_integration_test.go
  internal/core/source_api/api/update_status.go
  internal/core/source_api/api/utils.go
  internal/core/source_api/ddb/delete_item.go
  internal/core/source_api/ddb/get_item.go
  internal/core/source_api/ddb/items.go
  internal/core/source_api/ddb/put_item.go
  internal/core/source_api/ddb/scan.go
  internal/core/source_api/ddb/update.go
  internal/core/source_api/main/integration_test.go
  internal/log_analysis/log_processor/sources/s3_client_cache.go
  internal/log_analysis/log_processor/sources/s3_client_cache_test.go
  internal/log_analysis/log_processor/sources/s3_test.go
  tools/mage/glue_namespace.go
Labels: backend team

#1091 Move supported source check earlier
  internal/compliance/aws_event_processor/processor/process.go
  internal/compliance/aws_event_processor/processor/process_test.go
Labels: cloud security

#1083 Fix Events pagination bug
  web/src/pages/AlertDetails/AlertDetailsEvents/AlertDetailsEvents.tsx
Labels: frontend
