Repository panther-labs/panther, pull requests merged in 2020-03, with the labels that each got.

#304 Add PantherParseTime to the Parser
  docs/gitbook/historical-search/panther-fields.md
  internal/log_analysis/log_processor/parsers/awslogs/alb.go
  internal/log_analysis/log_processor/parsers/awslogs/alb_test.go
  internal/log_analysis/log_processor/parsers/awslogs/aurora_mysql_audit.go
  internal/log_analysis/log_processor/parsers/awslogs/aurora_mysql_audit_test.go
  internal/log_analysis/log_processor/parsers/awslogs/cloudtrail.go
  internal/log_analysis/log_processor/parsers/awslogs/cloudtrail_test.go
  internal/log_analysis/log_processor/parsers/awslogs/guardduty.go
  internal/log_analysis/log_processor/parsers/awslogs/guardduty_test.go
  internal/log_analysis/log_processor/parsers/awslogs/s3_server_access.go
  internal/log_analysis/log_processor/parsers/awslogs/s3_server_access_test.go
  internal/log_analysis/log_processor/parsers/awslogs/vpc_flow.go
  internal/log_analysis/log_processor/parsers/awslogs/vpc_flow_test.go
  internal/log_analysis/log_processor/parsers/nginxlogs/access.go
  internal/log_analysis/log_processor/parsers/nginxlogs/access_test.go
  internal/log_analysis/log_processor/parsers/osquerylogs/batch.go
  internal/log_analysis/log_processor/parsers/osquerylogs/batch_test.go
  internal/log_analysis/log_processor/parsers/osquerylogs/differential.go
  internal/log_analysis/log_processor/parsers/osquerylogs/differential_test.go
  internal/log_analysis/log_processor/parsers/osquerylogs/snapshot.go
  internal/log_analysis/log_processor/parsers/osquerylogs/snapshot_test.go
  internal/log_analysis/log_processor/parsers/osquerylogs/status.go
  internal/log_analysis/log_processor/parsers/osquerylogs/status_test.go
  internal/log_analysis/log_processor/parsers/osseclogs/eventinfo.go
  internal/log_analysis/log_processor/parsers/osseclogs/eventinfo_test.go
  internal/log_analysis/log_processor/parsers/pantherlog_test.go
  internal/log_analysis/log_processor/parsers/patherlog.go
  internal/log_analysis/log_processor/parsers/timestamp/timestamp.go
  tools/athenaviews/athenaviews_test.go
Labels: backend team, data inputs, log analysis

#327 Resource Lookup
  deployments/compliance/resources_api.yml
  go.sum
  internal/compliance/aws_event_processor/processor/process.go
  internal/compliance/policy_engine/src/engine.py
  internal/compliance/policy_engine/src/helpers.py
  internal/compliance/policy_engine/src/policy.py
  internal/compliance/policy_engine/tests/test_helpers.py
Labels: backend team, cloud security

#312 Opstool: requeue
  cmd/opstools/requeue/integration_test.go
  cmd/opstools/requeue/requeue.go
  cmd/opstools/requeue/requeue/main.go
  docs/gitbook/operations/ops-home.md
  tools/mage/build_namespace.go
  tools/mage/fmt.go
Labels: operations

#336 Bug scanning buckets in us-east-1
  internal/compliance/snapshot_poller/pollers/aws/s3_bucket.go
  internal/compliance/snapshot_poller/pollers/aws/s3_bucket_test.go
Labels: bug, cloud security

#321 Update lint-staged scripts
  .prettierignore
  deployments/auxiliary/cloudformation/panther-deployment-role.yml
  internal/compliance/aws_event_processor/processor/example_events/cloudtrail_put_event_selectors.json
  internal/core/analysis_api/main/test_policies/always_true.json
  lint-staged.config.js
  tools/mage/fmt.go
Labels: frontend

#320 Syslog parser for RFC3164 formatted logs
  docs/gitbook/log-analysis/supported-logs/README.md
  go.mod
  go.sum
  internal/log_analysis/log_processor/parsers/sysloglogs/rfc3164.go
  internal/log_analysis/log_processor/parsers/sysloglogs/rfc3164_test.go
  internal/log_analysis/log_processor/registry/registry.go
  web/src/constants.ts
Labels: log analysis, logs

#354 Remove Outdated Analysis Documentation
  docs/gitbook/log-analysis/rules/aws/aws-iam-anything-changed.md
  docs/gitbook/log-analysis/rules/aws/aws-iam-assume-role-blacklist-ignored.md
  docs/gitbook/log-analysis/rules/aws/aws-iam-entity-created-without-cloudformation.md
  docs/gitbook/log-analysis/rules/aws/aws-root-access-key-created.md
  docs/gitbook/log-analysis/rules/aws/aws-root-console-login.md
  docs/gitbook/log-analysis/rules/aws/aws-root-password-changed.md
  docs/gitbook/policies/policies/aws/aws-acm-certificates-are-valid.md
  docs/gitbook/policies/policies/aws/aws-cloudformation-stack-has-not-drifted.md
  docs/gitbook/policies/policies/aws/aws-cloudformation-stack-has-termination-protection.md
  docs/gitbook/policies/policies/aws/aws-cloudformation-stack-uses-iam-service-role.md
  docs/gitbook/policies/policies/aws/aws-cloudtrail-least-privilege-access-configured.md
  docs/gitbook/policies/policies/aws/aws-cloudtrail-logs-has-data-retention-of-one-year.md
  docs/gitbook/policies/policies/aws/aws-cloudwatch-logs-are-encrypted.md
  docs/gitbook/policies/policies/aws/aws-config-is-recording.md
  docs/gitbook/policies/policies/aws/aws-config-recording-with-no-errors.md
  docs/gitbook/policies/policies/aws/aws-config-records-all-resource-types.md
  docs/gitbook/policies/policies/aws/aws-customer-owned-ami-is-private.md
  docs/gitbook/policies/policies/aws/aws-ec2-volume-snapshot-is-encrypted.md
  docs/gitbook/policies/policies/aws/aws-network-acl-restricts-ssh.md
  docs/gitbook/policies/policies/aws/aws-rds-instance-has-auto-minor-version-upgrade-enabled.md
Labels: documentation

#342 Provide CFN Templates via API
  api/lambda/source/models/api.go
  api/lambda/source/models/integration.go
  deployments/auxiliary/cloudformation/panther-compliance-iam.yml
  deployments/auxiliary/cloudformation/panther-log-processing-iam.yml
  deployments/core/source_api.yml
  internal/core/source_api/api/get_integration_template.go
Labels: backend team

#363 Poller Scanning Nonexistant ECS Clusters Fix
  internal/compliance/snapshot_poller/pollers/aws/ecs_cluster.go
  internal/compliance/snapshot_poller/pollers/aws/ecs_cluster_test.go
Labels: backend team, bug, cloud security

#330 Mage Teardown
  deployments/backend.yml
  deployments/core/analysis_api.yml
  deployments/core/appsync.yml
  deployments/core/buckets.yml
  docs/gitbook/development.md
  tools/mage/deploy.go
  tools/mage/deploy_certificate.go
  tools/mage/teardown.go
  tools/mage/test_namespace.go
  tools/mage/util.go
  tools/mage/util_cfn.go
Labels: mage

#370 Force npm resolutions for acorn
  package-lock.json
  package.json
Labels: frontend, security

#261 Syslog Parser for RFC5424 formetted logs
  docs/gitbook/log-analysis/supported-logs/README.md
  internal/log_analysis/log_processor/parsers/sysloglogs/rfc3164_test.go
  internal/log_analysis/log_processor/parsers/sysloglogs/rfc5424.go
  internal/log_analysis/log_processor/parsers/sysloglogs/rfc5424_test.go
  internal/log_analysis/log_processor/registry/registry.go
  tools/cfngen/gluecf/schema.go
  tools/cfngen/gluecf/schema_test.go
  web/src/constants.ts
Labels: log analysis, logs

#364 Source API Log Analysis Deletion Fix
  internal/core/source_api/api/delete_integration_test.go
  internal/core/source_api/api/sqs_utils.go
Labels: backend team, cloud security

#380 Minor Fixes
  internal/compliance/alert_processor/processor/processor_test.go
  internal/compliance/aws_event_processor/processor/process.go
  internal/compliance/compliance_api/main/integration_test.go
  internal/compliance/resource_processor/processor/analysis_api.go
  internal/compliance/resource_processor/processor/handler.go
Labels: bug, cloud security

#386 Fallback to IAM when ACM limit reached
  tools/mage/deploy_certificate.go
Labels: deployment, mage

#382 Fix swagger generation
  api/gateway/compliance/client/operations/delete_status_parameters.go
  api/gateway/compliance/client/operations/delete_status_responses.go
  api/gateway/compliance/client/operations/describe_org_responses.go
  api/gateway/compliance/client/operations/describe_policy_responses.go
  api/gateway/compliance/client/operations/describe_resource_responses.go
  api/gateway/compliance/client/operations/get_org_overview_responses.go
  api/gateway/compliance/client/operations/get_status_responses.go
  api/gateway/compliance/client/operations/operations_client.go
  api/gateway/compliance/client/operations/set_status_parameters.go
  api/gateway/compliance/client/operations/set_status_responses.go
  api/gateway/compliance/client/operations/update_metadata_parameters.go
  api/gateway/compliance/client/operations/update_metadata_responses.go
  api/gateway/compliance/client/panther_compliance_client.go
  api/gateway/remediation/client/operations/list_remediations_responses.go
  api/gateway/remediation/client/operations/operations_client.go
  api/gateway/remediation/client/operations/remediate_resource_async_parameters.go
  api/gateway/remediation/client/operations/remediate_resource_async_responses.go
  api/gateway/remediation/client/operations/remediate_resource_parameters.go
  api/gateway/remediation/client/operations/remediate_resource_responses.go
  api/gateway/remediation/client/panther_remediation_client.go
  api/gateway/remediation/models/error.go
  api/gateway/resources/client/operations/add_resources_parameters.go
  api/gateway/resources/client/operations/add_resources_responses.go
  api/gateway/resources/client/operations/delete_resources_parameters.go
  api/gateway/resources/client/operations/delete_resources_responses.go
  api/gateway/resources/client/operations/get_org_overview_responses.go
  api/gateway/resources/client/operations/get_resource_responses.go
  api/gateway/resources/client/operations/list_resources_responses.go
  api/gateway/resources/client/operations/modify_resource_parameters.go
  api/gateway/resources/client/operations/modify_resource_responses.go
  api/gateway/resources/client/operations/operations_client.go
  api/gateway/resources/client/panther_resources_client.go
  internal/compliance/remediation_api/handlers/post.go
  internal/compliance/remediation_api/remediation/invoke.go
  internal/compliance/remediation_api/remediation/invoke_test.go
  tools/mage/build_namespace.go
  tools/mage/fmt.go
  tools/mage/test_namespace.go
Labels: mage

#388 Fixed Setup and Teardown of Cloud Watch Events Stack Set
  deployments/auxiliary/cloudformation/panther-cloudwatch-events.yml
  deployments/onboard.yml
  deployments/panther_config.yml
  tools/mage/config.go
  tools/mage/deploy.go
  tools/mage/deploy_onboard.go
  tools/mage/teardown.go
Labels: bug, deployment, mage

#402 lookup globals file when missing
  deployments/compliance/resources_api.yml
  internal/compliance/resource_processor/processor/analysis_api.go
  internal/compliance/resource_processor/processor/handler.go
Labels: backend team, bug, cloud security

#403 [docs] README refresh, Gitter -> Slack, new screenshots
  README.md
  docs/gitbook/quick-start.md
  docs/img/alert-viewer-new.png
  docs/img/resource-viewer-new.png
  docs/img/rule-editor-new.png
  docs/img/rule-search-new.png
Labels: documentation

#416 Have datacatalog updater us the common function to create partitions
  internal/log_analysis/datacatalog_updater/main/lambda_test.go
  pkg/awsglue/glue.go
  pkg/awsglue/partition.go
  pkg/awsglue/partition_test.go
Labels: bug

#444 Mage build:cfn and refactor monitoring stack
  .prettierignore
  deployments/backend.yml
  deployments/monitoring.yml
  docs/gitbook/operations/runbooks.md
  tools/cfngen/cf.go
  tools/cfngen/cloudwatchcf/alarms.go
  tools/cfngen/cloudwatchcf/alarms_apigw.go
  tools/cfngen/cloudwatchcf/alarms_appsync.go
  tools/cfngen/cloudwatchcf/alarms_ddb.go
  tools/cfngen/cloudwatchcf/alarms_elb.go
  tools/cfngen/cloudwatchcf/alarms_lambda.go
  tools/cfngen/cloudwatchcf/alarms_sns.go
  tools/cfngen/cloudwatchcf/alarms_sqs.go
  tools/cfngen/cloudwatchcf/alarms_test.go
  tools/cfngen/cloudwatchcf/dashboard.go
  tools/cfngen/cloudwatchcf/dashboards_test.go
  tools/cfngen/cloudwatchcf/metrics_test.go
  tools/cfngen/cloudwatchcf/testdata/cf.yml
  tools/cfngen/cloudwatchcf/testdata/generated_test_alarms.json
  tools/cfngen/cloudwatchcf/testdata/generated_test_metrics.json
  tools/cfngen/cloudwatchcf/util_test.go
  tools/cfngen/gluecf/db_test.go
  tools/cfngen/gluecf/gluecf_test.go
  tools/cfngen/gluecf/table_test.go
  tools/cfngen/gluecf/testdata/db.template.json
  tools/cfngen/gluecf/testdata/tables.template.json
  tools/cfngen/gluecf/util_test.go
  tools/config/config.go
  tools/dashboards/dashboards.go
  tools/mage/build_namespace.go
  tools/mage/cfngen.go
  tools/mage/deploy.go
  tools/mage/deploy_databases.go
  tools/mage/deploy_frontend.go
  tools/mage/deploy_monitoring.go
  tools/mage/deploy_template.go
  tools/mage/doc_namespace.go
  tools/mage/swagger.go
  tools/mage/swagger_test.go
  tools/mage/test_namespace.go
  tools/mage/testdata/valid-api-expected-output.yml
  tools/mage/testdata/valid-api.yml
Labels: mage

#480 Docs Refactor Pt 1
  README.md
  docs/gitbook/README.md
  docs/gitbook/SUMMARY.md
  docs/gitbook/automatic-remediation/auto-remediations/README.md
  docs/gitbook/automatic-remediation/automatic-remediation.md
  docs/gitbook/cost.md
  docs/gitbook/development.md
  docs/gitbook/policies/automatic-remediation/README.md
  docs/gitbook/policies/automatic-remediation/aws/README.md
  docs/gitbook/policies/automatic-remediation/aws/aws-block-public-access-for-s3-bucket.md
  docs/gitbook/policies/automatic-remediation/aws/aws-block-s3-bucket-public-acl.md
  docs/gitbook/policies/automatic-remediation/aws/aws-create-guardduty-detector.md
  docs/gitbook/policies/automatic-remediation/aws/aws-disable-rds-instance-public-access.md
  docs/gitbook/policies/automatic-remediation/aws/aws-enable-cloudtrail-log-validation.md
  docs/gitbook/policies/automatic-remediation/aws/aws-enable-dynamodb-table-encryption.md
  docs/gitbook/policies/automatic-remediation/aws/aws-enable-kms-key-rotation.md
  docs/gitbook/policies/automatic-remediation/aws/aws-enable-rds-instance-auto-minor-version-upgrade.md
  docs/gitbook/policies/automatic-remediation/aws/aws-enable-s3-bucket-access-logging.md
  docs/gitbook/policies/automatic-remediation/aws/aws-enable-s3-bucket-encryption.md
  docs/gitbook/policies/automatic-remediation/aws/aws-enable-s3-bucket-versioning.md
  docs/gitbook/policies/automatic-remediation/aws/aws-enable-vpc-flow-logs-to-s3.md
  docs/gitbook/policies/automatic-remediation/aws/aws-stop-ec2-instance.md
  docs/gitbook/policies/automatic-remediation/aws/aws-terminate-ec2-instance.md
  docs/gitbook/policies/automatic-remediation/aws/aws-update-account-password-policy.md
  docs/gitbook/policies/automatic-remediation/aws/aws.cloudtrail.createtrail.md
  docs/gitbook/policies/cloud-security-overview.md
  docs/gitbook/quick-start.md
Labels: documentation

#495 Doc Review [Pt 4] + More
  docs/gitbook/.gitbook/assets/log-analysis-iam-1.png
  docs/gitbook/.gitbook/assets/log-analysis-iam-2-optional.png
  docs/gitbook/.gitbook/assets/log-analysis-iam-2.png
  docs/gitbook/.gitbook/assets/log-analysis-iam-3.png
  docs/gitbook/.gitbook/assets/log-analysis-iam-4.png
  docs/gitbook/.gitbook/assets/log-analysis-iam-5.png
  docs/gitbook/README.md
  docs/gitbook/SUMMARY.md
  docs/gitbook/cost.md
  docs/gitbook/development.md
  docs/gitbook/log-analysis/log-processing/README.md
  docs/gitbook/log-analysis/log-processing/iam-setup.md
  docs/gitbook/log-analysis/rules/README.md
  docs/gitbook/log-analysis/rules/aws-cis/README.md
  docs/gitbook/log-analysis/supported-logs/README.md
  docs/gitbook/quick-start.md
  docs/gitbook/writing-parsers.md
  internal/core/alert_delivery/outputs/outputs.go
  internal/core/alert_delivery/outputs/outputs_test.go
  internal/core/source_api/api/put_integration.go
  web/src/components/wizards/ComplianceSourceWizard/StackDeploymentPanel/StackDeployment.tsx
  web/src/components/wizards/LogSourceWizard/SourceConfigurationPanel/SourceConfigurationPanel.tsx
  web/src/components/wizards/LogSourceWizard/StackDeploymentPanel/StackDeployment.tsx
Labels: alerting, documentation, frontend

#546 Pinning template to specific version
  tools/mage/deploy_onboard.go
Labels: bug

#545 Fix clearing of s3 event notifications and add delay before deleting bucket in mage:teardown
  tools/mage/teardown.go
Labels: bug

#548 Refactor mage show:schemas so it stays up to date and conforms to other targets
  tools/mage/show_namespace.go
Labels: deployment

#551 Rule Field Mappings in BulkUpload
  api/gateway/analysis/configmodels.go
  internal/core/analysis_api/handlers/bulk_upload.go
Labels: backend team

#549 Add analysis_api to cloudsec dashboard
  tools/dashboards/infra.go
Labels: bug

#550 Whitelist StartSchemaCreation in aws event processor
  internal/compliance/aws_event_processor/processor/process.go
Labels: bug

#541 Doc Reorganization: QuickStart, Log Onboarding, Rules
  README.md
  docs/gitbook/.gitbook/assets/create-sns-topic-1.png
  docs/gitbook/.gitbook/assets/create-sns-topic-2.png
  docs/gitbook/.gitbook/assets/panther_graphic_flow.jpg
  docs/gitbook/README.md
  docs/gitbook/SUMMARY.md
  docs/gitbook/log-analysis/log-processing/README.md
  docs/gitbook/log-analysis/log-processing/iam-setup.md
  docs/gitbook/log-analysis/log-processing/notifications-setup.md
  docs/gitbook/log-analysis/log-processing/setup.md
  docs/gitbook/log-analysis/rules/README.md
  docs/gitbook/log-analysis/rules/aws-cis/README.md
  docs/gitbook/log-analysis/writing-parsers.md
  docs/gitbook/quick-start.md
  docs/gitbook/security-privacy.md
  docs/gitbook/support.md
  docs/gitbook/troubleshooting.md
  package-lock.json
  package.json
  web/src/components/forms/AnalyticsConsentForm/ErrorReportingSection.tsx
  web/src/pages/Landing/Landing.tsx
  web/src/pages/Landing/index.tsx
Labels: documentation

#554 Fix regression in log processor test framework
  internal/log_analysis/log_processor/parsers/awslogs/alb_test.go
  internal/log_analysis/log_processor/parsers/awslogs/aurora_mysql_audit_test.go
  internal/log_analysis/log_processor/parsers/awslogs/cloudtrail_test.go
  internal/log_analysis/log_processor/parsers/awslogs/guardduty_test.go
  internal/log_analysis/log_processor/parsers/awslogs/s3_server_access_test.go
  internal/log_analysis/log_processor/parsers/awslogs/vpc_flow_test.go
  internal/log_analysis/log_processor/parsers/nginxlogs/access_test.go
  internal/log_analysis/log_processor/parsers/osquerylogs/batch_test.go
  internal/log_analysis/log_processor/parsers/osquerylogs/differential_test.go
  internal/log_analysis/log_processor/parsers/osquerylogs/snapshot_test.go
  internal/log_analysis/log_processor/parsers/osquerylogs/status_test.go
  internal/log_analysis/log_processor/parsers/osseclogs/eventinfo_test.go
  internal/log_analysis/log_processor/parsers/sysloglogs/rfc3164_test.go
  internal/log_analysis/log_processor/parsers/sysloglogs/rfc5424_test.go
  internal/log_analysis/log_processor/parsers/testutil/testutil.go
Labels: bug

#552 Add missing log groups analysis_api and compliance_api to overview dashboard
  tools/dashboards/overview.go
Labels: bug

#544 Added default functions for dedup and title
  web/src/constants.ts
  web/src/pages/CreateRule/CreateRule.tsx
Labels: documentation

#559 Fix remediation role construction
  internal/compliance/remediation_aws/src/app/remediations/remediation_base.py
Labels: auto remediation, backend team, bug

#564 Fixing stability issues
  deployments/panther_config.yml
  internal/log_analysis/alert_forwarder/forwarder/forwarder.go
  internal/log_analysis/alert_forwarder/forwarder/forwarder_test.go
  internal/log_analysis/rules_engine/src/engine.py
  internal/log_analysis/rules_engine/src/rule.py
  internal/log_analysis/rules_engine/tests/test_rule.py
  pkg/awsglue/partition.go
  tools/config/config.go
  tools/mage/deploy.go
  tools/mage/deploy_onboard.go
Labels: bug

#565 Updated remediation docs
  docs/gitbook/.gitbook/assets/automaticRemediationOptions.png
  docs/gitbook/.gitbook/assets/enableRemediations.png
  docs/gitbook/.gitbook/assets/remediateButton.png
  docs/gitbook/policies/automatic-remediation/README.md
Labels: documentation

#535 Parsers: Fluentd Syslog Support #437
  internal/log_analysis/log_processor/parsers/fluentdsyslogs/rfc3164.go
  internal/log_analysis/log_processor/parsers/fluentdsyslogs/rfc3164_test.go
  internal/log_analysis/log_processor/parsers/fluentdsyslogs/rfc5424.go
  internal/log_analysis/log_processor/parsers/fluentdsyslogs/rfc5424_test.go
  internal/log_analysis/log_processor/parsers/timestamp/timestamp.go
  internal/log_analysis/log_processor/parsers/timestamp/timestamp_test.go
  internal/log_analysis/log_processor/registry/registry.go
  tools/cfngen/gluecf/gluecf.go
Labels: logs

#566 Update policy library versions
  docs/gitbook/policies/policies/README.md
Labels: documentation

#578 Updated documentation on policies
  docs/gitbook/.gitbook/assets/automaticRemediationOptions.png
  docs/gitbook/.gitbook/assets/bulk-upload-1.png
  docs/gitbook/.gitbook/assets/bulk-upload-2.png
  docs/gitbook/.gitbook/assets/cloud-security-overview-new.png
  docs/gitbook/.gitbook/assets/policyAttributesSet.png
  docs/gitbook/.gitbook/assets/policyBodySet.png
  docs/gitbook/.gitbook/assets/policyTestsSet.png
  docs/gitbook/SUMMARY.md
  docs/gitbook/log-analysis/rules/README.md
  docs/gitbook/policies/automatic-remediation/README.md
  docs/gitbook/policies/cloud-security-overview.md
  docs/gitbook/policies/policies/README.md
  docs/gitbook/policies/policies/testing.md
  docs/gitbook/policies/policies/uploading.md
  docs/gitbook/policies/policies/writing.md
  docs/gitbook/policies/scanning/README.md
Labels: documentation

#586 Fixing fluentd parsers
  README.md
  internal/log_analysis/log_processor/parsers/fluentdsyslogs/rfc3164.go
  internal/log_analysis/log_processor/parsers/fluentdsyslogs/rfc3164_test.go
  internal/log_analysis/log_processor/parsers/fluentdsyslogs/rfc5424.go
  internal/log_analysis/log_processor/parsers/fluentdsyslogs/rfc5424_test.go
Labels: bug, logs

#591 Bring in master docs
  .all-contributorsrc
  README.md
  docs/gitbook/.gitbook/assets/bulk-upload-1.png
  docs/gitbook/.gitbook/assets/bulk-upload-2.png
  docs/gitbook/.gitbook/assets/cloud-security-overview-new.png
  docs/gitbook/.gitbook/assets/policyAttributesSet.png
  docs/gitbook/.gitbook/assets/policyBodySet.png
  docs/gitbook/.gitbook/assets/policyTestsSet.png
  docs/gitbook/SUMMARY.md
  docs/gitbook/log-analysis/log-processing/writing-parsers.md
  docs/gitbook/log-analysis/rules/README.md
  docs/gitbook/policies/automatic-remediation/README.md
  docs/gitbook/policies/cloud-security-overview.md
  docs/gitbook/policies/policies/README.md
  docs/gitbook/policies/policies/testing.md
  docs/gitbook/policies/policies/uploading.md
  docs/gitbook/policies/policies/writing.md
  docs/gitbook/policies/scanning/README.md
  internal/log_analysis/log_processor/parsers/fluentdsyslogs/rfc3164.go
  internal/log_analysis/log_processor/parsers/fluentdsyslogs/rfc3164_test.go
  internal/log_analysis/log_processor/parsers/fluentdsyslogs/rfc5424.go
  internal/log_analysis/log_processor/parsers/fluentdsyslogs/rfc5424_test.go
  internal/log_analysis/log_processor/parsers/osquerylogs/differential.go
  internal/log_analysis/log_processor/parsers/osquerylogs/differential_test.go
Labels: documentation

#596 [docs] readme small tweaks, better res logo
  README.md
  docs/img/panther-logo-github-highres.png
  docs/img/panther-logo-github.jpg
Labels: documentation

#601 mage doc: sort list of json type components for consistent output
  docs/gitbook/log-analysis/log-processing/supported-logs/AWS.md
  tools/mage/doc.go
Labels: bug

#599 [web] SNS/SQS Destination Policy and Toast Fix
  README.md
  web/src/components/forms/SnsDestinationForm/SnsDestinationForm.tsx
  web/src/components/forms/SqsDestinationForm/SqsDestinationForm.tsx
  web/src/pages/EditRule/EditRule.tsx
Labels: frontend

#611 Fix incorrect endpoint in log processing SNS setup doc
  docs/gitbook/log-analysis/log-processing/README.md
Labels: bug
