Repository panther-labs/panther, pull requests merged in 2020-05, with the labels that each got.

#818 Add alb latency and 5XX alarms
  tools/cfngen/cloudwatchcf/alarms.go
  tools/cfngen/cloudwatchcf/alarms_elb.go
  tools/cfngen/cloudwatchcf/testdata/generated_test_alarms.json
Labels: operations

#811 Alter Auth-related error messages
  deployments/bootstrap.yml
  web/src/components/forms/ForgotPasswordForm/ForgotPasswordForm.tsx
  web/src/pages/ForgotPassword/ForgotPassword.tsx
Labels: p1, security

#824 Resource Timeouts
  internal/compliance/aws_event_processor/processor/ec2.go
  internal/compliance/resources_api/handlers/add_resources.go
Labels: backend team, bug

#820 Add PantherEdition tag so it easy to tell apart Enterprise vs OpenSource
  tools/mage/deploy_template.go
Labels: operations

#821 Remove un-needed permissions in log_analysis.yml
  deployments/log_analysis.yml
Labels: operations

#826 Fix capitalization issues with cloudtrail json tags
  docs/gitbook/log-analysis/log-processing/supported-logs/AWS.md
  internal/log_analysis/log_processor/parsers/awslogs/cloudtrail.go
Labels: bug

#827 Grant rules engine permission to query resources table
  deployments/log_analysis.yml
Labels: backend team, enhancement, log analysis

#828 v1.2.0 Release
  docs/gitbook/development.md
  docs/gitbook/quick-start.md
Labels: documentation

#835 Proper handling of layer related events
  internal/compliance/aws_event_processor/processor/lambda.go
Labels: backend team, bug, cloud security

#841 Fix error handing in awsathena.WaitForResults
  pkg/awsathena/integration_test.go
  pkg/awsathena/query.go
Labels: bug

#857 Add custom certificate CFN resource
  deployments/bootstrap.yml
  deployments/bootstrap_gateway.yml
  deployments/web_server.yml
  docs/gitbook/operations/runbooks.md
  go.mod
  go.sum
  internal/compliance/snapshot_poller/pollers/aws/cloudformation_stack.go
  internal/compliance/snapshot_poller/pollers/aws/iam_user.go
  internal/core/custom_resources/main/lambda.go
  internal/core/custom_resources/resources/certificate.go
  internal/core/custom_resources/resources/clients.go
  internal/core/custom_resources/resources/map.go
  pkg/awsbatch/dynamodbbatch/batch_write_item.go
  pkg/awsbatch/kinesisbatch/put_records.go
  pkg/awsbatch/s3batch/delete_objects.go
  pkg/awsbatch/sqsbatch/send_message_batch.go
  tools/mage/deploy.go
  tools/mage/deploy_certificate.go
  tools/mage/deploy_frontend.go
  tools/mage/deploy_template.go
  tools/mage/teardown.go
  tools/mage/util.go
Labels: deployment

#865 Fix scheduler bug
  api/lambda/source/models/api.go
  internal/compliance/snapshot_scheduler/scheduler/schedule.go
  internal/compliance/snapshot_scheduler/scheduler/schedule_test.go
  internal/core/source_api/api/put_integration.go
  internal/core/source_api/api/put_integration_test.go
Labels: backend team, bug, cloud security

#866 Update docs to v1.2.1
  docs/gitbook/development.md
  docs/gitbook/quick-start.md
Labels: documentation

#863 Custom resource for Cognito MFA, use sam packaging
  deployments/bootstrap_gateway.yml
  deployments/panther_config.yml
  internal/core/custom_resources/main/lambda.go
  internal/core/custom_resources/resources/certificate.go
  internal/core/custom_resources/resources/clients.go
  internal/core/custom_resources/resources/cognito_user_pool_mfa.go
  internal/core/custom_resources/resources/map.go
  requirements-top-level.txt
  requirements.txt
  tools/mage/build_namespace.go
  tools/mage/deploy.go
  tools/mage/deploy_template.go
Labels: deployment

#871 Small fixes in the log processing SNS instructions
  docs/gitbook/log-analysis/log-processing/README.md
Labels: documentation

#876 Validate aws acount ids before updating p_any_aws_account_ids field
  internal/log_analysis/log_processor/parsers/awslogs/extractor.go
  internal/log_analysis/log_processor/parsers/awslogs/pantherlog.go
  internal/log_analysis/log_processor/parsers/awslogs/pantherlog_test.go
Labels: bug

#872 Custom resource: metric filters
  deployments/bootstrap_gateway.yml
  deployments/cloud_security.yml
  deployments/core.yml
  deployments/log_analysis.yml
  internal/core/custom_resources/main/lambda.go
  internal/core/custom_resources/resources/certificate.go
  internal/core/custom_resources/resources/clients.go
  internal/core/custom_resources/resources/cognito_user_pool_mfa.go
  internal/core/custom_resources/resources/lambda_metric_filters.go
  internal/core/custom_resources/resources/map.go
  internal/core/custom_resources/resources/parser.go
  tools/cfngen/cloudwatchcf/alarms_lambda.go
  tools/cfngen/cloudwatchcf/metrics.go
  tools/cfngen/cloudwatchcf/metrics_lambda.go
  tools/cfngen/cloudwatchcf/metrics_test.go
  tools/mage/build_namespace.go
  tools/mage/cfngen.go
  tools/mage/deploy.go
  tools/mage/teardown.go
  tools/mage/test_namespace.go
  tools/mage/util_cfn.go
Labels: deployment

#878 Simplify metric filters
  internal/core/custom_resources/resources/lambda_metric_filters.go
  internal/core/custom_resources/resources/map.go
Labels: deployment

#879 Custom resource: ApiGatewayAlarms
  deployments/alarms.yml
  deployments/bootstrap.yml
  deployments/bootstrap_gateway.yml
  docs/gitbook/operations/runbooks.md
  internal/core/custom_resources/resources/alarms_api_gateway.go
  internal/core/custom_resources/resources/clients.go
  internal/core/custom_resources/resources/map.go
  internal/core/custom_resources/resources/parser.go
  tools/cfngen/cloudwatchcf/alarms.go
  tools/cfngen/cloudwatchcf/alarms_apigw.go
  tools/cfngen/cloudwatchcf/testdata/cf.yml
  tools/cfngen/cloudwatchcf/testdata/generated_test_alarms.json
  tools/cfngen/cloudwatchcf/testdata/generated_test_metrics.json
  tools/mage/deploy.go
  tools/mage/test_namespace.go
Labels: deployment

#885 Document Parquet
  docs/gitbook/SUMMARY.md
  docs/gitbook/enterprise/log-compaction.md
Labels: documentation

#888 [deployment] bucket hardening
  deployments/bootstrap.yml
Labels: p3, security

#899 Add support for multiple globals
  api/gateway/analysis/api.yml
  api/gateway/analysis/client/operations/list_globals_parameters.go
  api/gateway/analysis/client/operations/list_globals_responses.go
  api/gateway/analysis/client/operations/operations_client.go
  api/gateway/analysis/models/global_list.go
  api/gateway/analysis/models/global_summary.go
  deployments/core.yml
  internal/core/analysis_api/handlers/bulk_upload.go
  internal/core/analysis_api/handlers/list_globals.go
  internal/core/analysis_api/handlers/util.go
  internal/core/analysis_api/main/lambda.go
  internal/core/layer_manager/manager/handle.go
Labels: backend team, enhancement

#905 Fix typo doc generation
  docs/gitbook/log-analysis/log-processing/supported-logs/AWS.md
  docs/gitbook/log-analysis/log-processing/supported-logs/GitLab.md
  docs/gitbook/log-analysis/log-processing/supported-logs/OSSEC.md
  docs/gitbook/log-analysis/log-processing/supported-logs/Osquery.md
  docs/gitbook/log-analysis/log-processing/supported-logs/Suricata.md
  docs/gitbook/log-analysis/log-processing/supported-logs/Syslog.md
  tools/mage/doc.go
  tools/mage/logdoc_test.go
Labels: bug

#906 downgraded to Info lvl messages
  internal/compliance/aws_event_processor/processor/acm.go
  internal/compliance/aws_event_processor/processor/cloudformation.go
  internal/compliance/aws_event_processor/processor/cloudtrail.go
  internal/compliance/aws_event_processor/processor/cloudwatch_log_group.go
  internal/compliance/aws_event_processor/processor/config.go
  internal/compliance/aws_event_processor/processor/dynamodb.go
  internal/compliance/aws_event_processor/processor/ec2.go
  internal/compliance/aws_event_processor/processor/ecs.go
  internal/compliance/aws_event_processor/processor/elbv2.go
  internal/compliance/aws_event_processor/processor/guardduty.go
  internal/compliance/aws_event_processor/processor/iam.go
  internal/compliance/aws_event_processor/processor/kms.go
  internal/compliance/aws_event_processor/processor/lambda.go
  internal/compliance/aws_event_processor/processor/rds.go
  internal/compliance/aws_event_processor/processor/redshift.go
  internal/compliance/aws_event_processor/processor/waf-regional.go
  internal/compliance/aws_event_processor/processor/waf.go
Labels: backend team, cloud security, monitoring

#914 Add Suricata to doc summary
  docs/gitbook/SUMMARY.md
Labels: documentation

#908 Add Unknown Events Panel to Cloudsec Dashboard
  tools/dashboards/infra.go
Labels: operations

#915 Add Panther Enterprise Log Docs
  docs/gitbook/SUMMARY.md
  docs/gitbook/log-analysis/log-processing/supported-logs/GCP.md
  docs/gitbook/log-analysis/log-processing/supported-logs/Okta.md
  docs/gitbook/log-analysis/log-processing/supported-logs/OneLogin.md
Labels: documentation

#920 Store rule tags for alerts in Athena
  api/gateway/analysis/api.yml
  api/gateway/analysis/models/enabled_policy.go
  internal/core/analysis_api/handlers/get_enabled_analyses.go
  internal/core/analysis_api/main/integration_test.go
  internal/log_analysis/rules_engine/src/__init__.py
  internal/log_analysis/rules_engine/src/engine.py
  internal/log_analysis/rules_engine/src/output.py
  internal/log_analysis/rules_engine/src/rule.py
  internal/log_analysis/rules_engine/tests/test_engine.py
  internal/log_analysis/rules_engine/tests/test_output.py
  internal/log_analysis/rules_engine/tests/test_rule.py
  tools/cfngen/gluecf/gluecf.go
  tools/cfngen/gluecf/testdata/gluecf.json.cf
Labels: enhancement

#925 Use API ID (not name) for appsync alarms
  internal/core/custom_resources/resources/alarms_appsync.go
Labels: bug, deployment

#926 Custom resource: dynamo alarms
  deployments/cloud_security.yml
  deployments/core.yml
  deployments/log_analysis.yml
  internal/core/custom_resources/resources/alarms_dynamo.go
  internal/core/custom_resources/resources/map.go
  tools/cfngen/cloudwatchcf/alarms.go
  tools/cfngen/cloudwatchcf/alarms_ddb.go
  tools/cfngen/cloudwatchcf/testdata/cf.yml
  tools/cfngen/cloudwatchcf/testdata/generated_test_alarms.json
  tools/mage/deploy.go
  tools/mage/test_namespace.go
Labels: deployment

#938 Prep bootstrap stack for SAR packaging
  deployments/bootstrap.yml
  deployments/bootstrap_gateway.yml
  deployments/onboard.yml
  deployments/web_server.yml
  tools/mage/deploy.go
  tools/mage/deploy_onboard.go
Labels: deployment

#952 Added support for backing up processed data
  deployments/bootstrap.yml
  deployments/panther_config.yml
  tools/config/config.go
  tools/mage/deploy.go
Labels: operations

#950 Pre-packaged deployment: initial master stack
  deployments/bootstrap.yml
  deployments/bootstrap_gateway.yml
  deployments/dashboards.yml
  deployments/master.yml
  tools/cfngen/cloudwatchcf/dashboard.go
  tools/mage/cfngen.go
  tools/mage/deploy.go
  tools/mage/deploy_template.go
Labels: deployment

#949 Remove glue table stack
  deployments/appsync.yml
  deployments/bootstrap_gateway.yml
  deployments/core.yml
  deployments/log_analysis.yml
  deployments/master.yml
  internal/core/custom_resources/resources/athena.go
  internal/core/custom_resources/resources/clients.go
  internal/core/custom_resources/resources/glue.go
  internal/core/custom_resources/resources/map.go
  internal/core/source_api/api/glue_utils.go
  internal/core/source_api/api/put_integration.go
  internal/core/source_api/api/put_integration_test.go
  internal/core/source_api/api/update_integration.go
  internal/core/source_api/api/update_integration_test.go
  internal/core/source_api/api/vars.go
  internal/log_analysis/athenaviews/athenaviews.go
  internal/log_analysis/athenaviews/athenaviews_test.go
  internal/log_analysis/awsglue/awsglue.go
  internal/log_analysis/awsglue/integration_test.go
  internal/log_analysis/awsglue/schema.go
  internal/log_analysis/awsglue/schema_test.go
  internal/log_analysis/awsglue/table_metadata.go
  internal/log_analysis/awsglue/table_metadata_test.go
  internal/log_analysis/awsglue/wrappers.go
  internal/log_analysis/gluetables/gluetables.go
  internal/log_analysis/gluetables/gluetables_test.go
  pkg/testutils/awsmocks.go
  tools/cfngen/gluecf/db.go
  tools/cfngen/gluecf/doc.go
  tools/cfngen/gluecf/gluecf.go
  tools/cfngen/gluecf/gluecf_test.go
  tools/cfngen/gluecf/table.go
  tools/cfngen/gluecf/table_test.go
  tools/cfngen/gluecf/testdata/db.template.json
  tools/cfngen/gluecf/testdata/gluecf.json.cf
  tools/cfngen/gluecf/testdata/tables.template.json
  tools/mage/build_namespace.go
  tools/mage/cfngen.go
  tools/mage/deploy.go
  tools/mage/deploy_onboard.go
  tools/mage/doc.go
  tools/mage/glue_namespace.go
  tools/mage/teardown.go
  tools/mage/util_cfn.go
Labels: bug, enhancement

#957 Improve mage doc error messages
  tools/mage/doc.go
  tools/mage/logdoc_test.go
Labels: deployment

#960 Custom resources: python analysis set, panther user/settings
  deployments/bootstrap_gateway.yml
  deployments/core.yml
  deployments/master.yml
  deployments/panther_config.yml
  internal/compliance/policy_engine/src/helpers.py
  internal/compliance/policy_engine/tests/test_helpers.py
  internal/core/analysis_api/handlers/create_global.go
  internal/core/custom_resources/resources/analysis_set.go
  internal/core/custom_resources/resources/map.go
  internal/core/custom_resources/resources/panther_settings.go
  internal/core/custom_resources/resources/panther_user.go
  internal/core/custom_resources/resources/s3_bucket_notification.go
  internal/core/custom_resources/resources/self_registration.go
  tools/config/config.go
  tools/mage/deploy.go
  tools/mage/util.go
Labels: deployment
