Repository panther-labs/panther, pull requests merged in 2020-12, with the labels that each got.

#2106 Dynamic Fields Support
  api/lambda/analysis/engine.go
  api/lambda/analysis/models/rules.go
  api/lambda/delivery/models/api.go
  internal/compliance/alert_processor/processor/processor.go
  internal/compliance/policy_engine/src/policy.py
  internal/core/alert_delivery/api/deliver_alert.go
  internal/core/alert_delivery/api/deliver_alert_test.go
  internal/core/alert_delivery/api/dispatch_alerts_test.go
  internal/core/alert_delivery/api/outputs.go
  internal/core/alert_delivery/api/send_test_alert.go
  internal/core/alert_delivery/outputs/asana_test.go
  internal/core/alert_delivery/outputs/custom_webhook_test.go
  internal/core/alert_delivery/outputs/github.go
  internal/core/alert_delivery/outputs/github_test.go
  internal/core/alert_delivery/outputs/jira.go
  internal/core/alert_delivery/outputs/jira_test.go
  internal/core/alert_delivery/outputs/msteams.go
  internal/core/alert_delivery/outputs/opsgenie.go
  internal/core/alert_delivery/outputs/outputs.go
  internal/core/alert_delivery/outputs/outputs_test.go
  internal/core/alert_delivery/outputs/pagerduty_test.go
  internal/core/alert_delivery/outputs/slack.go
  internal/core/alert_delivery/outputs/sns_test.go
  internal/core/alert_delivery/outputs/sqs_test.go
  internal/core/analysis_api/analysis/rule_engine.go
  internal/log_analysis/alert_forwarder/forwarder/forwarder.go
  internal/log_analysis/alert_forwarder/forwarder/forwarder_test.go
  internal/log_analysis/alert_forwarder/forwarder/models.go
  internal/log_analysis/alert_forwarder/forwarder/models_test.go
  internal/log_analysis/alerts_api/api/list_alerts_test.go
  internal/log_analysis/alerts_api/table/list.go
  internal/log_analysis/alerts_api/table/table.go
  internal/log_analysis/alerts_api/utils/utils.go
  internal/log_analysis/rules_engine/src/__init__.py
  internal/log_analysis/rules_engine/src/alert_merger.py
  internal/log_analysis/rules_engine/src/engine.py
  internal/log_analysis/rules_engine/src/main.py
  internal/log_analysis/rules_engine/src/output.py
  internal/log_analysis/rules_engine/src/rule.py
  internal/log_analysis/rules_engine/tests/test_main.py
  internal/log_analysis/rules_engine/tests/test_rule.py
Labels: p1, sync-to-release, team:security engineering

#2171 Fixes Rule Errors threshold and dedup period
  internal/log_analysis/alert_forwarder/forwarder/forwarder.go
  internal/log_analysis/alert_forwarder/forwarder/forwarder_test.go
  internal/log_analysis/rules_engine/src/engine.py
  internal/log_analysis/rules_engine/tests/test_engine.py
Labels: sync-to-release

#2167 Fix uuid validation and case-insensitive filtering
  api/lambda/analysis/models/api.go
  api/lambda/analysis/models/data_models.go
  api/lambda/analysis/models/globals.go
  api/lambda/analysis/models/policies.go
  api/lambda/analysis/models/rules.go
  internal/core/analysis_api/handlers/list.go
  internal/core/analysis_api/handlers/list_data_models.go
  internal/core/analysis_api/handlers/list_policies.go
  internal/core/analysis_api/handlers/list_rules.go
  internal/core/analysis_api/handlers/list_test.go
  internal/core/analysis_api/main/integration_test.go
Labels: bug, sync-to-release

#2143 FE: Refactor Related Destinations
  web/src/components/RelatedDestinations/RelatedDestinations.tsx
  web/src/pages/AlertDetails/AlertDetailsInfo/AlertDetailsInfo.tsx
  web/src/pages/RuleDetails/RuleCardDetails/RuleCardDetails.tsx
Labels: enhancement, team:web

#2182 fix: issue where PR Syncing would close issues from a wrong repo
  build/actions/pr_sync/dist/index.js
  build/actions/pr_sync/index.js
Labels: team:web

#2186 Rename Athena ddb connector namespace and lambda
  deployments/bootstrap_gateway.yml
  internal/compliance/awsglue/awsglue.go
Labels: team:data analytics

#2189 fix: date color on generic item card
  web/src/components/GenericItemCard/GenericItemCard.tsx
  web/src/components/cards/AlertCard/__snapshots__/AlertCard.test.tsx.snap
Labels: team:web

#2175 Add backend support for filtering by multiple severities
  api/graphql/schema.graphql
  api/lambda/analysis/models/policies.go
  api/lambda/analysis/models/rules.go
  internal/core/analysis_api/handlers/list.go
  internal/core/analysis_api/handlers/list_policies.go
  internal/core/analysis_api/handlers/list_rules.go
  internal/core/analysis_api/main/integration_test.go
  web/__generated__/schema.tsx
  web/__tests__/__mocks__/builders.generated.ts
  web/src/pages/ListPolicies/ListPoliciesActions/ListPoliciesActions.tsx
  web/src/pages/ListRules/ListRules.test.tsx
  web/src/pages/ListRules/ListRulesFilters/DropdownFilters.tsx
Labels: team:core infra

#2196 add missing entry to dimensionset
  internal/log_analysis/alert_forwarder/main/lambda.go
Labels: bug, sync-to-release, team:security engineering

#2192 Fix version bugs
  VERSION
  deployments/core.yml
  deployments/master.yml
  deployments/web_server.yml
  internal/core/source_api/api/get_integration_template.go
  tools/mage/build/tools.go
  tools/mage/deploy/deploy.go
  tools/mage/deploy/deploy_template.go
  tools/mage/deploy/frontend.go
  tools/mage/master/build.go
  tools/mage/master/deploy.go
  tools/mage/master/publish.go
  tools/mage/util/version.go
  web/__tests__/.env.test
  web/scripts/start.js
  web/scripts/utils.js
  web/src/components/Navigation/ProfileIcon/ProfileIcon.tsx
  web/src/components/wizards/ComplianceSourceWizard/StackDeploymentPanel/StackDeployment.tsx
  web/src/components/wizards/S3LogSourceWizard/StackDeploymentPanel/StackDeployment.tsx
  web/src/constants.ts
  web/src/helpers/__tests__/analytics.test.tsx
  web/src/helpers/analytics.ts
  web/src/pages/GeneralSettings/GeneralSettings.tsx
  web/src/pages/GeneralSettings/__snapshots__/GeneralSettings.test.tsx.snap
  web/src/pages/Support/__snapshots__/Support.test.tsx.snap
Labels: p0, sync-to-release, team:core infra

#2212 Revert to sequential publishing
  deployments/web_server.yml
  tools/mage/deploy/frontend.go
  tools/mage/master/build.go
  tools/mage/master/deploy.go
  tools/mage/master/publish.go
Labels: mage, sync-to-release, team:core infra

#2220 Update GuardDuty parser to use omit empty on non-required fields
  internal/log_analysis/log_processor/parsers/awslogs/guardduty.go
Labels: sync-to-release, team:data analytics

#2221 Explicitly add Application:Panther tag to Athena workgroup because stack is not applying
  deployments/bootstrap_gateway.yml
Labels: team:data analytics

#2216 [FE] update /web/README.md
  web/README.md
Labels: team:web

#2225 Initial refactor of dynamic fields - cleaned up git commit history
  api/lambda/analysis/engine.go
  api/lambda/analysis/models/rules.go
  api/lambda/delivery/models/api.go
  internal/core/alert_delivery/api/deliver_alert.go
  internal/core/alert_delivery/api/dispatch_alerts.go
  internal/core/alert_delivery/api/outputs.go
  internal/core/alert_delivery/outputs/asana_test.go
  internal/core/alert_delivery/outputs/outputs.go
  internal/core/alert_delivery/outputs/sns_test.go
  internal/core/analysis_api/analysis/rule_engine.go
  internal/log_analysis/alert_forwarder/forwarder/forwarder.go
  internal/log_analysis/alert_forwarder/forwarder/forwarder_test.go
  internal/log_analysis/alert_forwarder/forwarder/models.go
  internal/log_analysis/alert_forwarder/forwarder/models_test.go
  internal/log_analysis/alerts_api/table/table.go
  internal/log_analysis/rules_engine/src/__init__.py
  internal/log_analysis/rules_engine/src/alert_merger.py
  internal/log_analysis/rules_engine/src/engine.py
  internal/log_analysis/rules_engine/src/main.py
  internal/log_analysis/rules_engine/src/output.py
  internal/log_analysis/rules_engine/src/rule.py
  internal/log_analysis/rules_engine/tests/test_main.py
  internal/log_analysis/rules_engine/tests/test_rule.py
Labels: p2, team:security engineering

#2227 Marking some fields as optional
  internal/log_analysis/log_processor/parsers/sophoslogs/central.go
  internal/log_analysis/log_processor/parsers/sophoslogs/testdata/central_tests.yml
Labels: sync-to-release

#2219 Opstool `cost`
  cmd/opstools/cost/cost/main.go
  internal/cost/panther.go
  pkg/awscostexplorer/cost.go
Labels: team:data analytics

#2183 Updated S3 Log Source onboard fields
  api/graphql/schema.graphql
  web/__generated__/schema.tsx
  web/__tests__/__mocks__/builders.generated.ts
  web/src/components/BulletedLogTypeList/BulletedLogTypeList.tsx
  web/src/components/Wizard/Wizard.test.tsx
  web/src/components/Wizard/Wizard.tsx
  web/src/components/Wizard/WizardContext.tsx
  web/src/components/Wizard/WizardPanel.tsx
  web/src/components/buttons/LinkButton/LinkButton.tsx
  web/src/components/wizards/S3LogSourceWizard/S3LogSourceWizard.tsx
  web/src/components/wizards/S3LogSourceWizard/S3SourceConfigurationPanel/S3SourceConfigurationPanel.tsx
  web/src/components/wizards/S3LogSourceWizard/StackDeploymentPanel/StackDeployment.tsx
  web/src/graphql/fragments/S3LogIntegrationDetails.generated.ts
  web/src/graphql/fragments/S3LogIntegrationDetails.graphql
  web/src/pages/CreateLogSource/CreateS3LogSource/CreateS3LogSource.test.tsx
  web/src/pages/CreateLogSource/CreateS3LogSource/CreateS3LogSource.tsx
  web/src/pages/EditS3LogSource/EditS3LogSource.tsx
  web/src/pages/EditS3LogSource/ΕditS3LogSource.test.tsx
  web/src/pages/ListLogSources/LogSourceCards/S3LogSourceCard.test.tsx
  web/src/pages/ListLogSources/LogSourceCards/S3LogSourceCard.tsx
Labels: team:web

#2241 Bump to v1.14.0
  VERSION
Labels: sync-to-release

#2239 [FE]: Backport UTC changes
  package-lock.json
  package.json
  web/src/components/badges/SourceHealthBadge/__snapshots__/SourceHealthBadge.test.tsx.snap
  web/src/components/cards/AlertCard/__snapshots__/AlertCard.test.tsx.snap
  web/src/components/charts/TimeSeriesChart/TimeSeriesChart.tsx
  web/src/components/fields/DateRangeInput/DateRangeInput.test.tsx
  web/src/components/fields/DateRangeInput/DateRangeInput.tsx
  web/src/components/fields/DateRangeInput/__snapshots__/DateRangeInput.test.tsx.snap
  web/src/components/forms/PolicyForm/PolicyFormTestResult/__snapshots__/PolicyFormTestResult.test.tsx.snap
  web/src/components/forms/RuleForm/RuleFormTestResult/__snapshots__/RuleFormTestResult.test.tsx.snap
  web/src/helpers/utils.tsx
  web/src/pages/AlertDetails/AlertDetailsBanner/__snapshots__/AlertDetailsBanner.test.tsx.snap
  web/src/pages/ListAlerts/ListAlerts.test.tsx
  web/src/pages/ListDestinations/DestinationCards/__tests__/__snapshots__/DestinationCard.test.tsx.snap
Labels: team:web

#2233 [FE] Add unified alert filters
  web/src/components/GenericItemCard/GenericItemCard.tsx
  web/src/components/GenericItemCard/__snapshots__/GenericItemCard.test.tsx.snap
  web/src/components/RelatedDestinations/RelatedDestinations.tsx
  web/src/components/cards/AlertCard/PolicyAlertCard/__snapshots__/PolicyAlertCard.test.tsx.snap
  web/src/components/cards/AlertCard/RuleAlertCard/__snapshots__/RuleAlertCard.test.tsx.snap
  web/src/pages/ListAlerts/ListAlertBreadcrumbFilters/ListAlertBreadcrumbFilters.tsx
  web/src/pages/ListAlerts/ListAlertFilters/DropdownFilters.tsx
  web/src/pages/ListAlerts/ListAlerts.test.tsx
  web/src/pages/ListAlerts/ListAlerts.tsx
  web/src/pages/ListRules/ListRules.test.tsx
  web/src/pages/ListRules/ListRulesBreadcrumbFilters/ListRulesBreadcrumbFilters.tsx
Labels: team:web

#2246 Remove AfterTableCreateTime conditional for gluesync (not needed)
  cmd/opstools/gluesync/gluesync/main.go
  internal/log_analysis/datacatalog_updater/datacatalog/sync_database_partitions.go
  internal/log_analysis/gluetasks/sync.go
Labels: team:data analytics

#2256 Change "resource no longer exists" log from Warn() to Debug()
  internal/compliance/resources_api/handlers/delete_resources.go
Labels: team:data analytics

#2269 Updated with commands that can be used to get role names
  deployments/auxiliary/terraform/README.md
Labels: documentation

#2264 [FE] Update Rule Details Banner to latest version
  web/src/pages/RuleDetails/RuleCardDetails/RuleCardDetails.test.tsx
  web/src/pages/RuleDetails/RuleCardDetails/RuleCardDetails.tsx
  web/src/pages/RuleDetails/RuleDetails.test.tsx
  web/src/pages/RuleDetails/RuleDetails.tsx
  web/src/pages/RuleDetails/RuleDetailsBanner/RuleDetailsBanner.test.tsx
  web/src/pages/RuleDetails/RuleDetailsBanner/RuleDetailsBanner.tsx
  web/src/pages/RuleDetails/RuleDetailsBanner/index.tsx
  web/src/pages/RuleDetails/RuleDetailsInfo/RuleDetailsInfo.test.tsx
  web/src/pages/RuleDetails/RuleDetailsInfo/RuleDetailsInfo.tsx
Labels: team:web

#2259 Fixes for S3 Onboarding
  web/src/components/buttons/LinkButton/LinkButton.tsx
  web/src/components/wizards/S3LogSourceWizard/S3SourceConfigurationPanel/S3SourceConfigurationPanel.tsx
  web/src/components/wizards/S3LogSourceWizard/StackDeploymentPanel/StackDeployment.tsx
  web/src/pages/CreateLogSource/CreateS3LogSource/CreateS3LogSource.test.tsx
  web/src/pages/EditS3LogSource/ΕditS3LogSource.test.tsx
Labels: team:web

#2270 Bump web packages based on Snyk reports
  package-lock.json
  package.json
Labels: security, team:web

#2271 security: bump ua-parser-js
  package-lock.json
  package.json
Labels: security, team:web

#2275 Refactor: rename FE component
  web/src/components/BulletedValue/BulletedValue.test.tsx
  web/src/components/BulletedValue/BulletedValue.tsx
  web/src/components/BulletedValue/__snapshots__/BulletedValue.test.tsx.snap
  web/src/components/BulletedValue/index.tsx
  web/src/components/BulletedValueList/BulletedValueList.test.tsx
  web/src/components/BulletedValueList/BulletedValueList.tsx
  web/src/components/BulletedValueList/__snapshots__/BulletedValueList.test.tsx.snap
  web/src/components/BulletedValueList/index.tsx
  web/src/components/cards/AlertCard/PolicyAlertCard/PolicyAlertCard.tsx
  web/src/components/cards/AlertCard/RuleAlertCard/RuleAlertCard.tsx
  web/src/components/cards/RuleCard/RuleCard.tsx
  web/src/pages/AlertDetails/PolicyAlertDetails/AlertDetailsBanner/AlertDetailsBanner.tsx
  web/src/pages/AlertDetails/RuleAlertDetails/AlertDetailsBanner/AlertDetailsBanner.tsx
  web/src/pages/ListLogSources/LogSourceCards/S3LogSourceCard.tsx
  web/src/pages/ListLogSources/LogSourceCards/SqsLogSourceCard.tsx
  web/src/pages/RuleDetails/RuleDetailsBanner/RuleDetailsBanner.tsx
Labels: team:web

#2129 ci: bump bundlesize executor
  .circleci/config.yml
Labels: ci, enhancement

#2281 Alert filtering by title
  internal/log_analysis/alerts_api/table/list.go
Labels: bug

#2245 Generated Alert Fields - FE Support
  api/lambda/alerts/models/api.go
  internal/core/alert_delivery/api/deliver_alert.go
  internal/core/alert_delivery/api/deliver_alert_test.go
  internal/log_analysis/alerts_api/api/api.go
  internal/log_analysis/alerts_api/api/get_alert.go
  internal/log_analysis/alerts_api/api/get_alert_test.go
  internal/log_analysis/alerts_api/api/list_alerts.go
  internal/log_analysis/alerts_api/api/list_alerts_test.go
  internal/log_analysis/alerts_api/api/update_alert_delivery.go
  internal/log_analysis/alerts_api/api/update_alert_delivery_test.go
  internal/log_analysis/alerts_api/api/update_alert_status.go
  internal/log_analysis/alerts_api/api/update_alert_status_test.go
  internal/log_analysis/alerts_api/table/get_alert_test.go
  internal/log_analysis/alerts_api/table/table.go
  internal/log_analysis/alerts_api/utils/utils.go
  internal/log_analysis/alerts_api/utils/utils_test.go
Labels: p0, team:security engineering

#2293 fix: return alertId when generating the URL
  internal/core/alert_delivery/outputs/asana_test.go
  internal/core/alert_delivery/outputs/custom_webhook_test.go
  internal/core/alert_delivery/outputs/github_test.go
  internal/core/alert_delivery/outputs/jira_test.go
  internal/core/alert_delivery/outputs/msteams.go
  internal/core/alert_delivery/outputs/msteams_test.go
  internal/core/alert_delivery/outputs/opsgenie_test.go
  internal/core/alert_delivery/outputs/outputs.go
  internal/core/alert_delivery/outputs/outputs_test.go
  internal/core/alert_delivery/outputs/pagerduty_test.go
  internal/core/alert_delivery/outputs/slack_test.go
  internal/core/alert_delivery/outputs/sns_test.go
  internal/core/alert_delivery/outputs/sqs_test.go
Labels: team:core infra

#2308 fix: correct deep merging on alert's events
  web/src/pages/AlertDetails/RuleAlertDetails/RuleAlertDetails.tsx
Labels: bug, p0, team:web

#2309 Use string slice for PantherAnyString
  internal/log_analysis/log_processor/pantherlog/result_test.go
  internal/log_analysis/log_processor/parsers/awslogs/extractor_test.go
  internal/log_analysis/log_processor/parsers/awslogs/pantherlog.go
  internal/log_analysis/log_processor/parsers/awslogs/pantherlog_test.go
  internal/log_analysis/log_processor/parsers/pantherlog.go
  internal/log_analysis/log_processor/parsers/pantherlog_test.go
Labels: sync-to-release

#2307 Parallelize alert s3select
  api/lambda/alerts/models/api.go
  deployments/log_analysis.yml
  internal/log_analysis/alerts_api/api/api.go
  internal/log_analysis/alerts_api/api/get_alert.go
  internal/log_analysis/alerts_api/api/get_alert_test.go
  internal/log_analysis/alerts_api/api/list_alerts_test.go
  internal/log_analysis/alerts_api/api/s3_search.go
  internal/log_analysis/alerts_api/api/s3select_query.go
  internal/log_analysis/alerts_api/api/update_alert_delivery_test.go
  internal/log_analysis/alerts_api/api/update_alert_status_test.go
  internal/log_analysis/alerts_api/api/utils_test.go
  package-lock.json
  pkg/testutils/awsmocks.go
Labels: sync-to-release, team:data analytics

#2314 Bump VERSION to 1.14.3
  VERSION
Labels: sync-to-release

#2321 Add cloud_security and rule_errors to log subscription permissions
  deployments/bootstrap.yml
Labels: enterprise-backport
