Repository panther-labs/panther, pull requests merged in 2021-02, with the labels that each got.

#2475 Crowdstrike parsers: Insight special raw & Discover processed events
  internal/log_analysis/log_processor/parsers/crowdstrikelogs/crowdstrikelogs.go
  internal/log_analysis/log_processor/parsers/crowdstrikelogs/discover_processed_events.go
  internal/log_analysis/log_processor/parsers/crowdstrikelogs/discover_processed_events_test.go
  internal/log_analysis/log_processor/parsers/crowdstrikelogs/insight_raw_events.go
  internal/log_analysis/log_processor/parsers/crowdstrikelogs/insight_raw_events_test.go
  internal/log_analysis/log_processor/parsers/crowdstrikelogs/testdata/discover_processed_events.yml
  internal/log_analysis/log_processor/parsers/crowdstrikelogs/testdata/insight_raw_events.yml
Labels: data inputs, team:data processing

#2458 CrowdStrike parsers: UserIdentity & GroupIdentity
  internal/log_analysis/log_processor/parsers/crowdstrikelogs/crowdstrikelogs.go
  internal/log_analysis/log_processor/parsers/crowdstrikelogs/crowdstrikelogs_test.go
  internal/log_analysis/log_processor/parsers/crowdstrikelogs/identity.go
  internal/log_analysis/log_processor/parsers/crowdstrikelogs/identity_test.go
  internal/log_analysis/log_processor/parsers/crowdstrikelogs/testdata/identity.yml
  internal/log_analysis/log_processor/parsers/crowdstrikelogs/unknown.go
Labels: data inputs, team:data processing

#2568 Minor tool fixes
  cmd/devtools/filegen/fields.go
  cmd/devtools/filegen/filegen/main.go
  cmd/devtools/filegen/logtype/aws_serveraccess.go
  cmd/opstools/s3queue/s3queue/main.go
Labels: team:data analytics

#2577 Fix alert s3select paging bug
  internal/log_analysis/alerts_api/api/get_alert_test.go
  internal/log_analysis/alerts_api/api/s3select_query.go
Labels: bug, sync-to-release

#2594 [FE][BUGFIX] Remove stale appsync resolvers
  deployments/appsync.yml
Labels: bug, enterprise-backport

#2549 RegionIgnoreListError TypeAssertionError
  internal/compliance/snapshot_poller/pollers/aws/poll.go
  internal/compliance/snapshot_poller/pollers/aws/poll_test.go
  internal/compliance/snapshot_poller/pollers/aws/s3_bucket_test.go
Labels: bug, sync-to-release

#2600 bugfix: check for lb type
  internal/compliance/snapshot_poller/pollers/aws/awstest/elbv2.go
  internal/compliance/snapshot_poller/pollers/aws/elbv2_application_load_balancer.go
  internal/compliance/snapshot_poller/pollers/aws/elbv2_application_load_balancer_test.go
Labels: bug, team:security engineering

#2602 Dynamic partition/url suffix references in cfn
  deployments/auxiliary/cloudformation/osquery-firehose.yml
  deployments/auxiliary/cloudformation/panther-deployment-role.yml
  deployments/auxiliary/cloudformation/panther-log-analysis-iam.yml
  deployments/auxiliary/terraform/panther_deployment_role/main.tf
  deployments/bootstrap.yml
  deployments/bootstrap_gateway.yml
  deployments/core.yml
  deployments/log_analysis.yml
  deployments/web_server.yml
  internal/core/source_api/api/testdata/panther-log-analysis-iam-updated.yml
Labels: deployment, team:core infra

#2524 Replace sam-cli with our own packaging
  .gitignore
  VERSION
  deployments/auxiliary/terraform/osquery_firehose/main.tf
  deployments/bootstrap_gateway.yml
  deployments/cloud_security.yml
  deployments/core.yml
  deployments/dashboards.yml
  deployments/dev.yml
  deployments/log_analysis.yml
  deployments/root.yml
  deployments/web_server.yml
  go.mod
  go.sum
  magefile.go
  pkg/shutil/archive.go
  requirements-top-level.txt
  requirements.txt
  tools/mage/build/lambda.go
  tools/mage/build/schemas.go
  tools/mage/build/tools.go
  tools/mage/clean/clean.go
  tools/mage/clients/aws.go
  tools/mage/deploy/config.go
  tools/mage/deploy/deploy.go
  tools/mage/deploy/frontend.go
  tools/mage/deploy/template.go
  tools/mage/gen/gen.go
  tools/mage/master/build.go
  tools/mage/master/config.go
  tools/mage/master/deploy.go
  tools/mage/master/publish.go
  tools/mage/pkg/docker.go
  tools/mage/pkg/pkg.go
  tools/mage/setup/setup.go
  tools/mage/teardown/s3.go
  tools/mage/test/cfn.go
  tools/mage/util/aws.go
  tools/mage/util/cfnparse.go
  tools/mage/util/files.go
  tools/mage/util/run.go
  tools/mage/util/s3.go
  tools/mage/util/task.go
Labels: mage, team:core infra

#2585 Wrong type for AIDMaster.PointerSize field
  cmd/devtools/pantherlog/pantherlog/main.go
  internal/log_analysis/log_processor/parsers/crowdstrikelogs/insight_raw_events.go
  internal/log_analysis/log_processor/parsers/crowdstrikelogs/testdata/insight_raw_events.yml
Labels: team:data processing

#2603 [FE][Feat] Allow any type of item in Selection.Context
  web/src/components/cards/AlertCard/PolicyAlertCard/PolicyAlertCard.tsx
  web/src/components/cards/AlertCard/RuleAlertCard/RuleAlertCard.tsx
  web/src/components/utils/SelectContext/SelectAllCheckbox.tsx
  web/src/components/utils/SelectContext/SelectCheckbox.tsx
  web/src/components/utils/SelectContext/SelectContext.test.tsx
  web/src/components/utils/SelectContext/SelectContext.tsx
  web/src/components/utils/SelectContext/index.tsx
  web/src/pages/ListAlerts/ListAlerts.test.tsx
  web/src/pages/ListAlerts/ListAlerts.tsx
  web/src/pages/RuleDetails/RuleAlertsListing/RuleAlertsListing.tsx
  web/src/pages/RuleDetails/RuleDetails.test.tsx
Labels: enhancement, team:web

#2557 [FE][BUGFIX]: Prevent crashing when a destination override has been deleted
  web/src/hooks/__tests__/useDetectionDestinations.test.tsx
  web/src/hooks/useDetectionDestinations.tsx
Labels: bug, p1

#2460 [FE]: Fallback to `id` when Data Model display name is not present
  web/src/components/forms/DataModelForm/DataModelForm.tsx
  web/src/pages/ListDataModels/DataModelCard/DataModelCard.test.tsx
  web/src/pages/ListDataModels/DataModelCard/DataModelCard.tsx
  web/src/pages/ListDataModels/DataModelCard/__snapshots__/DataModelCard.test.tsx.snap
Labels: bug, team:web

#2607 fix: Autosave to skip submit when mounting
  web/src/components/utils/Autosave/Autosave.tsx
Labels: bug, team:web

#2571 [FE]: Compliance Source Additional configuration fields
  api/graphql/schema.graphql
  internal/core/source_api/api/utils.go
  web/__generated__/schema.tsx
  web/__tests__/__mocks__/builders.generated.ts
  web/src/components/wizards/ComplianceSourceWizard/ComplianceSourceWizard.tsx
  web/src/components/wizards/ComplianceSourceWizard/SourceConfigurationPanel/SourceConfigurationPanel.tsx
  web/src/constants.ts
  web/src/graphql/fragments/ComplianceIntegrationDetails.generated.ts
  web/src/graphql/fragments/ComplianceIntegrationDetails.graphql
  web/src/pages/CreateComplianceSource/CreateComplianceSource.test.tsx
  web/src/pages/CreateComplianceSource/CreateComplianceSource.tsx
  web/src/pages/EditComplianceSource/EditComplianceSource.tsx
  web/src/pages/EditComplianceSource/ΕditComplianceSource.test.tsx
Labels: team:web

#2613 Updating GCP Audit logs
  internal/log_analysis/log_processor/parsers/gcplogs/auditlog.go
  internal/log_analysis/log_processor/parsers/gcplogs/auditlog_test.go
  internal/log_analysis/log_processor/parsers/gcplogs/gcplogs.go
Labels: sync-to-release

#2612 Minor cleanup for new pkg code
  deployments/cloud_security.yml
  deployments/core.yml
  deployments/log_analysis.yml
  deployments/web_server.yml
  tools/mage/deploy/deploy.go
  tools/mage/pkg/pkg.go
  tools/mage/test/cfn.go
Labels: team:core infra

#2620 on call: update ignore list
  internal/compliance/aws_event_processor/processor/process.go
Labels: team:security engineering

#2548 ResourceType and LogType validations for policies, roles, and datamodels
  deployments/core.yml
  internal/compliance/snapshot_poller/models/aws/resource_types.go
  internal/compliance/snapshot_poller/pollers/aws/poll.go
  internal/core/analysis_api/handlers/bulk_upload.go
  internal/core/analysis_api/handlers/clients.go
  internal/core/analysis_api/handlers/create_update_datamodel.go
  internal/core/analysis_api/handlers/create_update_policy.go
  internal/core/analysis_api/handlers/create_update_rule.go
  internal/core/analysis_api/handlers/validation.go
  internal/core/analysis_api/main/bulk_test_resources/datamodel_invalid_logtype/sample_data_model.yml
  internal/core/analysis_api/main/bulk_test_resources/policy_invalid_resourcetype/policy_invalid_resource_types.json
  internal/core/analysis_api/main/bulk_test_resources/policy_invalid_resourcetype/policy_invalid_resource_types.py
  internal/core/analysis_api/main/bulk_test_resources/policy_invalid_resourcetype/policy_invalid_resource_types.yml
  internal/core/analysis_api/main/bulk_test_resources/rule_invalid_logtype/rule_invalid_logtype.py
  internal/core/analysis_api/main/bulk_test_resources/rule_invalid_logtype/rule_invalid_logtype.yml
  internal/core/analysis_api/main/bulk_test_resources/test_analyses/policy_always_true.json
  internal/core/analysis_api/main/bulk_test_resources/test_analyses/policy_always_true.py
  internal/core/analysis_api/main/bulk_test_resources/test_analyses/policy_always_true.yml
  internal/core/analysis_api/main/bulk_test_resources/test_analyses/policy_aws_cloudtrail_log_validation_enabled.py
  internal/core/analysis_api/main/bulk_test_resources/test_analyses/policy_aws_cloudtrail_log_validation_enabled.yml
  internal/core/analysis_api/main/bulk_test_resources/test_analyses/rule_always_true.py
  internal/core/analysis_api/main/bulk_test_resources/test_analyses/rule_always_true.yml
  internal/core/analysis_api/main/bulk_test_resources/test_analyses/sample_data_model.yml
  internal/core/analysis_api/main/integration_test.go
Labels: team:core infra

#2623 Resources timeout fixes
  deployments/cloud_security.yml
  deployments/root.yml
  internal/compliance/resource_processor/processor/resources_api.go
  internal/compliance/resources_api/handlers/clients.go
  internal/compliance/resources_api/handlers/compliance.go
  internal/compliance/resources_api/handlers/dynamo.go
  internal/compliance/resources_api/handlers/list_resources.go
  tools/mage/deploy/deploy.go
Labels: bug, cloud security, team:security engineering

#2636 Fix mage deploy
  tools/mage/deploy/deploy.go
Labels: bug

#2638 Use Athena2 when possible
  deployments/bootstrap_gateway.yml
  go.mod
  go.sum
  internal/core/custom_resources/resources/glue_tables.go
Labels: team:data analytics

#2634 [FE] Feat Mass Actions on Detections
  api/graphql/schema.graphql
  deployments/appsync.yml
  web/__generated__/schema.tsx
  web/__tests__/__mocks__/builders.generated.ts
  web/src/components/GenericItemCard/GenericItemCard.tsx
  web/src/components/GenericItemCard/__snapshots__/GenericItemCard.test.tsx.snap
  web/src/components/cards/AlertCard/PolicyAlertCard/__snapshots__/PolicyAlertCard.test.tsx.snap
  web/src/components/cards/AlertCard/RuleAlertCard/__snapshots__/RuleAlertCard.test.tsx.snap
  web/src/components/cards/PolicyCard/PolicyCard.test.tsx
  web/src/components/cards/PolicyCard/PolicyCard.tsx
  web/src/components/cards/PolicyCard/PolicyCardOptions/PolicyCardOptions.tsx
  web/src/components/cards/RuleCard/RuleCard.test.tsx
  web/src/components/cards/RuleCard/RuleCard.tsx
  web/src/components/cards/RuleCard/RuleCardOptions/RuleCardOptions.tsx
  web/src/components/modals/ConfirmModal/ConfirmModal.tsx
  web/src/components/modals/DeleteDetectionsModal/DeleteDetectionsModal.tsx
  web/src/components/modals/DeleteDetectionsModal/graphql/deleteDetections.generated.ts
  web/src/components/modals/DeleteDetectionsModal/graphql/deleteDetections.graphql
  web/src/components/modals/DeleteDetectionsModal/index.tsx
  web/src/components/modals/DeletePolicyModal/DeletePolicyModal.tsx
  web/src/components/modals/DeletePolicyModal/graphql/deletePolicy.graphql
  web/src/components/modals/DeleteRuleModal/DeleteRuleModal.tsx
  web/src/components/modals/DeleteRuleModal/graphql/deleteRule.generated.ts
  web/src/components/modals/DeleteRuleModal/graphql/deleteRule.graphql
  web/src/components/modals/OptimisticConfirmModal/OptimisticConfirmModal.tsx
  web/src/components/utils/Modal/ModalContext.tsx
  web/src/components/utils/Modal/ModalManager.tsx
  web/src/components/utils/SelectContext/SelectContext.tsx
  web/src/helpers/analytics.ts
  web/src/pages/CreateDetection/CreatePolicy/CreatePolicy.test.tsx
  web/src/pages/CreateDetection/CreatePolicy/CreatePolicy.tsx
  web/src/pages/CreateDetection/CreateRule/CreateRule.test.tsx
  web/src/pages/CreateDetection/CreateRule/CreateRule.tsx
  web/src/pages/ListCustomLogs/CustomLogCard/__snapshots__/CustomLogCard.test.tsx.snap
  web/src/pages/ListDataModels/DataModelCard/__snapshots__/DataModelCard.test.tsx.snap
  web/src/pages/ListDestinations/DestinationCards/__tests__/__snapshots__/DestinationCard.test.tsx.snap
  web/src/pages/ListDetections/ListDetections.test.tsx
  web/src/pages/ListDetections/ListDetections.tsx
  web/src/pages/ListDetections/ListDetectionsActions/ListDetectionsActions.tsx
  web/src/pages/ListDetections/ListDetectionsActions/ListDetectionsFilters/DropdownFilters.tsx
  web/src/pages/ListDetections/ListDetectionsActions/ListDetectionsFilters/ListDetectionsFilters.test.tsx
  web/src/pages/ListDetections/ListDetectionsActions/ListDetectionsFilters/ListDetectionsFilters.tsx
  web/src/pages/ListDetections/ListDetectionsActions/ListDetectionsFilters/__snapshots__/ListDetectionsFilters.test.tsx.snap
  web/src/pages/ListDetections/ListDetectionsActions/ListDetectionsFilters/index.tsx
  web/src/pages/ListDetections/ListDetectionsActions/ListDetectionsSelection/ListDetectionsSelection.tsx
  web/src/pages/ListDetections/ListDetectionsActions/ListDetectionsSelection/index.tsx
  web/src/pages/ListDetections/ListDetectionsActions/index.tsx
  web/src/pages/PolicyDetails/PolicyDetailsBanner/PolicyDetailsBanner.tsx
  web/src/pages/RuleDetails/RuleDetailsBanner/RuleDetailsBanner.tsx
Labels: enhancement, team:web

#2648 Enable zip compression for packaged binaries
  pkg/shutil/archive.go
Labels: deployment, team:core infra

#2647 Allow Python engine assume roles / managed policy attachment
  deployments/cloud_security.yml
  deployments/log_analysis.yml
  deployments/panther_config.yml
  deployments/root.yml
  tools/mage/deploy/config.go
  tools/mage/deploy/deploy.go
Labels: team:core infra

#2561 Panther Rules Engine Cross Account IAM Permissions CFNS
  deployments/auxiliary/cloudformation/panther-rules-engine-cross-account-read-only.yml
Labels: team:security engineering

#2670 Add default value for PythonManagedPolicyArn
  deployments/root.yml
Labels: bug, team:core infra

#2673 String join the role arns list to fix root stack
  deployments/root.yml
Labels: bug, team:core infra

#2659 Display the Panther-created SNS topic when an s3 source is deleted
  api/graphql/schema.graphql
  internal/core/source_api/api/managed_bucket_notifications.go
  internal/core/source_api/api/put_integration.go
  web/__generated__/schema.tsx
  web/__tests__/__mocks__/builders.generated.ts
  web/src/graphql/fragments/S3LogIntegrationDetails.generated.ts
  web/src/graphql/fragments/S3LogIntegrationDetails.graphql
  web/src/pages/ListLogSources/LogSourceCards/LogSourceCardOptions.tsx
Labels: sync-to-release

#2629 Simplify SchemaDatabase interface
  api/lambda/logtypes/models_gen.go
  internal/core/logtypesapi/api.go
  internal/core/logtypesapi/available_test.go
  internal/core/logtypesapi/customlogs.go
  internal/core/logtypesapi/customlogs_test.go
  internal/core/logtypesapi/dynamodb.go
  internal/core/logtypesapi/inmem.go
  internal/core/logtypesapi/managed_schemas.go
  internal/core/logtypesapi/managed_schemas_test.go
  internal/core/logtypesapi/resolver.go
  internal/core/logtypesapi/schemas.go
  internal/core/logtypesapi/transact/transact.go
  internal/log_analysis/managedschemas/github.go
  internal/log_analysis/managedschemas/github_test.go
  internal/log_analysis/managedschemas/managedschemas.go
Labels: sync-to-release

#2675 Deleting an s3 source succeeds even if the iam role was deleted
  internal/core/source_api/api/delete_integration.go
Labels: sync-to-release

#2683 Fixing dashboards
  internal/log_analysis/log_processor/destinations/s3.go
  internal/log_analysis/log_processor/destinations/s3_test.go
  internal/log_analysis/log_processor/metrics/metrics.go
Labels: sync-to-release

#2630 Add deep copying methods to the immutable types interface
  internal/log_analysis/rules_engine/src/immutable.py
  internal/log_analysis/rules_engine/tests/test_immutable.py
Labels: sync-to-release, team:data processing

#2690 Fixing dashboards
  deployments/dashboards.yml
  tools/mage/gen/dashboards/log_processing.go
Labels: sync-to-release

#2656 [FE] S3 onboarding with healthchecks
  web/src/assets/icons/warning.svg
  web/src/components/wizards/S3LogSourceWizard/ValidationPanel/HealthCheckPanel.tsx
  web/src/components/wizards/S3LogSourceWizard/ValidationPanel/HealthCheckWarning.tsx
  web/src/components/wizards/S3LogSourceWizard/ValidationPanel/ValidationPanel.tsx
  web/src/pages/CreateLogSource/CreateS3LogSource/CreateS3LogSource.test.tsx
  web/src/pages/EditS3LogSource/ΕditS3LogSource.test.tsx
Labels: sync-to-release, team:web

#2688 Misc fixes and feedback on pack api
  internal/core/analysis_api/handlers/dynamo.go
  internal/core/analysis_api/handlers/github.go
  internal/core/analysis_api/handlers/update_pack.go
  internal/core/analysis_api/handlers/update_pack_test.go
  internal/core/analysis_api/main/integration_test.go
  pkg/github/github.go
Labels: team:security engineering

#2684 Add healthcheck for bucket notifications configuration
  api/graphql/schema.graphql
  api/lambda/source/models/api.go
  api/lambda/source/models/integration.go
  deployments/appsync.yml
  internal/core/source_api/api/check_integration.go
  internal/core/source_api/api/managed_bucket_notifications.go
  web/__generated__/schema.tsx
  web/__tests__/__mocks__/builders.generated.ts
  web/src/graphql/fragments/S3LogIntegrationDetails.generated.ts
  web/src/graphql/fragments/S3LogIntegrationDetails.graphql
  web/src/pages/CreateLogSource/CreateS3LogSource/CreateS3LogSource.test.tsx
  web/src/pages/EditS3LogSource/ΕditS3LogSource.test.tsx
  web/src/pages/ListLogSources/LogSourceCards/LogSourceCard.tsx
Labels: sync-to-release, team:data processing

#2611 OPSTOOL: Flush panther-resources table items where deleted=true
  cmd/opstools/flushrsc/flushrsc/main.go
Labels: team:core infra

#2703 Make sure we don't serialize invalid JSON
  internal/log_analysis/log_processor/pantherlog/jsoniter.go
  internal/log_analysis/log_processor/pantherlog/jsoniter_test.go
Labels: sync-to-release

#2712 Ignore some verbose logs
  internal/compliance/aws_event_processor/processor/accounts.go
  internal/compliance/aws_event_processor/processor/process.go
Labels: bug, sync-to-release

#2710 Managed notifications multiple sources same bucket
  api/graphql/schema.graphql
  api/lambda/source/models/integration.go
  internal/core/source_api/api/check_integration.go
  internal/core/source_api/api/delete_integration.go
  internal/core/source_api/api/list_integrations.go
  internal/core/source_api/api/managed_bucket_notifications.go
  internal/core/source_api/api/managed_bucket_notifications_test.go
  internal/core/source_api/api/put_integration.go
  internal/core/source_api/api/update_integration.go
  internal/core/source_api/api/update_integration_test.go
  internal/core/source_api/api/utils.go
  internal/core/source_api/ddb/items.go
  internal/core/source_api/ddb/scan.go
  web/__generated__/schema.tsx
  web/__tests__/__mocks__/builders.generated.ts
  web/src/graphql/fragments/S3LogIntegrationDetails.generated.ts
  web/src/graphql/fragments/S3LogIntegrationDetails.graphql
  web/src/pages/ListLogSources/LogSourceCards/LogSourceCardOptions.tsx
Labels: sync-to-release, team:data processing

#2715 Fixing integration tests
  internal/core/metrics_api/api/log_processor_metrics.go
Labels: sync-to-release

#2718 Fix flaky test
  internal/core/source_api/api/managed_bucket_notifications_test.go
Labels: sync-to-release

#2699 Weyland destinations lookup
  api/lambda/outputs/models/api.go
  deployments/log_analysis.yml
  internal/log_analysis/alert_forwarder/forwarder/forwarder.go
  internal/log_analysis/rules_engine/src/destination.py
  internal/log_analysis/rules_engine/src/engine.py
  internal/log_analysis/rules_engine/src/main.py
  internal/log_analysis/rules_engine/src/outputs_api.py
  internal/log_analysis/rules_engine/src/rule.py
  internal/log_analysis/rules_engine/tests/test_destination.py
  internal/log_analysis/rules_engine/tests/test_engine.py
  internal/log_analysis/rules_engine/tests/test_main.py
  internal/log_analysis/rules_engine/tests/test_rule.py
Labels: enhancement

#2720 Fix bug in cloud security scanning when a region ignore list is configured
  internal/compliance/snapshot_poller/pollers/aws/cloudtrail.go
  internal/compliance/snapshot_poller/pollers/aws/configservice.go
  internal/compliance/snapshot_poller/pollers/aws/guardduty_detector.go
Labels: sync-to-release
