Repository panther-labs/panther, pull requests merged in 2021-03, with the labels that each got.

#2724 Fix resources-table scanning bug
  internal/compliance/resources_api/handlers/dynamo.go
Labels: bug, sync-to-release

#2722 Release 1.16 partition migration for the datacatalog-updater
  internal/log_analysis/datacatalog_updater/main/lambda.go
Labels: bug, sync-to-release, team:data analytics

#2728 Check all logtypes for partitions needing updating
  internal/log_analysis/datacatalog_updater/datacatalog/s3.go
  internal/log_analysis/datacatalog_updater/main/lambda.go
Labels: bug, sync-to-release

#2731 Handled glue index issue
  internal/log_analysis/datacatalog_updater/datacatalog/create_tables.go
Labels: bug, sync-to-release

#2730 Allow CloudTrail notifications to process
  internal/log_analysis/log_processor/common/common.go
  internal/log_analysis/log_processor/processor/processor.go
  internal/log_analysis/log_processor/sources/s3.go
  internal/log_analysis/log_processor/sources/s3_test.go
Labels: bug, sync-to-release

#2735 More glue index related changes
  internal/log_analysis/datacatalog_updater/datacatalog/create_tables.go
Labels: bug, sync-to-release, team:data analytics

#2737 Glue partition fix redux
  internal/log_analysis/awsglue/table_metadata.go
  internal/log_analysis/datacatalog_updater/main/lambda.go
Labels: bug, sync-to-release, team:data analytics

#2740 chore: version bump
  VERSION
Labels: sync-to-release

#2743 Fix not found err check
  tools/mage/master/publish.go
Labels: bug, sync-to-release
