Repository panther-labs/panther, pull requests merged in 2021-01, with the labels that each got.

#2329 Add -files-per-second and -duration flags to opstool s3queue
  cmd/opstools/s3list/s3list.go
  cmd/opstools/s3queue/integration_test.go
  cmd/opstools/s3queue/s3queue.go
  cmd/opstools/s3queue/s3queue/main.go
  cmd/opstools/s3queue/s3queue_test.go
  cmd/opstools/s3sns/s3sns.go
  cmd/opstools/s3sns/s3sns/main.go
  pkg/testutils/awsmocks.go
Labels: team:data analytics

#2333 fix: issue with bash echo command
  .circleci/config.yml
Labels: ci

#2312 [FE] add `variantBorderStyle` to maintain proper `IconButton` styling
  package-lock.json
  package.json
  web/src/components/GenericItemCard/GenericItemCard.tsx
  web/src/components/cards/AlertCard/PolicyAlertCard/__snapshots__/PolicyAlertCard.test.tsx.snap
  web/src/components/cards/AlertCard/RuleAlertCard/__snapshots__/RuleAlertCard.test.tsx.snap
  web/src/components/dropdowns/UpdateAlertDropdown/UpdateAlertDropdown.tsx
  web/src/components/fields/DateRangeInput/__snapshots__/DateRangeInput.test.tsx.snap
  web/src/components/forms/BaseRuleForm/BaseRuleFormEditorSection/BaseRuleFormEditorSection.tsx
  web/src/components/utils/TableControls/TableControlsPagination.tsx
  web/src/components/wizards/S3LogSourceWizard/S3SourceConfigurationPanel/S3SourceConfigurationPanel.tsx
  web/src/pages/AlertDetails/PolicyAlertDetails/AlertDetailsBanner/__snapshots__/AlertDetailsBanner.test.tsx.snap
  web/src/pages/AlertDetails/RuleAlertDetails/AlertDetailsBanner/__snapshots__/AlertDetailsBanner.test.tsx.snap
  web/src/pages/AlertDetails/common/AlertDeliverySection/AlertDeliveryTable/AlertDeliveryTable.tsx
  web/src/pages/ListCustomLogs/CustomLogCard/__snapshots__/CustomLogCard.test.tsx.snap
  web/src/pages/ListDestinations/DestinationCards/__tests__/__snapshots__/DestinationCard.test.tsx.snap
  web/src/pages/ListGlobalPythonModules/GlobalPythonModuleItem/GlobalPythonModuleItem.tsx
  web/src/pages/ListPolicies/ListPoliciesTable/ListPoliciesTableRowOptions/ListPoliciesTableRowOptions.tsx
  web/src/pages/PolicyDetails/PolicyDetailsTable/PolicyDetailsTableRowOptions.tsx
  web/src/pages/ResourceDetails/ResourceDetailsAttributes/ResourceDetailsAttributes.tsx
  web/src/pages/ResourceDetails/ResourceDetailsTable/ResourceDetailsTableRowOptions.tsx
  web/src/pages/Users/ListUsersTable/ListUsersTableRowOptions/ListUsersTableRowOptions.tsx
Labels: enhancement, team:web

#2343 fix: axios issue from AWS Amplify
  package-lock.json
  package.json
Labels: security, team:web

#2346 Configurable root stack params and other small fixes
  deployments/auxiliary/cloudformation/panther-deployment-role.yml
  deployments/auxiliary/terraform/README.md
  deployments/auxiliary/terraform/panther_cloudwatch_events/panther_sns_topic_subscription.tf
  deployments/auxiliary/terraform/panther_cloudwatch_events/variables.tf
  deployments/auxiliary/terraform/panther_deployment_role/main.tf
  deployments/auxiliary/terraform/panther_log_processing_notifications/variables.tf
  deployments/bootstrap_gateway.yml
  tools/mage/master/deploy.go
Labels: team:core infra

#2349 Removing unused CW dashboards
  deployments/dashboards.yml
  tools/mage/gen/dashboards/alerts.go
  tools/mage/gen/dashboards/dashboards.go
  tools/mage/gen/dashboards/infra.go
  tools/mage/gen/dashboards/overview.go
  tools/mage/gen/dashboards/remediation.go
Labels: team:core infra

#2339 Deploy with existing subnets
  deployments/bootstrap.yml
  deployments/master.yml
  deployments/panther_config.yml
  deployments/web_server.yml
  tools/mage/deploy/config.go
  tools/mage/deploy/deploy.go
Labels: deployment, security-feature

#2348 Small changes from testing in Panther Enterprise
  internal/log_analysis/athenaviews/athenaviews.go
  internal/log_analysis/datacatalog_updater/datacatalog/handler.go
  internal/log_analysis/datacatalog_updater/datacatalog/sync_database.go
  internal/log_analysis/datacatalog_updater/main/lambda.go
  internal/log_analysis/log_processor/pantherlog/scanners_aws.go
Labels: enterprise-backport

#2345 Data Models [1/4]: Allow Data Model creation
  api/graphql/schema.graphql
  deployments/appsync.yml
  web/__generated__/schema.tsx
  web/__tests__/__mocks__/builders.generated.ts
  web/src/components/Editor/Editor.tsx
  web/src/components/Editor/theme.ts
  web/src/components/forms/DataModelForm/DataModelForm.test.tsx
  web/src/components/forms/DataModelForm/DataModelForm.tsx
  web/src/components/forms/DataModelForm/index.tsx
  web/src/graphql/fragments/DataModelFull.generated.ts
  web/src/graphql/fragments/DataModelFull.graphql
  web/src/helpers/analytics.ts
  web/src/pages/CreateDataModel/CreateDataModel.test.tsx
  web/src/pages/CreateDataModel/CreateDataModel.tsx
  web/src/pages/CreateDataModel/graphql/createDataModel.generated.ts
  web/src/pages/CreateDataModel/graphql/createDataModel.graphql
  web/src/pages/CreateDataModel/index.tsx
  web/src/routes.tsx
  web/src/urls.ts
Labels: team:web

#2359 Creating immutable events
  internal/log_analysis/rules_engine/src/engine.py
  internal/log_analysis/rules_engine/src/enriched_event.py
  internal/log_analysis/rules_engine/src/immutable.py
  internal/log_analysis/rules_engine/tests/test_engine.py
  internal/log_analysis/rules_engine/tests/test_enriched_event.py
  internal/log_analysis/rules_engine/tests/test_immutable.py
  internal/log_analysis/rules_engine/tests/test_main.py
Labels: sync-to-release

#2370 Add -loop s3queue
  cmd/opstools/s3list/s3list.go
  cmd/opstools/s3queue/s3queue.go
  cmd/opstools/s3queue/s3queue/main.go
Labels: team:data analytics

#2361 Cloud Security - Sources API & Snapshot Poller - Filtering and Blacklisting
  api/lambda/source/models/api.go
  api/lambda/source/models/integration.go
  deployments/cloud_security.yml
  internal/compliance/aws_event_processor/processor/handler.go
  internal/compliance/snapshot_poller/models/aws/types.go
  internal/compliance/snapshot_poller/models/poller/poller.go
  internal/compliance/snapshot_poller/pollers/aws/clients.go
  internal/compliance/snapshot_poller/pollers/aws/configservice.go
  internal/compliance/snapshot_poller/pollers/aws/configservice_test.go
  internal/compliance/snapshot_poller/pollers/aws/eks_cluster.go
  internal/compliance/snapshot_poller/pollers/aws/eks_cluster_test.go
  internal/compliance/snapshot_poller/pollers/aws/guardduty_detector.go
  internal/compliance/snapshot_poller/pollers/aws/guardduty_detector_test.go
  internal/compliance/snapshot_poller/pollers/aws/password_policy.go
  internal/compliance/snapshot_poller/pollers/aws/poll.go
  internal/compliance/snapshot_poller/pollers/aws/s3_bucket.go
  internal/compliance/snapshot_poller/pollers/lambda_test.go
  internal/compliance/snapshot_scheduler/scheduler/schedule.go
  internal/compliance/snapshot_scheduler/scheduler/schedule_test.go
  internal/core/custom_resources/resources/self_registration.go
  internal/core/source_api/api/put_integration.go
  internal/core/source_api/api/update_integration.go
  internal/core/source_api/api/utils.go
  internal/core/source_api/ddb/items.go
Labels: sync-to-release

#2387 Fix teardown: run in stages
  tools/mage/teardown/cfn.go
Labels: bug, sync-to-release, team:core infra

#2366 Data Models [3/4]: Data Model Listing & Deletion
  api/graphql/schema.graphql
  deployments/appsync.yml
  package-lock.json
  package.json
  web/__generated__/schema.tsx
  web/__tests__/__mocks__/builders.generated.ts
  web/src/apollo/typePolicies.ts
  web/src/components/Navigation/SecondaryNavigations/LogAnalysisNavigation.tsx
  web/src/components/modals/DeleteDataModelModal/DeleteDataModelModal.tsx
  web/src/components/modals/DeleteDataModelModal/graphql/deleteDataModel.generated.ts
  web/src/components/modals/DeleteDataModelModal/graphql/deleteDataModel.graphql
  web/src/components/modals/DeleteDataModelModal/index.tsx
  web/src/components/utils/Modal/ModalContext.tsx
  web/src/components/utils/Modal/ModalManager.tsx
  web/src/helpers/analytics.ts
  web/src/pages/CreateDataModel/CreateDataModel.test.tsx
  web/src/pages/CreateDataModel/CreateDataModel.tsx
  web/src/pages/EditDataModel/EditDataModel.test.tsx
  web/src/pages/EditDataModel/EditDataModel.tsx
  web/src/pages/ListDataModels/DataModelCard/DataModelCard.tsx
  web/src/pages/ListDataModels/DataModelCard/DataModelCardOptions/DataModelCardOptions.tsx
  web/src/pages/ListDataModels/DataModelCard/DataModelCardOptions/index.tsx
  web/src/pages/ListDataModels/DataModelCard/index.tsx
  web/src/pages/ListDataModels/EmptyDataFallback/EmptyDataFallback.tsx
  web/src/pages/ListDataModels/EmptyDataFallback/index.tsx
  web/src/pages/ListDataModels/ListDataModels.test.tsx
  web/src/pages/ListDataModels/ListDataModels.tsx
  web/src/pages/ListDataModels/graphql/listDataModels.generated.ts
  web/src/pages/ListDataModels/graphql/listDataModels.graphql
  web/src/pages/ListDataModels/index.tsx
  web/src/routes.tsx
Labels: sync-to-release, team:web

#2386 Make athena view generation more robust
  internal/log_analysis/athenaviews/athenaviews.go
  internal/log_analysis/athenaviews/athenaviews_test.go
Labels: sync-to-release, team:data analytics

#2394 Dynamic Alert fields
  api/graphql/schema.graphql
  web/__generated__/schema.tsx
  web/__tests__/__mocks__/builders.generated.ts
  web/src/components/forms/RuleForm/RuleFormTestResult/RuleFormTestResult.test.tsx
  web/src/components/forms/RuleForm/RuleFormTestResult/RuleFormTestResult.tsx
  web/src/components/forms/RuleForm/RuleFormTestResult/__snapshots__/RuleFormTestResult.test.tsx.snap
  web/src/components/forms/RuleForm/RuleFormTestSection/graphql/testRule.generated.ts
  web/src/components/forms/RuleForm/RuleFormTestSection/graphql/testRule.graphql
Labels: sync-to-release, team:web

#2392 Backport LogTypesAPI changes from enterprise
  api/lambda/logtypes/models_gen.go
  internal/core/logtypesapi/api.go
  internal/core/logtypesapi/available.go
  internal/core/logtypesapi/available_test.go
  internal/core/logtypesapi/customlogs.go
  internal/core/logtypesapi/customlogs_test.go
  internal/core/logtypesapi/dynamodb.go
  internal/core/logtypesapi/inmem.go
  internal/core/logtypesapi/lambdaclient_gen.go
  internal/core/logtypesapi/main/lambda.go
Labels: enterprise-backport, sync-to-release

#2408 Fix backwards compatibility issue
  internal/core/source_api/api/update_integration.go
Labels: sync-to-release

#2410 fix: issue where alert wouldn't render if rule got deleted
  web/src/pages/AlertDetails/PolicyAlertDetails/AlertDetailsInfo/AlertDetailsInfo.tsx
  web/src/pages/AlertDetails/PolicyAlertDetails/PolicyAlertDetails.tsx
  web/src/pages/AlertDetails/RuleAlertDetails/AlertDetailsInfo/AlertDetailsInfo.tsx
  web/src/pages/AlertDetails/RuleAlertDetails/RuleAlertDetails.tsx
Labels: bug, sync-to-release, team:web

#2413 Pass through Log Types filter
  internal/core/analysis_api/handlers/list_rules.go
Labels: bug, sync-to-release

#2352 Configurable dynamo KV store billing mode
  deployments/bootstrap.yml
  deployments/core.yml
  deployments/master.yml
  deployments/panther_config.yml
  tools/mage/deploy/config.go
  tools/mage/deploy/deploy.go
Labels: p2, team:core infra

#2419 Pass stack name correctly during master:deploy
  tools/mage/master/deploy.go
Labels: bug, p0, sync-to-release, team:core infra

#2378 Allow deploying multiple lambdas and stacks directly
  .all-contributorsrc
  tools/mage/deploy/deploy.go
Labels: mage, team:core infra

#2409 JSON serialization for alert context with immutable event objects
  internal/log_analysis/rules_engine/src/enriched_event.py
  internal/log_analysis/rules_engine/src/immutable.py
  internal/log_analysis/rules_engine/src/rule.py
  internal/log_analysis/rules_engine/tests/test_immutable.py
  internal/log_analysis/rules_engine/tests/test_rule.py
Labels: bug, sync-to-release, team:data processing

#2423 Fix placeholder text in Rule Create/Edit form Log Type dropdown
  web/src/components/forms/BaseRuleForm/BaseRuleFormCoreSection/BaseRuleFormCoreSection.tsx
Labels: team:web

#2418 Generated Alert Fields - Destinations Fix
  api/lambda/analysis/engine.go
  internal/core/analysis_api/analysis/rule_engine.go
Labels: bug, p0, sync-to-release, team:security engineering

#2406 Indicate missing fields in Rules and Policy creation forms
  web/src/components/buttons/SubmitButton/SubmitButton.test.tsx
  web/src/components/buttons/SubmitButton/SubmitButton.tsx
  web/src/components/buttons/SubmitButton/__snapshots__/SubmitButton.test.tsx.snap
  web/src/components/forms/PolicyForm/PolicyForm.tsx
  web/src/components/forms/RuleForm/RuleForm.tsx
Labels: team:web

#2430 Added message attributes to the messages requeued
  cmd/opstools/requeue/requeue.go
Labels: bug, sync-to-release, team:data processing

#2403 Introduce AWS WAF Web ACL log parser
  .gitignore
  internal/log_analysis/log_processor/parsers/awslogs/awslogs.go
  internal/log_analysis/log_processor/parsers/awslogs/testdata/waf_web_acl_tests.yml
  internal/log_analysis/log_processor/parsers/awslogs/waf_web_acl.go
  internal/log_analysis/log_processor/parsers/awslogs/waf_web_acl_test.go
Labels: logs, team:data processing

#2358 New devtool: filegen
  cmd/devtools/filegen/csv.go
  cmd/devtools/filegen/fields.go
  cmd/devtools/filegen/filegen.go
  cmd/devtools/filegen/filegen/main.go
  cmd/devtools/filegen/jsonl.go
  cmd/devtools/filegen/logtype/aws_cloudtrail.go
  cmd/devtools/filegen/logtype/aws_serveraccess.go
  cmd/devtools/filegen/logtype/gravitational_teleportaudit.go
  go.mod
  go.sum
Labels: team:data analytics

#2444 source-api: make UpdateStatus return error if source doesn't exist
  internal/core/source_api/api/update_status.go
  internal/core/source_api/ddb/update.go
  internal/core/source_api/main/integration_test.go
Labels: sync-to-release, team:data processing

#2443 [FE] Add outline only during tabbing
  web/public/index.ejs
  web/src/app.tsx
  web/src/components/Navigation/SecondaryNavigations/LogAnalysisNavigation.tsx
  web/src/hooks/useHiddenOutline.test.tsx
  web/src/hooks/useHiddenOutline.tsx
Labels: enhancement, team:web

#2442 [FE] Policy Form & Rule Form layout updates
  web/src/assets/masonry.svg
  web/src/components/buttons/SaveButton/__snapshots__/SaveButton.test.tsx.snap
  web/src/components/forms/BaseDetectionForm/BaseDetectionFormEditorSection/BaseDetectionFormEditorSection.tsx
  web/src/components/forms/BaseDetectionForm/BaseDetectionFormEditorSection/index.tsx
  web/src/components/forms/BaseDetectionForm/BaseDetectionFormTestSection/BaseDetectionFormTestSection.tsx
  web/src/components/forms/BaseDetectionForm/BaseDetectionFormTestSection/index.tsx
  web/src/components/forms/BaseDetectionForm/index.tsx
  web/src/components/forms/BaseRuleForm/BaseRuleFormCoreSection/BaseRuleFormCoreSection.tsx
  web/src/components/forms/PolicyForm/PolicyForm.tsx
  web/src/components/forms/PolicyForm/PolicyFormAutoRemediationSection/PolicyFormAutoRemediationFields.tsx
  web/src/components/forms/PolicyForm/PolicyFormAutoRemediationSection/PolicyFormAutoRemediationSection.tsx
  web/src/components/forms/PolicyForm/PolicyFormCoreSection/PolicyFormCoreSection.tsx
  web/src/components/forms/PolicyForm/PolicyFormCoreSection/index.tsx
  web/src/components/forms/PolicyForm/PolicyFormTestSection/PolicyFormTestSection.tsx
  web/src/components/forms/RuleForm/RuleForm.tsx
  web/src/components/forms/RuleForm/RuleFormCoreSection/RuleFormCoreSection.tsx
  web/src/components/forms/RuleForm/RuleFormCoreSection/index.tsx
  web/src/components/forms/RuleForm/RuleFormTestSection/RuleFormTestSection.tsx
  web/src/hooks/useListAvailableDestinations.tsx
  web/src/pages/EditPolicy/EditPolicy.test.tsx
  web/src/pages/EditPolicy/Skeleton/Skeleton.tsx
  web/src/pages/EditRule/EditRule.test.tsx
  web/src/pages/EditRule/EditRule.tsx
  web/src/pages/EditRule/Skeleton/Skeleton.tsx
Labels: team:web

#2391 Eliminate Enabled and Disabled options from sort By dropdown in Rules page
  api/graphql/schema.graphql
  web/__generated__/schema.tsx
  web/src/pages/ListRules/ListRulesFilters/ListRulesFilters.test.tsx
  web/src/pages/ListRules/ListRulesFilters/ListRulesFilters.tsx
  web/src/pages/ListRules/ListRulesFilters/__snapshots__/ListRulesFilters.test.tsx.snap
Labels: team:web

#2461 Improve rule engine efficiency by using MaximumBatchingWindowInSeconds
  deployments/log_analysis.yml
Labels: team:data analytics

#2459 [FE]: Unified Detection Creation Page
  package-lock.json
  package.json
  web/src/components/forms/PolicyForm/PolicyForm.tsx
  web/src/components/forms/RuleForm/RuleForm.tsx
  web/src/helpers/analytics.ts
  web/src/pages/CreateDetection/CreateDetection.test.tsx
  web/src/pages/CreateDetection/CreateDetection.tsx
  web/src/pages/CreateDetection/CreatePolicy/CreatePolicy.test.tsx
  web/src/pages/CreateDetection/CreatePolicy/CreatePolicy.tsx
  web/src/pages/CreateDetection/CreatePolicy/graphql/createPolicy.generated.ts
  web/src/pages/CreateDetection/CreatePolicy/graphql/createPolicy.graphql
  web/src/pages/CreateDetection/CreatePolicy/index.tsx
  web/src/pages/CreateDetection/CreateRule/CreateRule.test.tsx
  web/src/pages/CreateDetection/CreateRule/CreateRule.tsx
  web/src/pages/CreateDetection/CreateRule/graphql/createRule.generated.ts
  web/src/pages/CreateDetection/CreateRule/graphql/createRule.graphql
  web/src/pages/CreateDetection/CreateRule/index.tsx
  web/src/pages/CreateDetection/DetectionSelectionCard/DetectionSelectionCard.test.tsx
  web/src/pages/CreateDetection/DetectionSelectionCard/DetectionSelectionCard.tsx
  web/src/pages/CreateDetection/DetectionSelectionCard/__snapshots__/DetectionSelectionCard.test.tsx.snap
  web/src/pages/CreateDetection/DetectionSelectionCard/index.tsx
  web/src/pages/CreateDetection/index.tsx
  web/src/pages/EditRule/EditRule.test.tsx
  web/src/pages/EditRule/Skeleton/Skeleton.tsx
  web/src/pages/ListRules/ListRulesFilters/__snapshots__/ListRulesFilters.test.tsx.snap
  web/src/routes.tsx
  web/src/urls.ts
Labels: team:web

#2470 Fixes for ELBV2 scanning
  internal/compliance/aws_event_processor/processor/elbv2.go
  internal/compliance/aws_event_processor/processor/process.go
  internal/compliance/snapshot_poller/pollers/aws/clients.go
Labels: bug, cloud security, sync-to-release

#2464 [FE] Add Data Models to Bulk Uploader
  api/graphql/schema.graphql
  web/__generated__/schema.tsx
  web/__tests__/__mocks__/builders.generated.ts
  web/src/components/wizards/BulkUploaderWizard/BulkUploaderWizard.test.tsx
  web/src/components/wizards/BulkUploaderWizard/SuccessfulUploadPanel/SuccessfulUploadPanel.tsx
  web/src/components/wizards/BulkUploaderWizard/UploadPanel/UploadPanel.tsx
  web/src/components/wizards/BulkUploaderWizard/UploadPanel/graphql/uploadDetections.generated.ts
  web/src/components/wizards/BulkUploaderWizard/UploadPanel/graphql/uploadDetections.graphql
Labels: bug, sync-to-release, team:web

#2481 Update dependencies
  requirements.txt
Labels: security

#2483 [FE] Showcase dynamic alert field in details page
  api/graphql/schema.graphql
  web/__generated__/schema.tsx
  web/__tests__/__mocks__/builders.generated.ts
  web/src/graphql/fragments/AlertDetailsFull.generated.ts
  web/src/graphql/fragments/AlertDetailsFull.graphql
  web/src/pages/AlertDetails/RuleAlertDetails/AlertDetailsInfo/AlertDetailsInfo.test.tsx
  web/src/pages/AlertDetails/RuleAlertDetails/AlertDetailsInfo/AlertDetailsInfo.tsx
  web/src/pages/AlertDetails/RuleAlertDetails/AlertDetailsInfo/__snapshots__/AlertDetailsInfo.test.tsx.snap
Labels: bug, sync-to-release, team:web

#2485 fix: deployment
  deployments/appsync.yml
Labels: sync-to-release, team:web

#2478 [FE] Make sure Docs open in another tab
  web/src/components/Navigation/Navigation.tsx
  web/src/components/Navigation/__snapshots__/Navigation.test.tsx.snap
Labels: bug, team:web

#2457 test: mock debounce where needed and changed all waitMs to 1ms
  web/src/components/FieldPolicyChecker/FieldPolicyChecker.test.tsx
  web/src/components/JsonViewer/JsonViewer.test.tsx
  web/src/components/forms/AsanaDestinationForm/AsanaDestinationForm.test.tsx
  web/src/components/forms/CustomLogForm/CustomLogForm.test.tsx
  web/src/components/forms/CustomWebhookDestinationForm/CustomWebhookDestinationForm.test.tsx
  web/src/components/forms/DataModelForm/DataModelForm.test.tsx
  web/src/components/forms/GithubDestinationForm/GithubDestinationForm.test.tsx
  web/src/components/forms/JiraDestinationForm/JiraDestinationForm.test.tsx
  web/src/components/forms/MicrosoftTeamsDestinationForm/MicrosoftTeamsDestinationForm.test.tsx
  web/src/components/forms/OpsgenieDestinationForm/OpsGenieDestinationForm.test.tsx
  web/src/components/forms/PagerdutyDestinationForm/PagerdutyDestinationForm.test.tsx
  web/src/components/forms/SlackDestinationForm/SlackDestinationForm.test.tsx
  web/src/components/forms/SnsDestinationForm/SnsDestinationForm.test.tsx
  web/src/components/forms/SqsDestinationForm/SqsDestinationForm.test.tsx
  web/src/components/modals/ProfileSettingsModal/ProfileSettingsModal.test.tsx
  web/src/components/utils/FormSessionRestoration/FormSessionRestoration.test.tsx
  web/src/helpers/__tests__/analytics.test.tsx
  web/src/helpers/__tests__/errors.test.tsx
  web/src/pages/CreateComplianceSource/CreateComplianceSource.test.tsx
  web/src/pages/CreateCustomLog/CreateCustomLog.test.tsx
  web/src/pages/CreateDataModel/CreateDataModel.test.tsx
  web/src/pages/CreateLogSource/CreateS3LogSource/CreateS3LogSource.test.tsx
  web/src/pages/CreateLogSource/CreateSqsLogSource/CreateSqsLogSource.test.tsx
  web/src/pages/EditComplianceSource/ΕditComplianceSource.test.tsx
  web/src/pages/EditDataModel/EditDataModel.test.tsx
  web/src/pages/EditS3LogSource/ΕditS3LogSource.test.tsx
  web/src/pages/EditSqsLogSource/ΕditSqsLogSource.test.tsx
  web/src/pages/ListDestinations/DestinationCards/__tests__/DestinationCard.test.tsx
  web/src/pages/RuleDetails/RuleDetails.test.tsx
Labels: team:web

#2490 fix: updated label for S3 log source fields
  web/src/components/wizards/S3LogSourceWizard/S3SourceConfigurationPanel/S3SourceConfigurationPanel.tsx
  web/src/pages/CreateLogSource/CreateS3LogSource/CreateS3LogSource.test.tsx
  web/src/pages/EditS3LogSource/ΕditS3LogSource.test.tsx
Labels: sync-to-release

#2495 Hotfix: Cloud Security Source Options
  internal/core/source_api/api/put_integration.go
Labels: bug, sync-to-release

#2499 source-api: Don't return sources without populated IntegrationType
  internal/core/source_api/api/list_integrations.go
  internal/core/source_api/api/list_integrations_test.go
Labels: sync-to-release

#2502 [FE] Fix custom log modal deletion
  web/src/components/modals/DeleteCustomLogModal/DeleteCustomLogModal.tsx
Labels: bug, p1, sync-to-release, team:web

#2505 feat: upgrade version
  VERSION
Labels: sync-to-release

#2503 Cloud Security Source Options multiRegionScan Fix
  internal/compliance/snapshot_poller/pollers/aws/cloudformation_stack.go
  internal/compliance/snapshot_poller/pollers/aws/iam_user.go
  internal/compliance/snapshot_poller/pollers/aws/poll.go
  internal/compliance/snapshot_poller/pollers/lambda_test.go
  internal/core/source_api/api/update_integration_test.go
Labels: bug, sync-to-release

#2498 Handle unescaped space in request URL for ALB log entries
  internal/log_analysis/log_processor/parsers/awslogs/alb.go
  internal/log_analysis/log_processor/parsers/awslogs/alb_test.go
Labels: bug, data inputs, team:data processing

#2514 FE: Alert Routing for Destinations
  web/src/components/forms/AsanaDestinationForm/AsanaDestinationForm.test.tsx
  web/src/components/forms/BaseDestinationForm/BaseDestinationForm.test.tsx
  web/src/components/forms/BaseDestinationForm/BaseDestinationForm.tsx
  web/src/components/forms/CustomWebhookDestinationForm/CustomWebhookDestinationForm.test.tsx
  web/src/components/forms/GithubDestinationForm/GithubDestinationForm.test.tsx
  web/src/components/forms/JiraDestinationForm/JiraDestinationForm.test.tsx
  web/src/components/forms/MicrosoftTeamsDestinationForm/MicrosoftTeamsDestinationForm.test.tsx
  web/src/components/forms/OpsgenieDestinationForm/OpsGenieDestinationForm.test.tsx
  web/src/components/forms/PagerdutyDestinationForm/PagerdutyDestinationForm.test.tsx
  web/src/components/forms/SlackDestinationForm/SlackDestinationForm.test.tsx
  web/src/components/forms/SnsDestinationForm/SnsDestinationForm.test.tsx
  web/src/components/forms/SqsDestinationForm/SqsDestinationForm.test.tsx
  web/src/components/wizards/CreateDestinationWizard/ConfigureDestinationPanel/ConfigureDestinationPanel.tsx
  web/src/components/wizards/EditDestinationWizard/ConfigureDestinationPanel/ConfigureDestinationPanel.tsx
  web/src/helpers/utils.tsx
  web/src/pages/AlertDetails/RuleAlertDetails/AlertDetailsEvents/AlertDetailsEvents.tsx
  web/src/pages/CreateDestination/CreateDestination.test.tsx
  web/src/pages/EditDestination/EditDestination.test.tsx
  web/src/pages/ListAlerts/ListAlertFilters/DropdownFilters.tsx
  web/src/pages/ListDestinations/DestinationCards/AsanaDestinationCard.tsx
  web/src/pages/ListDestinations/DestinationCards/CustomWebhookDestinationCard.tsx
  web/src/pages/ListDestinations/DestinationCards/DestinationCard.tsx
  web/src/pages/ListDestinations/DestinationCards/GithubDestinationCard.tsx
  web/src/pages/ListDestinations/DestinationCards/JiraDestinationCard.tsx
  web/src/pages/ListDestinations/DestinationCards/MsTeamsDestinationCard.tsx
  web/src/pages/ListDestinations/DestinationCards/OpsGenieDestinationCard.tsx
  web/src/pages/ListDestinations/DestinationCards/PagerDutyDestinationCard.tsx
  web/src/pages/ListDestinations/DestinationCards/SlackDestinationCard.tsx
  web/src/pages/ListDestinations/DestinationCards/SnsDestinationCard.tsx
  web/src/pages/ListDestinations/DestinationCards/SqsDestinationCard.tsx
  web/src/pages/ListDestinations/DestinationCards/__tests__/AsanaDestinationCard.test.tsx
  web/src/pages/ListDestinations/DestinationCards/__tests__/CustomWebhookDestinationCard.test.tsx
  web/src/pages/ListDestinations/DestinationCards/__tests__/DestinationCard.test.tsx
  web/src/pages/ListDestinations/DestinationCards/__tests__/GithubDestinationCard.test.tsx
  web/src/pages/ListDestinations/DestinationCards/__tests__/JiraDestinationCard.test.tsx
  web/src/pages/ListDestinations/DestinationCards/__tests__/MsTeamsDestinationCard.test.tsx
  web/src/pages/ListDestinations/DestinationCards/__tests__/OpsGenieDestinationCard.test.tsx
  web/src/pages/ListDestinations/DestinationCards/__tests__/PagerDutyDestinationCard.test.tsx
  web/src/pages/ListDestinations/DestinationCards/__tests__/SlackDestinationCard.test.tsx
  web/src/pages/ListDestinations/DestinationCards/__tests__/SnsDestinationCard.test.tsx
  web/src/pages/ListDestinations/DestinationCards/__tests__/SqsDestinationCard.test.tsx
  web/src/pages/ListDestinations/DestinationCards/__tests__/__snapshots__/DestinationCard.test.tsx.snap
Labels: team:web

#2494 Add projection to list policies call
  internal/compliance/resource_processor/processor/analysis_api.go
Labels: bug, cloud security

#2538 Add analysis type to rules and policies
  api/lambda/analysis/models/policies.go
  api/lambda/analysis/models/rules.go
  internal/core/analysis_api/handlers/dynamo.go
  internal/core/analysis_api/main/integration_test.go
  internal/core/outputs_api/main/integration_test.go
Labels: enterprise-backport, team:data analytics

#2534 [FE] Backport UI changes from Enterprise
  api/graphql/schema.graphql
  web/__generated__/schema.tsx
  web/src/components/cards/RuleCard/RuleCard.tsx
  web/src/components/cards/RuleCard/RuleCardOptions/RuleCardOptions.tsx
  web/src/components/forms/RuleForm/RuleFormCoreSection/RuleFormCoreSection.tsx
  web/src/components/modals/DeletePolicyModal/DeletePolicyModal.tsx
  web/src/components/modals/DeleteRuleModal/DeleteRuleModal.tsx
  web/src/graphql/fragments/PolicyDetails.generated.ts
  web/src/graphql/fragments/RuleDetails.generated.ts
  web/src/hooks/useDetectionDestinations.tsx
  web/src/pages/AlertDetails/PolicyAlertDetails/AlertDetailsBanner/AlertDetailsBanner.tsx
  web/src/pages/AlertDetails/PolicyAlertDetails/AlertDetailsBanner/__snapshots__/AlertDetailsBanner.test.tsx.snap
  web/src/pages/AlertDetails/RuleAlertDetails/AlertDetailsBanner/AlertDetailsBanner.tsx
  web/src/pages/AlertDetails/RuleAlertDetails/AlertDetailsBanner/__snapshots__/AlertDetailsBanner.test.tsx.snap
  web/src/pages/EditPolicy/graphql/updatePolicy.generated.ts
  web/src/pages/ListPolicies/ListPoliciesTable/ListPoliciesTableRowOptions/ListPoliciesTableRowOptions.tsx
  web/src/pages/PolicyDetails/PolicyDetailsBanner/PolicyDetailsBanner.tsx
  web/src/pages/PolicyDetails/PolicyDetailsInfo/PolicyDetailsInfo.tsx
  web/src/pages/PolicyDetails/graphql/getPolicyDetails.generated.ts
  web/src/pages/PolicyDetails/graphql/getPolicyDetails.graphql
  web/src/pages/RuleDetails/RuleDetailsBanner/RuleDetailsBanner.tsx
Labels: enterprise-backport, team:web

#2545 Make athena views use only athena
  deployments/log_analysis.yml
  internal/log_analysis/athenaviews/athenaviews.go
  internal/log_analysis/athenaviews/athenaviews_test.go
  internal/log_analysis/datacatalog_updater/datacatalog/create_tables.go
  internal/log_analysis/datacatalog_updater/datacatalog/create_tables_test.go
  internal/log_analysis/datalake/athena/athenaviews/athenaviews.go
  internal/log_analysis/datalake/views/views.go
  internal/log_analysis/datalake/views/views_test.go
  pkg/testutils/awsmocks.go
Labels: team:data analytics

#2480 poll panther analysis
  api/lambda/analysis/configmodels.go
  api/lambda/analysis/models/api.go
  api/lambda/analysis/models/packs.go
  deployments/core.yml
  go.mod
  go.sum
  internal/core/analysis_api/handlers/bulk_upload.go
  internal/core/analysis_api/handlers/clients.go
  internal/core/analysis_api/handlers/dynamo.go
  internal/core/analysis_api/handlers/get.go
  internal/core/analysis_api/handlers/github.go
  internal/core/analysis_api/handlers/list_packs.go
  internal/core/analysis_api/handlers/pack.go
  internal/core/analysis_api/handlers/poll_packs.go
  internal/core/analysis_api/handlers/poll_packs_test.go
  internal/core/analysis_api/handlers/update_pack.go
  internal/core/analysis_api/handlers/update_pack_test.go
  internal/core/analysis_api/main/integration_test.go
  pkg/awskms/awskms.go
  pkg/github/github.go
Labels: team:security engineering
